// GENERATED by `npm run make:profile-art` from components/shared/profileScenes.ts.
// Do not edit: change the scene and run it again.
import type { ImageSourcePropType } from 'react-native';

export const PROFILE_ART_STAMP = '1bc0eec8c64e';

export interface ProfileSceneArt { name: string; source: ImageSourcePropType; sky: string; ground: string; focus: { x: number; y: number } }

export const PROFILE_SCENE_ART: Record<string, ProfileSceneArt> = {
  'woodcut-sky': { name: 'Open Sea', source: require('@/assets/images/profile/woodcut-sky.png'), sky: '#BBD6D3', ground: '#1E2F35', focus: { x: 790, y: 430 } },
  'night-spiral': { name: 'Moonlit Lake', source: require('@/assets/images/profile/night-spiral.png'), sky: '#1B2741', ground: '#101827', focus: { x: 780, y: 420 } },
  'sunburst': { name: 'Break in the Clouds', source: require('@/assets/images/profile/sunburst.png'), sky: '#93ABBC', ground: '#21301E', focus: { x: 620, y: 330 } },
  'the-peak': { name: 'The Peak', source: require('@/assets/images/profile/the-peak.png'), sky: '#C6B4CE', ground: '#151C23', focus: { x: 610, y: 360 } },
  'the-range': { name: 'The Range', source: require('@/assets/images/profile/the-range.png'), sky: '#DDE5EA', ground: '#1C2937', focus: { x: 380, y: 440 } },
  'rain-field': { name: 'Weather', source: require('@/assets/images/profile/rain-field.png'), sky: '#A7B6AE', ground: '#222A1F', focus: { x: 520, y: 420 } },
  'small-house': { name: 'The Small House', source: require('@/assets/images/profile/small-house.png'), sky: '#2D4560', ground: '#1A2621', focus: { x: 730, y: 400 } },
  'the-tower': { name: 'The Lighthouse', source: require('@/assets/images/profile/the-tower.png'), sky: '#5B6286', ground: '#1C1923', focus: { x: 320, y: 400 } },
  'stone-bridge': { name: 'The Crossing', source: require('@/assets/images/profile/stone-bridge.png'), sky: '#C8DCD3', ground: '#1E2A21', focus: { x: 600, y: 470 } },
  'the-ruins': { name: 'The Ruins', source: require('@/assets/images/profile/the-ruins.png'), sky: '#B5A3C0', ground: '#29212F', focus: { x: 540, y: 380 } },
};

/** The Pass tab's reading room. */
export const READING_ROOM_ART = { source: require('@/assets/images/pass/reading-room.png') as ImageSourcePropType, sky: '#182B2C', ground: '#132120' };
