// GENERATED by scripts/make-narration.mjs. Do not edit by hand.
//
// Which lessons are narrated, the clip for each spoken beat, and when each word of it
// starts (estimated from the clip; see the script). A lesson that is not here is not
// narrated, and plays exactly as it did before narration existed.
import type { NarratedLine } from './types';

export const NARRATION: Record<string, Record<number, NarratedLine>> = {
  "ethics-ethics-9": {
    0: {
      clip: require('../../assets/narration/ethics-ethics-9/beat-00.wav'),
      dur: 4.96,
      text: "Most hard choices have a right answer buried in them somewhere. Some do not.",
      words: [0.00, 0.19, 0.37, 0.71, 1.05, 1.42, 1.60, 1.94, 2.28, 2.47, 2.65, 4.20, 4.56, 4.76],
    },
    1: {
      clip: require('../../assets/narration/ethics-ethics-9/beat-01.wav'),
      dur: 2.08,
      text: "Some leave a mark on you whichever way you go.",
      words: [0.00, 0.28, 0.57, 0.72, 0.88, 1.04, 1.20, 1.61, 1.76, 1.92],
    },
    2: {
      clip: require('../../assets/narration/ethics-ethics-9/beat-02.wav'),
      dur: 6.00,
      text: "In 1940 a student came to Sartre. His brother had been killed by the Germans and he wanted to fight.",
      words: [0.01, 0.21, 0.85, 1.05, 1.40, 1.76, 1.96, 2.83, 3.00, 3.31, 3.49, 3.66, 3.97, 4.14, 4.32, 4.63, 5.11, 5.28, 5.59, 5.77],
    },
    3: {
      clip: require('../../assets/narration/ethics-ethics-9/beat-03.wav'),
      dur: 3.52,
      text: "The student’s mother lived for him alone, and his leaving would break her.",
      words: [0.01, 0.18, 0.48, 0.78, 1.08, 1.25, 1.42, 2.26, 2.45, 2.63, 2.96, 3.15, 3.33],
    },
    4: {
      clip: require('../../assets/narration/ethics-ethics-9/beat-04.wav'),
      dur: 7.28,
      text: "Neither claim outranks the other. This is a dilemma, not a hard sum, because there is no scale both of them fit on.",
      words: [0.01, 0.42, 0.64, 1.05, 1.27, 2.43, 2.61, 2.78, 2.96, 3.66, 3.89, 4.12, 4.35, 4.90, 5.37, 5.69, 5.87, 6.05, 6.37, 6.55, 6.73, 6.91, 7.09],
    },
    6: {
      clip: require('../../assets/narration/ethics-ethics-9/beat-06.wav'),
      dur: 4.20,
      text: "The student goes. Say he was right to, as most people think he was.",
      words: [0.01, 0.27, 0.75, 1.43, 1.64, 1.84, 2.05, 2.25, 2.83, 3.03, 3.23, 3.59, 3.79, 3.99],
    },
    7: {
      clip: require('../../assets/narration/ethics-ethics-9/beat-07.wav'),
      dur: 5.40,
      text: "Now look at the board: the other claim has not moved. Nothing about his choice removed it.",
      words: [0.00, 0.18, 0.36, 0.53, 0.71, 1.38, 1.59, 1.96, 2.17, 2.37, 2.58, 3.53, 3.86, 4.19, 4.37, 4.69, 5.17],
    },
  },
};
