// GENERATED by scripts/make-professor-voice.mjs — do not edit by hand.
//
// The professor's six lines, as they sit in assets/professor/voice/professor.mp3.
// Zero imports, so the timeline that reads this can be stepped in plain Node.
//
//   key    the take, and the line in professorScript.ts it says
//   text   what he says
//   at     where the line starts in the MP3, seconds
//   dur    how long the take runs, seconds
//   words  when each word starts, seconds from the start of the line (estimated from
//          the pauses in the take; Chirp 3 HD returns no word timings)

export interface VoiceLine {
  key: string;
  text: string;
  at: number;
  dur: number;
  words: number[];
}

export const VOICE_LINES: VoiceLine[] = [
  {
    key: "p1",
    text: "Welcome. Before your first lesson, let me show you what you're about to learn.",
    at: 0,
    dur: 4.517,
    words: [0.01, 0.54, 1.52, 1.73, 1.93, 2.3, 2.5, 2.7, 2.91, 3.11, 3.32, 3.68, 4.05, 4.26],
  },
  {
    key: "p2",
    text: "Philosophy has six branches, and each one trains a skill you use every day.",
    at: 4.917,
    dur: 5.503,
    words: [0, 0.83, 1.07, 1.31, 2.21, 2.41, 2.62, 2.98, 3.19, 3.39, 3.6, 3.8, 4.17, 4.7],
  },
  {
    key: "p3",
    text: "Logic teaches you to spot a bad argument before it fools you. Ethics helps you decide what’s right when it’s hard.",
    at: 10.821,
    dur: 7.673,
    words: [0, 0.39, 0.77, 0.99, 1.2, 1.41, 1.63, 1.84, 2.4, 2.96, 3.17, 3.39, 4.08, 4.52, 4.76, 5, 5.64, 5.88, 6.12, 6.36, 6.61],
  },
  {
    key: "p4",
    text: "Epistemology asks how you know what you know, which matters every time you read the news.",
    at: 18.894,
    dur: 5.883,
    words: [0.01, 1.12, 1.34, 1.56, 1.78, 2.01, 2.23, 2.45, 3.23, 3.41, 3.74, 4.22, 4.55, 4.73, 4.91, 5.1],
  },
  {
    key: "p5",
    text: "Every lesson is short, narrated and animated, and it ends with a question you have to think through.",
    at: 25.177,
    dur: 6.053,
    words: [0.02, 0.5, 0.82, 1.01, 1.39, 1.88, 2.07, 3.18, 3.35, 3.53, 3.7, 3.87, 4.05, 4.36, 4.53, 4.84, 5.01, 5.19],
  },
  {
    key: "p6",
    text: "Every lesson comes with the Scholar’s Pass, and your first three days are free.",
    at: 31.631,
    dur: 4.584,
    words: [0.02, 0.51, 0.86, 1.2, 1.39, 1.58, 1.92, 2.61, 2.86, 3.12, 3.37, 3.62, 3.87, 4.33],
  },
];
