// GENERATED by `npm run make:road-art`. Do not edit.
// Each road's scenery layers as baked pictures, in sceneLayers' order (make-road-art.mjs).

export const ROAD_SCALE = 2;

export const ROAD_STAMP: Record<string, string> = {
  'philosophy:0': 'e4189763da9162d2',
  'psychology:0': '81345d338064b985',
  'personal-growth:0': '1723bfd9324ad4e6',
  'business:0': 'd737f0974aca4f34',
  'economics:0': '926f39762fdd512e',
  'science:0': '746c846550c945dd',
  'history:0': 'f5c0ac9c8963c956',
};

export const ROAD_ART: Record<string, number[]> = {
  'philosophy:0': [
    require('../../assets/images/road/philosophy-0-0.png'),
    require('../../assets/images/road/philosophy-0-1.png'),
    require('../../assets/images/road/philosophy-0-2.png'),
    require('../../assets/images/road/philosophy-0-3.png'),
    require('../../assets/images/road/philosophy-0-4.png'),
    require('../../assets/images/road/philosophy-0-5.png'),
    require('../../assets/images/road/philosophy-0-6.png'),
  ],
  'psychology:0': [
    require('../../assets/images/road/psychology-0-0.png'),
    require('../../assets/images/road/psychology-0-1.png'),
    require('../../assets/images/road/psychology-0-2.png'),
    require('../../assets/images/road/psychology-0-3.png'),
    require('../../assets/images/road/psychology-0-4.png'),
    require('../../assets/images/road/psychology-0-5.png'),
  ],
  'personal-growth:0': [
    require('../../assets/images/road/personal-growth-0-0.png'),
    require('../../assets/images/road/personal-growth-0-1.png'),
    require('../../assets/images/road/personal-growth-0-2.png'),
    require('../../assets/images/road/personal-growth-0-3.png'),
    require('../../assets/images/road/personal-growth-0-4.png'),
    require('../../assets/images/road/personal-growth-0-5.png'),
    require('../../assets/images/road/personal-growth-0-6.png'),
  ],
  'business:0': [
    require('../../assets/images/road/business-0-0.png'),
    require('../../assets/images/road/business-0-1.png'),
    require('../../assets/images/road/business-0-2.png'),
    require('../../assets/images/road/business-0-3.png'),
  ],
  'economics:0': [
    require('../../assets/images/road/economics-0-0.png'),
    require('../../assets/images/road/economics-0-1.png'),
    require('../../assets/images/road/economics-0-2.png'),
    require('../../assets/images/road/economics-0-3.png'),
    require('../../assets/images/road/economics-0-4.png'),
    require('../../assets/images/road/economics-0-5.png'),
    require('../../assets/images/road/economics-0-6.png'),
  ],
  'science:0': [
    require('../../assets/images/road/science-0-0.png'),
    require('../../assets/images/road/science-0-1.png'),
    require('../../assets/images/road/science-0-2.png'),
    require('../../assets/images/road/science-0-3.png'),
    require('../../assets/images/road/science-0-4.png'),
    require('../../assets/images/road/science-0-5.png'),
  ],
  'history:0': [
    require('../../assets/images/road/history-0-0.png'),
    require('../../assets/images/road/history-0-1.png'),
    require('../../assets/images/road/history-0-2.png'),
    require('../../assets/images/road/history-0-3.png'),
    require('../../assets/images/road/history-0-4.png'),
    require('../../assets/images/road/history-0-5.png'),
    require('../../assets/images/road/history-0-6.png'),
  ],
};
