// GENERATED by scripts/make-welcome-voice.mjs — do not edit by hand.
//
// The seated host's seven lines on the first screen, as they sit in
// assets/welcome/voice/welcome.mp3. Zero imports, so the timeline that reads this can
// be stepped in plain Node.
//
//   text   what he says, as the speech bubble shows it
//   pages  the index of the first word on each page of the bubble
//   at     where the line starts in the MP3, seconds
//   dur    how long the take runs, seconds
//   words  when each word starts, seconds from the start of the line (estimated from
//          the pauses in the take; Chirp 3 HD returns no word timings)

export interface VoiceLine {
  text: string;
  pages: number[];
  at: number;
  dur: number;
  words: number[];
}

export const VOICE_LINES: VoiceLine[] = [
  {
    text: "So… you want to learn philosophy?",
    pages: [0],
    at: 0,
    dur: 2.424,
    words: [0.01, 1.09, 1.26, 1.44, 1.61, 1.78],
  },
  {
    text: "Or possibly… you're already a well-distinguished individual, getting back into it.",
    pages: [0, 7],
    at: 2.824,
    dur: 4.691,
    words: [0.01, 0.23, 1.21, 1.52, 1.96, 2.13, 2.85, 3.7, 4.01, 4.18, 4.48],
  },
  {
    text: "Whichever the case, you're here to learn.",
    pages: [0],
    at: 7.916,
    dur: 2.290,
    words: [0.02, 0.46, 0.63, 1.41, 1.69, 1.98, 2.13],
  },
  {
    text: "And I have the perfect program for you, to achieve your goals in vast knowledge of the subject!",
    pages: [0, 8],
    at: 10.606,
    dur: 4.673,
    words: [0.01, 0.17, 0.33, 0.62, 0.78, 1.06, 1.35, 1.51, 2.09, 2.27, 2.75, 2.94, 3.12, 3.31, 3.49, 3.97, 4.15, 4.34],
  },
  {
    text: "The only thing I ask of you… is mental effort, and curiosity.",
    pages: [0],
    at: 15.679,
    dur: 3.612,
    words: [0, 0.18, 0.52, 0.7, 0.89, 1.07, 1.25, 1.92, 2.1, 2.44, 2.77, 2.95],
  },
  {
    text: "As Socrates once said, “The unexamined life is not worth living.”",
    pages: [0, 4],
    at: 19.692,
    dur: 4.544,
    words: [0.01, 0.22, 0.75, 1.12, 2.24, 2.43, 3.25, 3.6, 3.8, 3.99, 4.19],
  },
  {
    text: "Thus begins your journey.",
    pages: [0],
    at: 24.636,
    dur: 1.650,
    words: [0, 0.27, 0.77, 1.04],
  },
];
