// GENERATED by scripts/make-welcome-voice.mjs — do not edit by hand.
//
// The seated host's lines on the first screen, as they sit in
// assets/welcome/voice/welcome.mp3. Zero imports, so the timeline that reads this can
// be stepped in plain Node.
//
//   text   what he says, as the speech bubble shows it
//   pages  the index of the first word on each page of the bubble
//   rows   the index of every word that starts a hand-set row (the bubble does not wrap)
//   at    where the line starts in the MP3, seconds
//   dur    how long the take runs, seconds
//   words  when each word starts, seconds from the start of the line (estimated from
//          the pauses in the take; Chirp 3 HD returns no word timings)

export interface VoiceLine {
  text: string;
  pages: number[];
  rows: number[];
  at: number;
  dur: number;
  words: number[];
}

export const VOICE_LINES: VoiceLine[] = [
  {
    text: "Welcome. My name is Alfred.",
    pages: [0],
    rows: [1],
    at: 0,
    dur: 2.300,
    words: [0.02, 0.96, 1.15, 1.51, 1.7],
  },
  {
    text: "And I will be walking you through any subject of your choosing.",
    pages: [0, 6],
    rows: [9],
    at: 2.7,
    dur: 3.530,
    words: [0, 0.22, 0.43, 0.65, 0.86, 1.25, 1.47, 1.68, 2.07, 2.46, 2.68, 2.89],
  },
  {
    text: "Between philosophy, psychology, business, science, history, and more.",
    pages: [0, 4],
    rows: [2],
    at: 6.63,
    dur: 5.290,
    words: [0, 0.4, 1.31, 2.23, 3, 3.88, 4.56, 4.73],
  },
  {
    text: "Turn on your mind to curiosity, and begin this wonderful journey of learning.",
    pages: [0, 6],
    rows: [4, 10],
    at: 12.32,
    dur: 4.880,
    words: [0.03, 0.26, 0.5, 0.73, 0.97, 1.2, 2.16, 2.39, 2.79, 3.02, 3.6, 4.01, 4.23],
  },
];
