// GENERATED by `npm run make:quickstart` from components/home/quickStartScenes.ts.
// Do not edit: change the scene and run it again.
import type { ImageSourcePropType } from 'react-native';
import type { QsSubject } from './quickStartScenes';

export interface QsArt {
  id: string;
  source: ImageSourcePropType;
  sky: string;
  ground: string;
}

export const QS_ART: Record<QsSubject, readonly QsArt[]> = {
  'philosophy': [
    { id: 'philosophy-1', source: require('@/assets/images/quickstart/philosophy-1.png'), sky: '#EFE3CB', ground: '#26282C' },
    { id: 'philosophy-2', source: require('@/assets/images/quickstart/philosophy-2.png'), sky: '#2B2E33', ground: '#1E2024' },
    { id: 'philosophy-3', source: require('@/assets/images/quickstart/philosophy-3.png'), sky: '#3A3950', ground: '#1F1C28' },
  ],
  'economics': [
    { id: 'economics-1', source: require('@/assets/images/quickstart/economics-1.png'), sky: '#EEE4CF', ground: '#1F2A33' },
    { id: 'economics-2', source: require('@/assets/images/quickstart/economics-2.png'), sky: '#F2E6CF', ground: '#252A2D' },
    { id: 'economics-3', source: require('@/assets/images/quickstart/economics-3.png'), sky: '#34506A', ground: '#1C2733' },
  ],
  'psychology': [
    { id: 'psychology-1', source: require('@/assets/images/quickstart/psychology-1.png'), sky: '#DCD5E7', ground: '#23243A' },
    { id: 'psychology-2', source: require('@/assets/images/quickstart/psychology-2.png'), sky: '#D6CEDD', ground: '#24233A' },
    { id: 'psychology-3', source: require('@/assets/images/quickstart/psychology-3.png'), sky: '#3F4466', ground: '#1F2035' },
  ],
  'personal-growth': [
    { id: 'personal-growth-1', source: require('@/assets/images/quickstart/personal-growth-1.png'), sky: '#F4E2BF', ground: '#262B1F' },
    { id: 'personal-growth-2', source: require('@/assets/images/quickstart/personal-growth-2.png'), sky: '#E7E0CC', ground: '#2A2A24' },
    { id: 'personal-growth-3', source: require('@/assets/images/quickstart/personal-growth-3.png'), sky: '#DCE0C6', ground: '#262B1F' },
  ],
  'business': [
    { id: 'business-1', source: require('@/assets/images/quickstart/business-1.png'), sky: '#F0CFA8', ground: '#221E1B' },
    { id: 'business-2', source: require('@/assets/images/quickstart/business-2.png'), sky: '#E7DDCB', ground: '#23201D' },
    { id: 'business-3', source: require('@/assets/images/quickstart/business-3.png'), sky: '#D8CDBB', ground: '#221E1B' },
  ],
  'science': [
    { id: 'science-1', source: require('@/assets/images/quickstart/science-1.png'), sky: '#1F3F4A', ground: '#132A30' },
    { id: 'science-2', source: require('@/assets/images/quickstart/science-2.png'), sky: '#DCE7E3', ground: '#162226' },
    { id: 'science-3', source: require('@/assets/images/quickstart/science-3.png'), sky: '#12222E', ground: '#18394A' },
  ],
  'history': [
    { id: 'history-1', source: require('@/assets/images/quickstart/history-1.png'), sky: '#F3DEB6', ground: '#2B2320' },
    { id: 'history-2', source: require('@/assets/images/quickstart/history-2.png'), sky: '#E8DCC6', ground: '#28231F' },
    { id: 'history-3', source: require('@/assets/images/quickstart/history-3.png'), sky: '#5A3A2A', ground: '#4A2F22' },
  ],
};
