// GENERATED by scripts/make-sfx.mjs — do not edit. Every clip is a CC0 recording
// from Freesound (scripts/lib/sfxcuts.mjs SOURCES), cut and levelled there (LESSON_RULES AT6).

export type SfxId = 'court' | 'muffled' | 'laugh' | 'murmur' | 'gasp' | 'cheer' | 'door' | 'steps' | 'pour' | 'drip' | 'discs';

/** The clips, which are background loops, and how long each is heard (seconds). */
export const SFX: Record<SfxId, { clip: number; bed: boolean; audible: number }> = {
  court: { clip: require('../../assets/sfx/court.mp3'), bed: true, audible: 37.5 },
  muffled: { clip: require('../../assets/sfx/muffled.mp3'), bed: true, audible: 37.5 },
  laugh: { clip: require('../../assets/sfx/laugh.mp3'), bed: false, audible: 4.75 },
  murmur: { clip: require('../../assets/sfx/murmur.mp3'), bed: false, audible: 4.55 },
  gasp: { clip: require('../../assets/sfx/gasp.mp3'), bed: false, audible: 3.15 },
  cheer: { clip: require('../../assets/sfx/cheer.mp3'), bed: false, audible: 7.35 },
  door: { clip: require('../../assets/sfx/door.mp3'), bed: false, audible: 2 },
  steps: { clip: require('../../assets/sfx/steps.mp3'), bed: false, audible: 2.5 },
  pour: { clip: require('../../assets/sfx/pour.mp3'), bed: false, audible: 7.6 },
  drip: { clip: require('../../assets/sfx/drip.mp3'), bed: false, audible: 0.15 },
  discs: { clip: require('../../assets/sfx/discs.mp3'), bed: false, audible: 3.85 },
};
