// THE MUST-SEE RULE — which of a beat's measured words the camera has to hold.
//
// Its own file, and with no imports, for the same reason rig.ts and camera.ts have
// none: the rule is the arguable part of H60c and it should be possible to change
// it and regenerate the whole table (scripts/regen-must.mjs) without paying for
// another browser sweep. measure-must.mjs collects the words; this decides what
// they add up to.

export const STAGE_W = 400;
export const STAGE_H = 560;

/** The same word read twice within one beat, covered across both readings. */
export function mergeReadings(a = [], b = []) {
  const by = new Map();
  for (const it of [...a, ...b]) {
    const prev = by.get(it.t);
    if (!prev) { by.set(it.t, it.b.slice()); continue; }
    const x0 = Math.min(prev[0], it.b[0]);
    const y0 = Math.min(prev[1], it.b[1]);
    const x1 = Math.max(prev[0] + prev[2], it.b[0] + it.b[2]);
    const y1 = Math.max(prev[1] + prev[3], it.b[1] + it.b[3]);
    by.set(it.t, [x0, y0, x1 - x0, y1 - y0]);
  }
  return [...by.entries()].map(([t, b2]) => ({ t, b: b2.map((n) => +n.toFixed(1)) }));
}

/**
 * Every word the beat has on stage, and no cleverer than that.
 *
 * The obvious refinement is to keep only the words this beat BROUGHT ON, treating
 * anything carried over unmoved as chrome — a timeline's "EARLIER"/"LATER", a title
 * that stays up all lesson — on the reasoning that H60c is about "a beat that shows
 * the reader a SPECIFIC thing". That rule was written and then dropped, because the
 * plain union turned out to cost far less than it looked like it would. Measured
 * across the sample: 47% of beats reduce scale at all, and the reductions are
 * 1.18 -> 1.05…1.16 and 1.40 -> 1.12…1.14. The camera still pans, still drifts,
 * still slides its centre; it stops pushing PAST the words.
 *
 * Buying back that last tenth of zoom would have cost the guarantee. Under the
 * union, "no word the scene draws is ever sliced" is a property check-frame.mjs can
 * verify outright; under the chrome rule it becomes "no word we judged important",
 * which nothing can check and which leaves the reader looking at half of "LATER".
 * The wrong trade at 0.1x.
 *
 * Where the union really does flatten a lesson — metaphysics-being-7 caps at 1.05
 * because it prints axis labels hard against both edges of the stage — the fix is
 * in the SCENE, moving those labels inboard, not in the camera. `prev` stays in the
 * signature, and the raw per-word measurements stay in the sidecar JSON, so that
 * argument can be reopened cheaply.
 */
export function mustBox(items, _prev) {
  if (!items || !items.length) return null;
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  for (const it of items) {
    x0 = Math.min(x0, it.b[0]); y0 = Math.min(y0, it.b[1]);
    x1 = Math.max(x1, it.b[0] + it.b[2]); y1 = Math.max(y1, it.b[1] + it.b[3]);
  }
  x0 = Math.floor(x0) - 2; y0 = Math.floor(y0) - 2;
  x1 = Math.ceil(x1) + 2; y1 = Math.ceil(y1) + 2;
  // CLAMPED TO THE STAGE. A word may sit a few units off the edge (the on-stage
  // filter keeps anything whose CENTRE is on), and containShot's two clamps — "the
  // box's left edge is visible" and "its right edge is visible" — contradict each
  // other once the box is wider than the frame, with the second winning. The result
  // is a shot pushed off the design space to chase a rectangle that reaches past
  // it. Nothing outside the stage can be shown anyway, so ask for nothing.
  x0 = Math.max(0, x0); y0 = Math.max(0, y0);
  x1 = Math.min(STAGE_W, x1); y1 = Math.min(STAGE_H, y1);
  if (x1 - x0 < 1 || y1 - y0 < 1) return null;
  return [x0, y0, x1 - x0, y1 - y0];
}

/** The generated file, from a map of lesson id -> per-beat word lists. */
export function renderTable(words, stamps) {
  const boxes = {};
  for (const [id, per] of Object.entries(words)) {
    boxes[id] = per.map((items, i) => mustBox(items, i > 0 ? per[i - 1] : null));
  }
  const lines = [
    '// GENERATED by scripts/measure-must.mjs — do not hand-edit.',
    '//',
    '// Per beat, the box (scene coordinates) the camera must contain: the union of the',
    '// words that lesson has on stage at that moment. H60c — "if the reader is told to',
    '// look at it, the camera must frame it" — with the looking-at measured from what',
    '// the scene actually draws rather than declared by hand in 800 places.',
    '//',
    '// CinematicPlayer feeds these to containShot, which only ever LOOSENS a shot: the',
    '// scale comes down to fit and the centre slides the shortest distance. A beat whose',
    '// shot already showed its words is returned untouched, so the authored camera work',
    '// survives everywhere it was already right.',
    '//',
    '// MUST_STAMP fingerprints the scene and script each box was measured from.',
    '// validate-cinematic fails when one diverges, because the dangerous direction is',
    '// silent: a box that has gone stale and too SMALL lets a push crop the very thing',
    '// it was recorded to protect. Re-run measure-must.mjs after changing a layout.',
    '',
    'export type MustBox = readonly [x: number, y: number, w: number, h: number];',
    '',
    'export const MUST: Record<string, readonly (MustBox | null)[]> = {',
  ];
  for (const id of Object.keys(boxes).sort()) {
    lines.push(`  '${id}': [${boxes[id].map((b) => (b ? `[${b.join(', ')}]` : 'null')).join(', ')}],`);
  }
  lines.push('};', '', 'export const MUST_STAMP: Record<string, string> = {');
  for (const id of Object.keys(stamps).sort()) lines.push(`  '${id}': '${stamps[id]}',`);
  lines.push('};', '');
  return { text: lines.join('\n'), boxes };
}
