// ─────────────────────────────────────────────────────────────────────────────
// THE SOUND EFFECTS' SOURCES AND CUTS (LESSON_RULES AT6), read by scripts/make-sfx.mjs,
// which makes the clips, and scripts/check-sfx.mjs, which holds them. Zero imports.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Where each recording comes from. `id` is Freesound's, and `licence` was read off the
 * sound's own page when it was fetched (not trusted from a search filter).
 */
export const SOURCES = {
  crowd: { id: 546676, by: 'trezz77', title: 'Crowd talking / murmur', url: 'https://freesound.org/people/trezz77/sounds/546676/', licence: 'CC0 1.0' },
  laugh: { id: 346682, by: 'deleted_user_2104797', title: 'Crowd awkward laughter.wav', url: 'https://freesound.org/s/346682/', licence: 'CC0 1.0' },
  murmur: { id: 466767, by: 'stewadosan', title: 'Murmur.wav', url: 'https://freesound.org/people/stewadosan/sounds/466767/', licence: 'CC0 1.0' },
  gasp: { id: 324898, by: 'deleted_user_2104797', title: 'Crowd shock.wav', url: 'https://freesound.org/s/324898/', licence: 'CC0 1.0' },
  cheer: { id: 365132, by: 'SoundsExciting', title: 'Crowd Cheering', url: 'https://freesound.org/people/SoundsExciting/sounds/365132/', licence: 'CC0 1.0' },
  door: { id: 125957, by: 'Ryding', title: 'Opening a creaking door', url: 'https://freesound.org/people/Ryding/sounds/125957/', licence: 'CC0 1.0' },
  steps: { id: 331451, by: 'ralph.whitehead', title: 'Walking On A Wooden Floor', url: 'https://freesound.org/people/ralph.whitehead/sounds/331451/', licence: 'CC0 1.0' },
  pour: { id: 163733, by: 'mrbriandesign', title: 'pouring water 02.wav', url: 'https://freesound.org/people/mrbriandesign/sounds/163733/', licence: 'CC0 1.0' },
  drip: { id: 683102, by: 'florianreichelt', title: 'water drop', url: 'https://freesound.org/people/florianreichelt/sounds/683102/', licence: 'CC0 1.0' },
  discs: { id: 613312, by: 'eZZin', title: 'Coins.wav', url: 'https://freesound.org/people/eZZin/sounds/613312/', licence: 'CC0 1.0' },
  // every lesson's places and actions (AT8, 2026-10-03)
  chalk: { id: 398491, by: 'Anthousai', title: 'writing - chalk - center 01.wav', url: 'https://freesound.org/people/Anthousai/sounds/398491/', licence: 'CC0 1.0' },
  chalktap: { id: 258092, by: 'joedeshon', title: 'tap_on_chalkboard.wav', url: 'https://freesound.org/people/joedeshon/sounds/258092/', licence: 'CC0 1.0' },
  coinflip: { id: 181189, by: 'Raventhornn', title: 'coin flip.wav', url: 'https://freesound.org/people/Raventhornn/sounds/181189/', licence: 'CC0 1.0' },
  paper: { id: 211246, by: 'Tomoyo Ichijouji', title: 'PageRustle', url: 'https://freesound.org/people/Tomoyo Ichijouji/sounds/211246/', licence: 'CC0 1.0' },
  tear: { id: 181773, by: 'keweldog', title: 'tearing paper4.wav', url: 'https://freesound.org/people/keweldog/sounds/181773/', licence: 'CC0 1.0' },
  pin: { id: 446634, by: 'Nicolas4677', title: 'ThumbTack', url: 'https://freesound.org/people/Nicolas4677/sounds/446634/', licence: 'CC0 1.0' },
  stamp: { id: 470710, by: 'I.fekry', title: 'traditional stamp.wav', url: 'https://freesound.org/people/I.fekry/sounds/470710/', licence: 'CC0 1.0' },
  book: { id: 543572, by: 'BiancaDrey', title: 'openingandclosingabook.wav', url: 'https://freesound.org/people/BiancaDrey/sounds/543572/', licence: 'CC0 1.0' },
  cup: { id: 568758, by: 'bowlingballout', title: 'Cup and Saucer 2.wav', url: 'https://freesound.org/people/bowlingballout/sounds/568758/', licence: 'CC0 1.0' },
  mug: { id: 404922, by: 'squidge316', title: 'putting down a mug on a table.wav', url: 'https://freesound.org/people/squidge316/sounds/404922/', licence: 'CC0 1.0' },
  stir: { id: 181716, by: 'keweldog', title: 'stirring coffee.wav', url: 'https://freesound.org/people/keweldog/sounds/181716/', licence: 'CC0 1.0' },
  coffee: { id: 658711, by: 'tlabrant1', title: 'Pouring a cup of coffee.wav', url: 'https://freesound.org/people/tlabrant1/sounds/658711/', licence: 'CC0 1.0' },
  freewheel: { id: 378211, by: 'fredelisle', title: 'Bike click', url: 'https://freesound.org/people/fredelisle/sounds/378211/', licence: 'CC0 1.0' },
  wooddrop: { id: 723568, by: 'CosmoX45', title: 'wood drop', url: 'https://freesound.org/people/CosmoX45/sounds/723568/', licence: 'CC0 1.0' },
  planks: { id: 577455, by: 'Manim8', title: 'Wood Fall 2.wav', url: 'https://freesound.org/people/Manim8/sounds/577455/', licence: 'CC0 1.0' },
  cardflip: { id: 84322, by: 'Splashdust', title: 'flipCard.wav', url: 'https://freesound.org/people/Splashdust/sounds/84322/', licence: 'CC0 1.0' },
  tealid: { id: 390342, by: 'megashroom', title: 'Teapot Lid Small 170428_1476.wav', url: 'https://freesound.org/people/megashroom/sounds/390342/', licence: 'CC0 1.0' },
  jar: { id: 235498, by: 'ekfink', title: 'glass jar_set on table_2.wav', url: 'https://freesound.org/people/ekfink/sounds/235498/', licence: 'CC0 1.0' },
  jarbreak: { id: 141563, by: 'avrahamy', title: 'Glass Break', url: 'https://freesound.org/people/avrahamy/sounds/141563/', licence: 'CC0 1.0' },
  shards: { id: 483363, by: 'Zeinel', title: 'Glass broken.mp3', url: 'https://freesound.org/people/Zeinel/sounds/483363/', licence: 'CC0 1.0' },
  knock: { id: 629987, by: 'Flem0527', title: 'Knocking on Wood Door (1)', url: 'https://freesound.org/people/Flem0527/sounds/629987/', licence: 'CC0 1.0' },
  bong: { id: 402382, by: 'freemaster2', title: 'Bells Bong', url: 'https://freesound.org/people/freemaster2/sounds/402382/', licence: 'CC0 1.0' },
  chair: { id: 175410, by: 'Housed1J', title: 'Moaning Chair.aif', url: 'https://freesound.org/people/Housed1J/sounds/175410/', licence: 'CC0 1.0' },
  creak: { id: 390323, by: 'Lightnessko', title: 'Creaking', url: 'https://freesound.org/people/Lightnessko/sounds/390323/', licence: 'CC0 1.0' },
  tick: { id: 450509, by: 'abyeditsound', title: 'ClockTickSound_01.wav', url: 'https://freesound.org/people/abyeditsound/sounds/450509/', licence: 'CC0 1.0' },
  mud: { id: 445109, by: 'Breviceps', title: 'Mud Splat', url: 'https://freesound.org/people/Breviceps/sounds/445109/', licence: 'CC0 1.0' },
  wheel: { id: 262251, by: 'vasifer', title: 'ceramics_wheel.wav', url: 'https://freesound.org/people/vasifer/sounds/262251/', licence: 'CC0 1.0' },
  squeeze: { id: 845258, by: 'nazwhale', title: 'Lemon Squeeze', url: 'https://freesound.org/people/nazwhale/sounds/845258/', licence: 'CC0 1.0' },
  oven: { id: 234735, by: 'FenrirFangs', title: 'oven door 1.wav', url: 'https://freesound.org/people/FenrirFangs/sounds/234735/', licence: 'CC0 1.0' },
  cashbox: { id: 186408, by: 'nauix26', title: 'cash_box.wav', url: 'https://freesound.org/people/nauix26/sounds/186408/', licence: 'CC0 1.0' },
  umbrella: { id: 235494, by: 'ekfink', title: 'umbrella_open.wav', url: 'https://freesound.org/people/ekfink/sounds/235494/', licence: 'CC0 1.0' },
  van: { id: 365219, by: 'Mochni', title: 'Drive by Van', url: 'https://freesound.org/people/Mochni/sounds/365219/', licence: 'CC0 1.0' },
  slidedoor: { id: 819037, by: 'Sadiquecat', title: 'Ford 115 T350 - Side door sliding shut (from interrior)', url: 'https://freesound.org/people/Sadiquecat/sounds/819037/', licence: 'CC0 1.0' },
  hen: { id: 316920, by: 'Rudmer_Rotteveel', title: 'Chicken Single Alarm Call', url: 'https://freesound.org/people/Rudmer_Rotteveel/sounds/316920/', licence: 'CC0 1.0' },
  ball: { id: 765650, by: 'ChrisGrundlingh', title: 'Dropping ball', url: 'https://freesound.org/people/ChrisGrundlingh/sounds/765650/', licence: 'CC0 1.0' },
  bounce: { id: 788264, by: 'amsaenz03', title: 'Sports Tennis Ball Bouncing', url: 'https://freesound.org/people/amsaenz03/sounds/788264/', licence: 'CC0 1.0' },
  throw: { id: 389441, by: 'RossBell', title: 'Paper Throw Into Air; 3.wav', url: 'https://freesound.org/people/RossBell/sounds/389441/', licence: 'CC0 1.0' },
  tape: { id: 565501, by: 'NinjaSharkStudios', title: 'Tape Measure_1.wav', url: 'https://freesound.org/people/NinjaSharkStudios/sounds/565501/', licence: 'CC0 1.0' },
  swing: { id: 693795, by: 'PospecStudio', title: 'woden swing.mp3', url: 'https://freesound.org/people/PospecStudio/sounds/693795/', licence: 'CC0 1.0' },
  crack: { id: 183453, by: 'utsuru', title: 'Wood Crack 1', url: 'https://freesound.org/people/utsuru/sounds/183453/', licence: 'CC0 1.0' },
  churchbell: { id: 76405, by: 'dsp9000', title: 'Old Church Bell.wav', url: 'https://freesound.org/people/dsp9000/sounds/76405/', licence: 'CC0 1.0' },
  whistle: { id: 20065, by: 'euroblues', title: 'Trainwhistle SBB Re 420 euroblues.wav', url: 'https://freesound.org/people/euroblues/sounds/20065/', licence: 'CC0 1.0' },
  pencil: { id: 257518, by: 'waldram', title: 'Scribble_short.wav', url: 'https://freesound.org/people/waldram/sounds/257518/', licence: 'CC0 1.0' },
  clap: { id: 151219, by: 'OwlStorm', title: 'Solo Clap', url: 'https://freesound.org/people/OwlStorm/sounds/151219/', licence: 'CC0 1.0' },
  blanket: { id: 320144, by: 'OwlStorm', title: 'Blanket Movement 6', url: 'https://freesound.org/people/OwlStorm/sounds/320144/', licence: 'CC0 1.0' },
  splash: { id: 321490, by: 'dslrguide', title: 'Tiny Splash', url: 'https://freesound.org/people/dslrguide/sounds/321490/', licence: 'CC0 1.0' },
  plate: { id: 257939, by: 'Kane53126', title: 'Set Plate Down.wav', url: 'https://freesound.org/people/Kane53126/sounds/257939/', licence: 'CC0 1.0' },
  can: { id: 406558, by: 'Anthousai', title: 'hit - metallic - watering can - flicking a metal watering can 01.wav', url: 'https://freesound.org/people/Anthousai/sounds/406558/', licence: 'CC0 1.0' },
  bucket: { id: 175948, by: 'freefire66', title: 'Bucket Hit.wav', url: 'https://freesound.org/people/freefire66/sounds/175948/', licence: 'CC0 1.0' },
  trolley: { id: 209978, by: 'Soundscape_Leuphana', title: '20131204_Getting a Shopping cart_ZoomH2nXY.wav', url: 'https://freesound.org/people/Soundscape_Leuphana/sounds/209978/', licence: 'CC0 1.0' },
  cafe: { id: 380201, by: 'lunchmoney', title: 'Cafe Ambience Day - 2 - Sound Devices 702 - Senn K6.WAV', url: 'https://freesound.org/people/lunchmoney/sounds/380201/', licence: 'CC0 1.0' },
  room: { id: 135097, by: 'mzui', title: 'Room Tone Office Quiet Distant Traffic.wav', url: 'https://freesound.org/people/mzui/sounds/135097/', licence: 'CC0 1.0' },
  attic: { id: 329569, by: 'leonelmail', title: 'Roomtone Bedroom Yew', url: 'https://freesound.org/people/leonelmail/sounds/329569/', licence: 'CC0 1.0' },
  museum: { id: 219461, by: 'cediez', title: 'musee.Victoria.Londres_hall.entree.wav', url: 'https://freesound.org/people/cediez/sounds/219461/', licence: 'CC0 1.0' },
  street: { id: 451734, by: 'florianreichelt', title: 'Shopping Street Ambience', url: 'https://freesound.org/people/florianreichelt/sounds/451734/', licence: 'CC0 1.0' },
  station: { id: 404479, by: 'Trainscough5407', title: 'Train Station.wav', url: 'https://freesound.org/people/Trainscough5407/sounds/404479/', licence: 'CC0 1.0' },
  supermarket: { id: 370969, by: 'waweee', title: 'supermarket ambience', url: 'https://freesound.org/people/waweee/sounds/370969/', licence: 'CC0 1.0' },
  garden: { id: 153551, by: 'sphion', title: 'garden_city_ambience.wav', url: 'https://freesound.org/people/sphion/sounds/153551/', licence: 'CC0 1.0' },
  park: { id: 469613, by: 'brunoboselli', title: 'Kids Playing', url: 'https://freesound.org/people/brunoboselli/sounds/469613/', licence: 'CC0 1.0' },
  market: { id: 433612, by: 'drewhalasz', title: 'amb, ext, outdoor market, chatter, footsteps, bformat-fuma.WAV', url: 'https://freesound.org/people/drewhalasz/sounds/433612/', licence: 'CC0 1.0' },
  rain: { id: 380651, by: 'BonnyOrbit', title: 'Light rain on street.wav', url: 'https://freesound.org/people/BonnyOrbit/sounds/380651/', licence: 'CC0 1.0' },
  beach: { id: 518637, by: 'jackmichaelking', title: 'Gentle ocean waves birdsong and gull.WAV', url: 'https://freesound.org/people/jackmichaelking/sounds/518637/', licence: 'CC0 1.0' },
  river: { id: 517419, by: 'Antonio_Lai', title: 'River', url: 'https://freesound.org/people/Antonio_Lai/sounds/517419/', licence: 'CC0 1.0' },
  square: { id: 119934, by: 'ftpalad', title: 'Town Square Ambience.aif', url: 'https://freesound.org/people/ftpalad/sounds/119934/', licence: 'CC0 1.0' },
  kitchen: { id: 473718, by: 'Joao_Janz', title: 'Kitchen Ambience At Night .wav', url: 'https://freesound.org/people/Joao_Janz/sounds/473718/', licence: 'CC0 1.0' },
};

/**
 * What the app plays, cut from the sources. `loud` is the integrated loudness each is
 * set to (EBU R128, LUFS): a reaction sits a little under the voices' level, a bed far
 * under it, so the player's own gains start from one common scale.
 */
export const CUTS = [
  { id: 'court', src: 'crowd', from: 4, len: 40, loop: 2.5, loud: -24, bed: true },
  { id: 'muffled', src: 'crowd', from: 4, len: 40, loop: 2.5, loud: -30, bed: true, filter: 'lowpass=f=420,lowpass=f=420' },
  { id: 'laugh', src: 'laugh', from: 0, len: 5.3, fadeOut: 0.8, loud: -20, onset: true },
  { id: 'murmur', src: 'murmur', from: 0, len: 5.6, fadeOut: 1.0, loud: -22, onset: true },
  { id: 'gasp', src: 'gasp', from: 0, len: 3.8, fadeOut: 0.8, loud: -20, onset: true },
  { id: 'cheer', src: 'cheer', from: 0, len: 7.5, fadeOut: 2.0, loud: -20, onset: true },
  { id: 'door', src: 'door', from: 0, len: 2.9, fadeOut: 0.7, loud: -22, onset: true },
  { id: 'steps', src: 'steps', from: 1.0, len: 2.6, fadeIn: 0.05, fadeOut: 0.5, loud: -26, onset: true },
  { id: 'pour', src: 'pour', from: 0, len: 8.3, fadeOut: 1.5, loud: -26, onset: true },
  { id: 'drip', src: 'drip', from: 0, len: 1.7, fadeOut: 0.3, loud: -26, onset: true },
  { id: 'discs', src: 'discs', from: 0, len: 4.0, fadeOut: 0.6, loud: -22, onset: true },
  // AT8: the small sounds of hands at work (`foley`, which may sound quietly under a line,
  // cut from their first hit, `onset`), the answer's seal, two sounds for a beat with no
  // line, and a bed for every lesson's place
  { id: 'chalk', src: 'chalk', from: 0, len: 1.6, fadeOut: 0.4, loud: -28, foley: true, onset: true },
  { id: 'chalktap', src: 'chalktap', from: 0, len: 0.3, fadeOut: 0.1, loud: -29, foley: true, onset: true },
  { id: 'coinflip', src: 'coinflip', from: 0, len: 1.5, fadeOut: 0.3, loud: -28, foley: true, onset: true },
  { id: 'coin', src: 'discs', from: 0, len: 0.7, fadeOut: 0.25, loud: -28, foley: true, onset: true, onsetDb: 3 },
  { id: 'paper', src: 'paper', from: 0, len: 1.2, fadeOut: 0.4, loud: -29, foley: true, onset: true, onsetDb: 10 },
  { id: 'tear', src: 'tear', from: 0, len: 1.2, fadeOut: 0.3, loud: -28, foley: true, onset: true, onsetDb: 10 },
  { id: 'pin', src: 'pin', from: 0, len: 0.5, fadeOut: 0.15, loud: -28, foley: true, onset: true, onsetDb: 8 },
  { id: 'stamp', src: 'stamp', from: 0, len: 0.9, fadeOut: 0.3, loud: -27, foley: true, onset: true },
  { id: 'book', src: 'book', from: 0, len: 1.2, fadeOut: 0.4, loud: -28, foley: true, onset: true },
  { id: 'cup', src: 'cup', from: 0, len: 0.7, fadeOut: 0.2, loud: -28, foley: true, onset: true },
  { id: 'mug', src: 'mug', from: 0, len: 0.8, fadeOut: 0.2, loud: -28, foley: true, onset: true },
  { id: 'stir', src: 'stir', from: 0, len: 2.0, fadeOut: 0.5, loud: -29, foley: true, onset: true },
  { id: 'pourcup', src: 'coffee', from: 0, len: 2.2, fadeOut: 0.6, loud: -29, foley: true, onset: true, onsetDb: 6 },
  { id: 'water', src: 'pour', from: 0, len: 2.4, fadeOut: 0.6, loud: -29, foley: true, onset: true },
  { id: 'freewheel', src: 'freewheel', from: 0, len: 1.8, fadeOut: 0.5, loud: -29, foley: true, onset: true },
  { id: 'crate', src: 'wooddrop', from: 0, search: 1.0, len: 0.38, fadeOut: 0.1, loud: -28, foley: true, onset: true },
  { id: 'plank', src: 'planks', from: 0, len: 1.2, fadeOut: 0.3, loud: -28, foley: true, onset: true },
  { id: 'cardflip', src: 'cardflip', from: 0, len: 0.8, fadeOut: 0.2, loud: -28, foley: true, onset: true, onsetDb: 10 },
  { id: 'jarlid', src: 'tealid', from: 0, len: 1.2, fadeOut: 0.4, loud: -28, foley: true, onset: true },
  { id: 'jar', src: 'jar', from: 0, len: 1.0, fadeOut: 0.3, loud: -28, foley: true, onset: true },
  { id: 'jarbreak', src: 'jarbreak', from: 0, len: 1.8, fadeOut: 0.5, loud: -27, foley: true, onset: true },
  { id: 'glass', src: 'shards', from: 1.6, len: 1.0, fadeIn: 0.03, fadeOut: 0.4, loud: -31, foley: true },
  { id: 'knock', src: 'knock', from: 0, len: 0.17, fadeOut: 0.05, loud: -27, foley: true, onset: true, onsetDb: 6 },
  { id: 'clockchime', src: 'bong', from: 0, len: 2.5, fadeOut: 0.8, loud: -29, foley: true, onset: true },
  { id: 'chair', src: 'chair', from: 0, len: 1.2, fadeOut: 0.3, loud: -29, foley: true, onset: true },
  { id: 'creak', src: 'creak', from: 0, len: 1.0, fadeOut: 0.3, loud: -29, foley: true, onset: true },
  { id: 'stopwatch', src: 'tick', from: 0, len: 0.15, fadeOut: 0.05, loud: -28, foley: true, onset: true },
  { id: 'clay', src: 'mud', from: 0, len: 0.5, fadeOut: 0.15, loud: -29, foley: true, onset: true },
  { id: 'squeeze', src: 'squeeze', from: 0, len: 1.8, fadeOut: 0.4, loud: -28, foley: true, onset: true },
  { id: 'oven', src: 'oven', from: 0, len: 1.5, fadeOut: 0.4, loud: -28, foley: true, onset: true, onsetDb: 10 },
  { id: 'cashbox', src: 'cashbox', from: 0, search: 1.2, len: 0.32, fadeOut: 0.1, loud: -28, foley: true, onset: true, onsetDb: 10 },
  { id: 'umbrella', src: 'umbrella', from: 0, len: 1.5, fadeOut: 0.3, loud: -28, foley: true, onset: true, onsetDb: 10 },
  { id: 'slidedoor', src: 'slidedoor', from: 0, len: 2.0, fadeOut: 0.4, loud: -28, foley: true, onset: true, onsetDb: 6 },
  { id: 'hen', src: 'hen', from: 0, len: 1.2, fadeOut: 0.3, loud: -28, foley: true, onset: true, onsetDb: 8 },
  { id: 'thud', src: 'ball', from: 0, len: 0.8, fadeOut: 0.3, loud: -27, foley: true, onset: true },
  { id: 'bounce', src: 'bounce', from: 0, len: 1.0, fadeOut: 0.3, loud: -29, foley: true, onset: true },
  { id: 'plane', src: 'throw', from: 0, len: 0.8, fadeOut: 0.2, loud: -29, foley: true, onset: true, onsetDb: 10 },
  { id: 'tape', src: 'tape', from: 0, len: 1.5, fadeOut: 0.3, loud: -28, foley: true, onset: true },
  { id: 'swing', src: 'swing', from: 0, len: 2.0, fadeOut: 0.5, loud: -29, foley: true, onset: true },
  { id: 'crack', src: 'crack', from: 0, len: 1.0, fadeOut: 0.3, loud: -29, foley: true, onset: true },
  { id: 'pencil', src: 'pencil', from: 0, len: 1.3, fadeOut: 0.3, loud: -29, foley: true, onset: true },
  { id: 'clap', src: 'clap', from: 0, len: 0.5, fadeOut: 0.15, loud: -27, foley: true, onset: true },
  { id: 'whoosh', src: 'blanket', from: 0, len: 1.0, fadeOut: 0.3, loud: -29, foley: true, onset: true, onsetDb: 10 },
  { id: 'splash', src: 'splash', from: 0, len: 1.0, fadeOut: 0.3, loud: -28, foley: true, onset: true },
  { id: 'plate', src: 'plate', from: 0, search: 1.0, len: 0.5, fadeOut: 0.15, loud: -28, foley: true, onset: true },
  { id: 'can', src: 'can', from: 0, len: 0.7, fadeOut: 0.2, loud: -28, foley: true, onset: true },
  { id: 'bucket', src: 'bucket', from: 0, len: 1.0, fadeOut: 0.3, loud: -28, foley: true, onset: true },
  { id: 'trolley', src: 'trolley', from: 1.7, len: 0.6, fadeOut: 0.3, loud: -27, foley: true, onset: true, onsetDb: 6 },
  { id: 'shed', src: 'door', from: 0, len: 2.2, fadeOut: 0.5, loud: -29, foley: true, onset: true, onsetDb: 6 },
  { id: 'drop', src: 'drip', from: 0, len: 0.6, fadeOut: 0.2, loud: -28, foley: true, onset: true },
  { id: 'wheel', src: 'wheel', from: 1.0, len: 2.2, fadeIn: 0.15, fadeOut: 0.6, loud: -29, foley: true },
  { id: 'van', src: 'van', from: 0, search: 3.0, len: 3.0, fadeOut: 1.0, loud: -28, foley: true, onset: true, onsetDb: 10 },
  { id: 'seal', src: 'stamp', from: 0, len: 0.9, fadeOut: 0.3, loud: -24, onset: true },
  { id: 'bell', src: 'churchbell', from: 0, len: 4.4, fadeOut: 1.2, loud: -24, onset: true },
  { id: 'train', src: 'whistle', from: 0, len: 4.0, fadeOut: 1.0, loud: -30, onset: true, filter: 'lowpass=f=2500' },
  { id: 'cafe', src: 'cafe', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'room', src: 'room', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'attic', src: 'attic', from: 0.5, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'museum', src: 'museum', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'street', src: 'street', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'station', src: 'station', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'supermarket', src: 'supermarket', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'garden', src: 'garden', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'park', src: 'park', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'market', src: 'market', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'rain', src: 'rain', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'beach', src: 'beach', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'river', src: 'river', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'square', src: 'square', from: 2, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
  { id: 'kitchen', src: 'kitchen', from: 0.5, len: 30, loop: 2.5, loud: -32, bed: true, kbps: 96 },
];

