import type { BaseBeat } from './cinematicKit';

// Cinematic aesthetics-aesthetics-11, "Can a Machine Make Art?"
//
// THE PICTURE: two framed canvases hung side by side and drawn from the same style
// object, so they are identical by construction rather than by claim. Over the
// lesson everything that CAN change changes — the plaques underneath, the tag
// across them, the answer cards — and the two pictures never differ by a mark. The
// argument is that the only thing the stage can find to differentiate is the label.
//
// Q1 is answered on the wall (tap what actually differs). Q2 is A/B/C/D, because
// "what could the maker be adding" is the one that needs weighing (E34).

export interface Aes11Beat extends BaseBeat {
  /** Figure gesture (emote code). */ p?: number;
  /** Where the figure stands (stage x). 70 = downstage left, 168 = at the wall. */ x?: number;
  /** Both canvases are hung, 0..1. */ frames?: number;
  /** The two plaques are lettered, 0..1. */ plaques?: number;
  /** 1 = the IDENTICAL tag is drawn across both frames. */ same?: number;
  /** 1 = the three answer cards are live (Q1). */ pick?: number;
}

export const BEATS: Aes11Beat[] = [
  {
    p: 462, x: 70,
    text: 'Suppose a gallery hangs two pictures. One was painted by a person over four months.',
    dur: 2.7,
  },
  {
    p: 462, x: 70,
    text: 'The other was generated by a machine in about nine seconds.',
    dur: 1.8,
  },
  {
    p: 41, x: 168, frames: 1,
    text: 'The two pictures aren’t merely similar but identical.',
    cite: 'Both canvases',
    dur: 1.8,
  },
  {
    p: 41, x: 168, frames: 1,
    text: 'Every mark is in the same place, at the same size, in the same colour.',
    dur: 3.2,
  },
  {
    p: 396, x: 124, frames: 1, plaques: 1,
    text: 'Only the plaques tell the two apart. With the plaques covered, no visitor, curator or critic could reliably sort them.',
    cite: 'The plaques',
    dur: 4.4,
  },
  {
    p: 139, x: 124, frames: 1, plaques: 1,
    quote: {
      id: 'lq-aesthetics-aesthetics-11-1',
      text: 'Art is a human activity having for its purpose the transmission to others of the highest and best feelings to which men have risen.',
      author: 'Leo Tolstoy',
      work: 'What Is Art?',
      era: '1897',
      branchSlugs: ['aesthetics'],
    },
    dur: 3.8,
  },
  {
    p: 389, x: 168, frames: 1, plaques: 1, same: 1,
    text: 'So every visible property is shared. What sets the two apart lies not in the objects but in how each was made.',
    cite: 'The history of making',
    dur: 4.8,
  },
  {
    p: 383, x: 124, frames: 1, plaques: 1, same: 1, pick: 1,
    interact: {
      prompt: 'If the canvases match exactly, what differs between the two works?',
      explain: 'Who made it. By hypothesis, the brushwork and the colours are identical, so no visible feature differs. If one brushstroke differed, the puzzle would disappear. What differs is the history behind the paint.',
      xp: 5,
    },
    dur: 1.0,
  },
  {
    p: 165, x: 124, frames: 1, plaques: 1, same: 1,
    interact: {
      prompt: 'What could a human maker add that the surface doesn’t show?',
      sort: {
        chip: 'the human maker',
        bins: [
          { id: 'nothing', label: 'nothing', reads: 'nothing, the surfaces are identical' },
          { id: 'toil', label: 'hours spent', reads: 'the hours of labour it took' },
          { id: 'feeling', label: 'a feeling', reads: 'a feeling the maker had and passed on', correct: true },
        ],
      },
      explain: 'A feeling the maker had and passed on. For Tolstoy, art transmits a feeling from the artist to the audience. On that view, only a maker who had the feeling can pass it on. Formalists reply that only the surface matters.',
      xp: 5,
    },
    dur: 1.0,
  },
  {
    summary: {
      title: 'Art and Its Maker',
      points: [
        'Identical surfaces can still differ in what they are',
        'The difference lies in how each was made',
        'Expression needs someone doing the expressing',
        'Formalists deny that anything beyond the surface matters',
      ],
      closing: 'The question isn’t whether a machine can produce an image. It’s whether art requires a maker who expresses something.',
    },
    dur: 3.0,
  },
];
