// GENERATED by `npm run make:lesson-art` from scripts/lib/lessonart/. Do not edit:
// change the drawing and run it again. check:lesson-art fails a stale stamp.
import type { ImageSourcePropType } from 'react-native';

/** A lesson's detailed art, pre-drawn: where it sits on the stage (scene units) and its picture. */
export const LESSON_ART: Record<string, { source: ImageSourcePropType; x: number; y: number; w: number; h: number; stamp: string }> = {
  'hist6-carving': { source: require('@/assets/lesson-art/hist6-carving.png'), x: 24, y: 272, w: 280, h: 146, stamp: '322406a03d1c' },
  'hist6-king-gold': { source: require('@/assets/lesson-art/hist6-king-gold.png'), x: 60, y: 272, w: 104, h: 100, stamp: 'e8c829228b97' },
  'phil6-horse': { source: require('@/assets/lesson-art/phil6-horse.png'), x: -17, y: -15, w: 34, h: 30, stamp: '9d4c835c12d4' },
  'sci6-hammock-full': { source: require('@/assets/lesson-art/sci6-hammock-full.png'), x: -23, y: 0, w: 46, h: 62, stamp: '58f21ac9c3fd' },
  'sci6-hammock-empty': { source: require('@/assets/lesson-art/sci6-hammock-empty.png'), x: -23, y: 0, w: 46, h: 62, stamp: '8662b08a2c26' },
  'econ6-wreck': { source: require('@/assets/lesson-art/econ6-wreck.png'), x: -4, y: 337, w: 120, h: 70, stamp: '203effafa02f' },
  'econ6-ship': { source: require('@/assets/lesson-art/econ6-ship.png'), x: -20, y: -17, w: 40, h: 34, stamp: 'f549317f3388' },
  'growth6-boat': { source: require('@/assets/lesson-art/growth6-boat.png'), x: -28, y: -26.5, w: 56, h: 31, stamp: '0fe2d3548c43' },
  'econ5-rat-a': { source: require('@/assets/lesson-art/econ5-rat-a.png'), x: -15, y: -9.93, w: 30, h: 10.26, stamp: 'bf2064aa23f0' },
  'econ5-rat-b': { source: require('@/assets/lesson-art/econ5-rat-b.png'), x: -15, y: -9.93, w: 30, h: 10.26, stamp: '88c0dd9898da' },
  'econ5-rat-peek': { source: require('@/assets/lesson-art/econ5-rat-peek.png'), x: -8.5, y: -13.9, w: 17, h: 13.81, stamp: 'aa8fcc168120' },
};
