// GENERATED by `npm run make:plates`. Do not edit.
// The baked picture of each set plate (plates.ts); `check:plates` holds the stamps.

export const PLATE_STAMP: Record<string, string> = {
  'hist5-far': '6693fb0edf0dc2d1',
  'hist5-floor': '24d95bc3e42d1c57',
  'hist5-mid': 'f29bc42877ac28d7',
  'hist5-room': '26789e5a6946a69b',
};

export const PLATE_ART: Record<string, number> = {
  'hist5-far': require('../../../assets/images/sets/hist5-far.png'),
  'hist5-floor': require('../../../assets/images/sets/hist5-floor.png'),
  'hist5-mid': require('../../../assets/images/sets/hist5-mid.png'),
  'hist5-room': require('../../../assets/images/sets/hist5-room.png'),
};
