// GENERATED by scripts/make-tours.mjs — do not hand-edit.
//
// Group K — the tour. Per beat, the stations the camera visits: a box in scene
// coordinates, the seconds to travel there, and the seconds to sit once arrived.
// `null` is a beat that keeps one shot, which is every graded beat, every drag beat,
// every summary (K6), and every beat whose contents do not separate into subjects
// worth their own framing (K4).
//
// The last station of every tour is the beat's whole must-box (K3), so a beat's
// resting frame is exactly what it was before this table existed — the tour is new
// motion added ahead of an unchanged final framing. Empty this file and every lesson
// is byte-for-byte its old self.
//
// Scene time does not advance while the camera travels between stations (K1), so the
// order here is the order the reader experiences the beat in. It is the measured
// reveal order, not reading order — see scripts/lib/tourrule.mjs.
//
// TOUR_STAMP fingerprints the scene and script each tour was derived from, exactly as
// MUST_STAMP does, because a stale tour fails the same silent way: it parks the camera
// where something used to be.

// Six numbers is a station the camera parks at. TEN is a FOLLOW (K9): the last four
// are where the subject has walked to by the end of the dwell, and the camera tracks
// it there at a fixed scale instead of watching it cross a still frame.
export type TourStation =
  | readonly [x: number, y: number, w: number, h: number, tr: number, dwell: number]
  | readonly [x: number, y: number, w: number, h: number, tr: number, dwell: number,
      tx: number, ty: number, tw: number, th: number];

export const TOURS: Record<string, readonly (readonly TourStation[] | null)[]> = {
  'business-foundations-1': [[[219, 417, 97, 88, 1.2, 9]], null, null, null, null, null, [[180, 406, 140, 99, 1.2, 9]], null, null, null, null, null],
  'business-foundations-2': [null, null, null, null, null, [[40, 406, 256, 99, 1.08, 9]], [[40, 406, 178, 99, 0.67, 9]], null, null, [[38, 406, 219, 99, 1.2, 9]], [[34, 406, 180, 99, 0.55, 9]]],
  'business-foundations-3': [null, null, null, null, null, [[67, 406, 267, 99, 1.03, 9]], null, null, [[76, 407, 255, 98, 0.61, 9]], null, [[65, 406, 270, 99, 1.02, 9]], [[72, 406, 258, 99, 0.6, 9]]],
  'business-foundations-4': [null, null, [[12, 405, 258, 100, 0.67, 9]], [[65, 406, 208, 99, 0.67, 9]], null, null, null, null, null, null, null],
  'business-foundations-6': [[[40, 282, 295, 223, 0.74, 9]], [[21, 278, 315, 227, 0.57, 9]], null, [[35, 280, 302, 225, 0.56, 9]], null, [[14, 278, 331, 227, 0.72, 9]], null, null, [[0, 252, 400, 262, 0.75, 9]], null, null, null],
  'economics-foundations-1': [[[67, 416, 259, 89, 1.07, 9]], null, [[15, 405, 304, 100, 0.87, 9]], [[0, 306, 400, 208, 0.88, 9]], [[22, 406, 273, 99, 1.01, 9]], null, [[25, 407, 239, 98, 1.17, 9]], [[0, 306, 400, 208, 1.17, 9]], null, null],
  'economics-foundations-4': [null, [[93, 417, 135, 88, 0.73, 9]], [[93, 407, 296, 98, 0.84, 9]], null, null, [[80, 406, 317, 99, 0.83, 9]], [[141, 406, 249, 99, 0.84, 9]], null, null, null, null],
  'economics-foundations-6': [null, null, [[0, 250, 400, 274, 0.71, 9]], null, null, null, null, null, null, null, null],
  'history-foundations-1': [null, null, [[0, 306, 400, 208, 1.2, 9]], null, null, null, null, null, null, null, null],
  'history-foundations-2': [null, null, [[0, 405, 284, 100, 0.79, 9]], null, null, null, [[92, 406, 218, 99, 0.55, 9]], null, null, [[93, 406, 193, 99, 0.55, 9]], null],
  'history-foundations-3': [null, [[44, 416, 293, 89, 0.92, 9]], null, null, null, [[12, 405, 319, 100, 0.82, 9]], [[9, 405, 331, 113, 0.59, 9]], null, null, null, null, [[36, 406, 332, 99, 0.77, 9]]],
  'history-foundations-4': [null, null, [[14, 405, 294, 100, 0.83, 9]], null, null, null, null, null, null, null, [[64, 330, 310, 175, 0.79, 9]]],
  'history-foundations-6': [null, null, null, null, null, null, null, null, null, null, [[7, 300, 338, 205, 0.75, 9]], [[10, 299, 311, 206, 0.63, 9]]],
  'personal-growth-foundations-1': [null, null, null, null, null, null, null, null, null, null, [[43, 406, 246, 99, 1.13, 9]], null],
  'personal-growth-foundations-2': [null, null, null, null, null, null, null, null, null, null, [[0, 362, 265, 143, 1, 9]], [[0, 306, 400, 208, 1, 9]]],
  'personal-growth-foundations-3': [[[16, 419, 266, 86, 1.04, 9]], null, [[16, 405, 293, 100, 0.83, 9]], [[16, 406, 273, 99, 0.63, 9]], null, null, null, null, null, null, null, null],
  'personal-growth-foundations-4': [[[156, 416, 95, 89, 1.2, 9]], null, null, [[0, 406, 252, 99, 0.65, 9]], null, [[82, 406, 225, 99, 1.2, 9]], null, null, null, null, null, null],
  'philosophy-foundations-1': [[[15, 416, 287, 89, 0.95, 9]], null, null, [[42, 407, 257, 98, 0.85, 9]], null, null, null, null, null, null, null, null],
  'philosophy-foundations-2': [[[187, 420, 160, 85, 1.2, 9]], null, [[12, 406, 310, 99, 0.89, 9]], null, null, null, null, null, null, null, null],
  'psychology-foundations-1': [[[31, 420, 257, 85, 1.08, 9]], [[148, 420, 152, 85, 0.67, 9]], [[160, 421, 212, 84, 0.55, 9]], null, [[0, 306, 400, 208, 1.2, 9]], null, null, null, null, null, null, null],
  'psychology-foundations-2': [[[107, 416, 188, 89, 1.2, 9]], [[106, 417, 136, 96, 0.55, 9]], null, [[0, 306, 400, 208, 1.2, 9]], null, null, null, [[22, 406, 264, 99, 0.83, 9]], null, null, null, [[34, 407, 255, 98, 0.88, 9]]],
  'psychology-foundations-3': [null, null, null, null, null, null, null, null, null, null, [[54, 406, 247, 99, 1.13, 9]], null],
  'psychology-foundations-5': [null, null, null, null, null, null, null, null, null, null, null, [[0, 300, 400, 214, 0.79, 9]]],
  'psychology-foundations-6': [[[15, 320, 253, 185, 0.87, 9]], null, null, null, [[19, 321, 286, 184, 0.88, 9]], null, null, null, null, null, null],
  'science-foundations-1': [null, null, null, null, null, null, null, null, null, null, [[230, 406, 133, 99, 0.72, 9]]],
  'science-foundations-2': [null, [[0, 306, 400, 210, 1.16, 9]], [[9, 388, 203, 117, 1.2, 9]], [[0, 306, 400, 210, 1.2, 9]], null, null, null, null, null, null, null, null],
  'science-foundations-5': [[[119, 373, 227, 123, 1.2, 9]], null, [[116, 374, 159, 122, 0.55, 9]], null, null, null, null, null, null, null, null, null],
};

export const TOUR_STAMP: Record<string, string> = {
  'business-foundations-1': 'fd06157a59d5',
  'business-foundations-2': '53336dde5ee3',
  'business-foundations-3': 'd36bac376e11',
  'business-foundations-4': 'ffffae53d3f9',
  'business-foundations-6': '50989b100c4c',
  'economics-foundations-1': 'd7f34f5cdad9',
  'economics-foundations-4': '6734156dbf83',
  'economics-foundations-6': 'fde884168af3',
  'history-foundations-1': 'ce1f84921b35',
  'history-foundations-2': '9d6abacb2af7',
  'history-foundations-3': '9f7208948fd9',
  'history-foundations-4': '8bb70a0024a1',
  'history-foundations-6': '0b6fc8a51f04',
  'personal-growth-foundations-1': 'dee84286185a',
  'personal-growth-foundations-2': '73f92fc9c1de',
  'personal-growth-foundations-3': '698dd7100bce',
  'personal-growth-foundations-4': '8f945fd5a9ad',
  'philosophy-foundations-1': 'f5f56d190e5f',
  'philosophy-foundations-2': '19e5f74cab49',
  'psychology-foundations-1': 'f57c256f1344',
  'psychology-foundations-2': 'b0261c9ecb5e',
  'psychology-foundations-3': 'c0bac5f6df5e',
  'psychology-foundations-5': 'f346d1aa8a9c',
  'psychology-foundations-6': '23aea00f4ee0',
  'science-foundations-1': 'f58d9a5b8ba1',
  'science-foundations-2': 'c4232e914411',
  'science-foundations-5': '7463bec88372',
};
