// GENERATED by scripts/make-tours.mjs — do not hand-edit.
//
// Group K — the tour. Per beat, the stations the camera visits: a box in scene
// coordinates, the seconds to travel there, and the seconds to sit once arrived.
// `null` is a beat that keeps one shot, which is every graded beat, every drag beat,
// every summary (K6), and every beat whose contents do not separate into subjects
// worth their own framing (K4).
//
// The last station of every tour is the beat's whole must-box (K3), so a beat's
// resting frame is exactly what it was before this table existed — the tour is new
// motion added ahead of an unchanged final framing. Empty this file and every lesson
// is byte-for-byte its old self.
//
// Scene time does not advance while the camera travels between stations (K1), so the
// order here is the order the reader experiences the beat in. It is the measured
// reveal order, not reading order — see scripts/lib/tourrule.mjs.
//
// TOUR_STAMP fingerprints the scene and script each tour was derived from, exactly as
// MUST_STAMP does, because a stale tour fails the same silent way: it parks the camera
// where something used to be.

// Six numbers is a station the camera parks at. TEN is a FOLLOW (K9): the last four
// are where the subject has walked to by the end of the dwell, and the camera tracks
// it there at a fixed scale instead of watching it cross a still frame.
export type TourStation =
  | readonly [x: number, y: number, w: number, h: number, tr: number, dwell: number]
  | readonly [x: number, y: number, w: number, h: number, tr: number, dwell: number,
      tx: number, ty: number, tw: number, th: number];

export const TOURS: Record<string, readonly (readonly TourStation[] | null)[]> = {
  'business-foundations-1': [[[218, 417, 98, 88, 1.2, 9]], null, [[220, 417, 129, 88, 0.55, 9]], [[0, 404, 318, 101, 0.93, 9]], [[178, 406, 139, 99, 0.93, 9]], null, null, null, null, null, null, null],
  'business-foundations-2': [null, null, null, null, null, null, null, null, null, null, [[41, 406, 170, 99, 0.57, 9]]],
  'business-foundations-3': [[[238, 417, 95, 88, 1.2, 9]], null, null, null, null, [[67, 406, 267, 99, 1.03, 9]], null, null, [[76, 407, 255, 98, 0.61, 9]], null, [[65, 406, 270, 99, 1.02, 9]], null],
  'business-foundations-4': [null, null, [[12, 405, 259, 100, 0.68, 9]], [[65, 407, 210, 98, 0.68, 9]], null, null, null, null, null, null, null],
  'business-foundations-5': [null, [[0, 222, 400, 292, 0.79, 9]], null, null, null, null, null, null, null, null, null, null],
  'business-foundations-6': [null, null, null, null, null, null, [[24, 292, 314, 213, 0.61, 9]], [[15, 284, 328, 221, 0.59, 9]], [[0, 252, 400, 262, 0.75, 9]], null, null, null],
  'economics-foundations-1': [[[71, 416, 255, 89, 1.09, 9]], null, [[0, 306, 400, 208, 1.09, 9]], null, [[22, 406, 274, 99, 1, 9]], null, null, null, null, null],
  'economics-foundations-4': [[[94, 416, 142, 89, 1.2, 9]], null, [[93, 407, 295, 98, 0.84, 9]], null, null, [[80, 406, 315, 99, 0.84, 9]], [[141, 406, 249, 99, 0.83, 9]], null, null, null, null],
  'history-foundations-1': [null, null, [[0, 306, 400, 208, 1.2, 9]], null, null, null, null, null, null, null, null],
  'history-foundations-2': [[[91, 421, 219, 84, 1.2, 9]], null, [[96, 406, 214, 99, 0.55, 9]], null, null, null, null, null, null, [[94, 406, 193, 99, 0.55, 9]], null],
  'history-foundations-3': [[[43, 417, 289, 88, 0.94, 9]], null, [[0, 404, 335, 101, 0.73, 9]], [[37, 406, 301, 99, 0.68, 9]], null, [[39, 406, 347, 108, 0.72, 9]], null, [[62, 406, 323, 99, 0.64, 9]], null, null, null, [[60, 406, 288, 99, 0.69, 9]]],
  'history-foundations-4': [null, null, null, null, null, null, null, null, null, null, [[63, 329, 311, 176, 0.78, 9]]],
  'history-foundations-6': [null, null, null, null, null, null, null, null, null, null, [[8, 299, 337, 206, 0.76, 9]], [[10, 299, 311, 206, 0.62, 9]]],
  'personal-growth-foundations-1': [null, null, null, null, null, null, null, null, null, null, [[56, 406, 234, 99, 1.19, 9]], null],
  'personal-growth-foundations-3': [[[16, 419, 267, 86, 1.03, 9]], null, [[16, 405, 296, 100, 0.84, 9]], [[16, 406, 273, 99, 0.65, 9]], null, null, null, null, null, null, null, null],
  'personal-growth-foundations-4': [[[156, 416, 98, 89, 1.2, 9]], null, null, null, null, null, null, null, null, null, null, [[84, 406, 209, 99, 1.2, 9]]],
  'philosophy-foundations-1': [[[109, 416, 192, 89, 1.2, 9]], null, [[118, 416, 179, 89, 0.97, 9]], [[16, 406, 287, 99, 0.8, 9]], [[39, 406, 257, 99, 0.68, 9]], null, null, null, null, null, null, null],
  'philosophy-foundations-2': [[[187, 421, 169, 84, 1.2, 9]], null, [[13, 406, 309, 99, 0.89, 9]], null, null, null, null, null, null, null, null],
  'psychology-foundations-1': [[[35, 420, 249, 85, 1.12, 9]], [[145, 419, 151, 86, 0.63, 9]], [[160, 448, 168, 52, 0.55, 9]], [[160, 421, 211, 84, 0.55, 9]], null, null, null, null, [[38, 406, 324, 99, 0.6, 9]], null, null, null],
  'psychology-foundations-2': [[[107, 416, 188, 89, 1.2, 9]], [[106, 417, 136, 96, 0.55, 9]], null, [[0, 306, 400, 208, 1.2, 9]], null, null, null, [[22, 406, 264, 99, 0.83, 9]], null, null, null, [[35, 407, 254, 98, 0.88, 9]]],
  'psychology-foundations-6': [[[15, 320, 253, 185, 0.87, 9]], null, null, null, [[17, 321, 288, 184, 0.88, 9]], null, null, null, null, null, null],
  'science-foundations-1': [null, null, null, null, null, null, null, null, null, null, [[235, 406, 125, 99, 0.73, 9]]],
  'science-foundations-2': [[[2, 370, 212, 135, 1.08, 9]], null, [[8, 404, 204, 101, 0.67, 9]], [[0, 306, 400, 210, 1.2, 9]], null, null, null, null, null, null, null, null],
  'science-foundations-3': [null, null, null, null, null, [[43, 406, 350, 99, 0.71, 9]], null, [[0, 306, 400, 208, 0.76, 9]], null, null, null, [[49, 406, 346, 99, 0.72, 9]]],
};

export const TOUR_STAMP: Record<string, string> = {
  'business-foundations-1': 'fc69cc2873cc',
  'business-foundations-2': 'fa4bc6b11be6',
  'business-foundations-3': '87c44538ea2c',
  'business-foundations-4': 'c798580a540a',
  'business-foundations-5': 'fe5244422540',
  'business-foundations-6': 'ce03ca532b5e',
  'economics-foundations-1': '832b74fbdc2c',
  'economics-foundations-4': '0f8095ebdd3c',
  'history-foundations-1': '1f9d3b92066b',
  'history-foundations-2': 'c713fe609747',
  'history-foundations-3': '182062edfb0b',
  'history-foundations-4': '85a3dfaa5f2a',
  'history-foundations-6': '1f0cab8f6752',
  'personal-growth-foundations-1': 'b715c2314d11',
  'personal-growth-foundations-3': '08f029a0e08b',
  'personal-growth-foundations-4': '79e13a09d79f',
  'philosophy-foundations-1': '64e564e005c0',
  'philosophy-foundations-2': 'd2f12b23263e',
  'psychology-foundations-1': 'c0961b1447a8',
  'psychology-foundations-2': 'ea9005c40b0f',
  'psychology-foundations-6': 'b3207d970aca',
  'science-foundations-1': '6793ea523ae8',
  'science-foundations-2': '039806b1ff57',
  'science-foundations-3': 'c2f0032e27b1',
};
