// GENERATED by scripts/make-tours.mjs — do not hand-edit.
//
// Group K — the tour. Per beat, the stations the camera visits: a box in scene
// coordinates, the seconds to travel there, and the seconds to sit once arrived.
// `null` is a beat that keeps one shot, which is every graded beat, every drag beat,
// every summary (K6), and every beat whose contents do not separate into subjects
// worth their own framing (K4).
//
// The last station of every tour is the beat's whole must-box (K3), so a beat's
// resting frame is exactly what it was before this table existed — the tour is new
// motion added ahead of an unchanged final framing. Empty this file and every lesson
// is byte-for-byte its old self.
//
// Scene time does not advance while the camera travels between stations (K1), so the
// order here is the order the reader experiences the beat in. It is the measured
// reveal order, not reading order — see scripts/lib/tourrule.mjs.
//
// TOUR_STAMP fingerprints the scene and script each tour was derived from, exactly as
// MUST_STAMP does, because a stale tour fails the same silent way: it parks the camera
// where something used to be.

export type TourStation = readonly [x: number, y: number, w: number, h: number, tr: number, dwell: number];

export const TOURS: Record<string, readonly (readonly TourStation[] | null)[]> = {
  'metaphysics-being-2': [[[30, 184, 340, 152, 0.7, 1.2], [20, 180, 375, 331, 0.7, 9]], [[30, 184, 340, 152, 0.7, 1.2], [20, 180, 375, 331, 0.7, 9]], [[30, 184, 340, 152, 0.7, 1.2], [20, 180, 375, 331, 0.7, 9]], [[30, 184, 340, 152, 0.7, 1.2], [20, 180, 375, 331, 0.7, 9]], [[30, 184, 340, 152, 0.7, 1.2], [20, 180, 375, 331, 0.7, 9]], null, null, null],
};

export const TOUR_STAMP: Record<string, string> = {
  'metaphysics-being-2': 'a688a1fb4f87',
};
