// GENERATED by scripts/make-thoughts.mjs — the placement. The WORDS are authored.
//
// What the stickman is working out, beat by beat, in a bubble over his head.
//
// ── WHY THIS IS A TABLE AND NOT A FIELD ON THE BEAT ─────────────────────────
//
// The same reason `data/lessonFocus.ts` is one, and it is nothing to do with
// design: `muststamp` hashes every lesson's SCRIPT, so writing a thought into 186
// scripts marks all 186 must-box measurements stale and demands a browser sweep
// of hours to record something the stage never draws from the script. §17 records
// the maxim making exactly that trade and being moved out for it.
//
// The cost is that a rewritten beat can orphan its own thought — J9's stale "the
// trap is B" — so `check:thoughts` re-derives every entry against the beat it
// claims to sit on, and says so when the beat has moved out from under it.
//
// ── `top` IS PER LESSON, `say` IS PER BEAT ──────────────────────────────────
//
// `top` is the stage y of the bubble's TAIL, chosen against the lesson's own BAND
// and the art the beats actually draw. It is per lesson because the band is, and
// because a bubble that moved between beats would read as a second object rather
// than as something coming out of his head.

export interface LessonThoughts {
  /**
   * Per beat: `[x, tailY, discs, headX]`, or null for the beats with nowhere to
   * put a bubble.
   *
   * `x` is the box's centre and `headX` is HIS centre — both absolute stage
   * coordinates, both measured out of `mustBoxes`. They differ when the space
   * directly overhead was taken and the box had to slide; the trail leans back
   * toward `headX` so it still says whose thought it is.
   *
   * ABSOLUTE, not an offset from his live position. The player derives that from
   * the script's `walk` track, a scene need not pass one, and where it was missing
   * the bubble fell back to the middle of the stage and landed across a plate this
   * generator had carefully avoided. `headX` is the union of his boxes across the
   * whole beat, so it already covers wherever he walks during it.
   *
   * `tailY` is the stage y of the smallest disc: the bubble hangs from its tail so
   * a one-line and a two-line thought keep the same distance from his head.
   *
   * GENERATED by `make:thoughts` against the measured art. A bubble never covers
   * a WORD (D31); it is allowed over art, and only when nothing fully clear was
   * within reach.
   */
  at: ([number, number, number, number] | null)[];
  /** One entry per beat: what he is thinking, or null for the beats he is just listening. */
  say: (string | null)[];
  /**
   * The SECOND figure's line as he walks in: `[beat, x, tailY, discs]`.
   *
   * Only the 24 lessons where a visitor arrives (AA8), and only on his entrance
   * beat — never on the question itself, because a second figure staking a claim
   * while the reader is still choosing is a hint wearing a hat (group O). What he
   * says is pooled rather than authored, and that is structural: a `poll` lists
   * named positions and a `split` divides one thing in two, so his meaning is
   * fixed by the CONTROL — he disagrees — whatever the lesson is about.
   */
  vis?: [number, number, number, number];
}

export const THOUGHTS: Record<string, LessonThoughts> = {
  'aesthetics-aesthetics-1': {
    at: [null, null, null, null, null, null, null, null, null, null, [252, 395, 1, 252], null, null, null, [138, 384, 3, 258], null],
    say: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  'epistemology-knowledge-1': {
    at: [null, null, null, null, null, null, null, null, null, null, [293, 393, 2, 293], [292, 393, 2, 292], null],
    say: [null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  'metaphysics-being-1': {
    at: [null, null, null, null, null, null, null, null, null, [325, 393, 3, 331], [324, 393, 3, 330], null],
    say: [null, null, null, null, null, null, null, null, null, null, null, null],
  },
  'ethics-ethics-1': {
    at: [null, null, null, null, null, null, null, null, null, null, null, [218, 202, 1, 218], [218, 203, 2, 218], null, null, null],
    say: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  'political-political-1': {
    at: [null, null, null, null, null, null, null, [202, 393, 3, 202], null, null, [202, 354, 1, 202], null],
    say: [null, null, null, null, null, null, null, null, null, null, null, null],
  },
  'epistemology-knowledge-3': {
    at: [null, [186, 335, 2, 180], null, [189, 335, 3, 183], [191, 335, 2, 185], null, [192, 335, 2, 180], [197, 335, 2, 179], [192, 335, 2, 180], [193, 335, 2, 181], [195, 334, 2, 177], null],
    say: [null, 'Certain isn’t the same as true.', null, 'A demon. Really?', 'Doubt at maximum.', null, 'So the demon is a tool.', 'One refuses to crack.', 'Doubt that rebuilds.', null, null, null],
  },
  'ethics-ethics-2': {
    at: [null, [217, 336, 3, 259], null, null, null, null, null, null, null, null, null, null, null, null, null],
    say: [null, 'Three verdicts. One wallet.', null, 'Not three religions.', 'I use all three.', null, 'Everyone counts the same.', null, 'Would I want that rule?', 'It eats itself.', null, 'Who am I becoming, then.', null, null, null],
  },
  'metaphysics-being-2': {
    at: [null, null, [135, 363, 3, 135], [168, 365, 3, 168], [169, 366, 3, 169], null, [229, 363, 3, 229], null, [264, 362, 3, 264], [297, 364, 3, 297], null, [222, 364, 3, 222], null],
    say: [null, null, 'Always a reason.', 'Why anything at all?', 'Nothing was simpler.', null, 'Was nothing ever on offer?', null, 'There’s nothing to step on.', 'You can’t point at it.', null, null, null],
  },
  'aesthetics-aesthetics-2': {
    at: [null, [202, 343, 3, 202], [201, 340, 3, 201], [203, 343, 3, 203], null, [203, 340, 3, 203], [200, 342, 3, 200], [194, 343, 3, 194], [202, 340, 3, 202], null],
    say: [null, 'Art as an infection.', 'I catch the feeling.', 'The room was frightened.', null, null, 'Packed into lines.', 'Nothing else does that.', null, null],
  },
  'logic-arguments-4': {
    at: [null, [85, 364, 3, 85], null, [81, 364, 3, 81], null, [89, 362, 2, 89], null, [89, 364, 2, 89], null, [81, 363, 2, 81], [73, 366, 2, 73], null],
    say: [null, 'Two different rulers.', null, 'Wrong ruler, wrong verdict.', null, 'That one locks shut.', null, 'And that one only leans.', null, null, null, null],
  },
  'political-political-2': {
    at: [null, null, null, null, null, null, null, null, null, null, null, null],
    say: [null, 'Bodies, or minds.', null, 'Entitled to be obeyed.', 'One ship, or a fleet.', 'Only legitimacy splits them.', null, 'Custom and bloodline.', 'Or rules and offices.', null, null, null],
  },
  'logic-arguments-3': {
    at: [null, [74, 386, 1, 68], null, null, null, null, null, null, null, null, null],
    say: [null, 'Shape, not truth.', null, null, 'But toasters aren’t gold.', 'Ah. Valid, not sound.', null, null, 'So go at the premises.', null, null],
  },
  'ethics-ethics-4': {
    at: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    say: [null, 'That is a bigger claim.', 'They do differ.', 'Right because they say so?', 'That’s the slide.', null, null, 'Some things hold anyway.', 'Differing isn’t equal.', 'Every society, the same few.', null, 'A shared floor.', null, null, null],
  },
  'ethics-ethics-3': {
    at: [null, [217, 384, 3, 217], null, [219, 383, 3, 219], null, [217, 384, 3, 217], null, [216, 384, 3, 216], [216, 384, 3, 216], [217, 384, 3, 217], [217, 384, 3, 217], null, [151, 384, 3, 217], [153, 384, 3, 213], null],
    say: [null, 'Same goal. They split.', null, 'One instead of five.', null, 'Five outweigh one.', null, 'Not a sum, then.', 'Duty, whatever follows.', 'Who do I become?', 'What would a wise one do?', null, null, null, null],
  },
  'epistemology-knowledge-4': {
    at: [null, [84, 364, 2, 192], null, [81, 365, 1, 195], null, [170, 308, 3, 200], [80, 364, 2, 200], [170, 308, 3, 200], [81, 365, 1, 195], [199, 364, 3, 199], [199, 364, 1, 199], [169, 311, 3, 199], [165, 317, 3, 195], null],
    say: [null, 'Blank paper.', null, 'Burned, then I know hot.', null, 'Never had to be shown.', 'Before any burn.', 'The boy already knew.', 'Learning is remembering?', null, 'Both half right.', 'The mind has shapes.', null, null],
  },
  'metaphysics-being-3': {
    at: [null, [155, 394, 1, 143], [155, 394, 1, 143], [158, 394, 1, 146], [155, 395, 1, 143], [158, 394, 1, 140], null, [155, 395, 1, 137], [155, 393, 1, 137], [134, 393, 1, 134], [147, 394, 3, 147], null],
    say: [null, 'You can’t step in twice.', 'So he split the world.', 'Becoming never holds.', 'Shadows for the real thing.', 'The wall is where we live.', null, 'Never quite equal.', 'The copy is only good.', null, null, null],
  },
  'epistemology-knowledge-5': {
    at: [null, [80, 382, 1, 80], [78, 383, 1, 78], [79, 383, 3, 79], [79, 384, 3, 79], [79, 384, 1, 79], null, [79, 384, 1, 79], [80, 384, 1, 80], [85, 384, 1, 85], null, [78, 381, 3, 78], [80, 381, 3, 80], null],
    say: [null, 'Nobody taught me that.', 'Not the useful kind.', 'Free knowledge.', 'I do just look.', 'And that is the evidence.', null, 'Knocked off balance.', 'Knowledge as power, then.', 'Understand it, or use it.', null, null, null, null],
  },
  'metaphysics-being-4': {
    at: [null, [326, 370, 3, 332], [325, 370, 3, 331], null, [324, 371, 3, 324], null, [326, 371, 3, 332], [328, 370, 3, 334], [324, 370, 3, 330], [326, 370, 3, 326], null],
    say: [null, 'Thinking it makes it a thing.', 'Every grab turns it real.', null, 'It can’t be said at all.', null, 'Then nothing can change.', 'Motion as illusion.', null, null, null],
  },
  'aesthetics-aesthetics-3': {
    at: [null, [329, 394, 2, 347], [326, 392, 1, 344], [326, 392, 1, 338], null, null, null, [327, 396, 1, 333], [217, 392, 3, 337], null, [326, 393, 1, 344], null],
    say: [null, 'Not one, anywhere.', 'It hurts and I go anyway.', 'He never says what.', 'Nobody looks away.', 'Drawn well, I can look.', null, 'It never argues.', 'Dangerous, then.', null, null, null],
  },
  'aesthetics-aesthetics-4': {
    at: [null, [221, 365, 2, 221], [220, 365, 2, 220], [221, 365, 3, 221], [224, 365, 3, 224], [225, 365, 2, 225], [225, 365, 2, 225], null, [222, 365, 3, 222], [222, 365, 2, 222], [220, 365, 2, 220], [221, 364, 2, 221], null],
    say: [null, 'So what makes it art?', 'Copy the world, then.', 'Or carry a feeling.', 'He just signed it.', 'The maker chose it.', 'Choosing was the work.', null, 'It fits neither.', 'Asking is already the work.', null, null, null],
  },
  'political-political-3': {
    at: [null, [202, 374, 3, 202], [203, 374, 3, 203], [205, 374, 3, 205], [203, 375, 3, 203], null, null, [205, 372, 3, 205], [205, 372, 3, 205], [205, 372, 3, 205], [204, 375, 2, 204], null],
    say: [null, 'Compelled, or owed.', 'No rules at all.', 'So they covenant.', 'Only while it guards them.', null, null, 'What everyone truly shares.', 'Rules I gave myself.', null, null, null],
  },
  'logic-arguments-6': {
    at: [null, null, [74, 373, 3, 62], [72, 372, 3, 66], [72, 372, 3, 66], null, [71, 372, 3, 65], [71, 372, 3, 65], null],
    say: [null, null, 'So Q rides on P.', 'It doesn’t say it rains.', 'Only the link, then.', null, null, null, null],
  },
  'logic-arguments-5': {
    at: [[80, 382, 3, 80], null, null, [77, 382, 3, 77], [75, 382, 3, 75], null, [78, 383, 3, 78], [78, 383, 3, 78], [80, 383, 3, 80], null],
    say: ['One weak link.', null, null, 'Two circles, one point.', 'Every step shown.', null, null, 'Not the vibe, then.', null, null],
  },
  'ethics-ethics-5': {
    at: [null, null, null, null, null, null, null, null, null, null, null],
    say: [null, null, null, null, null, null, null, null, null, null, null],
  },
  'political-political-4': {
    at: [null, [319, 340, 3, 205], null, null, null, null, null, null, null, null, null],
    say: [null, 'Left alone, then.', 'Only to stop harm.', 'My business, apparently.', 'Now it’s theirs.', null, 'Being my own master.', 'Empower, or leave alone?', null, null, null],
    vis: [8, 247, 393, 1],
  },
  'metaphysics-being-6': {
    at: [null, [72, 345, 3, 66], null, null, [125, 354, 3, 65], [125, 354, 3, 65], [122, 354, 3, 62], [71, 346, 3, 59], [125, 353, 3, 65], [124, 353, 3, 64], null],
    say: [null, 'Plank by plank.', null, null, 'Two kinds of same.', 'It keeps the second.', 'Every cell, replaced.', 'Still call it me.', null, null, null],
  },
  'aesthetics-aesthetics-6': {
    at: [null, null, [75, 381, 1, 75], [75, 381, 1, 75], null, null, null, null, null, null, null, null],
    say: [null, 'Small and smooth.', 'Terror, and I stay.', 'Safe on the cliff.', 'Danger at a distance.', null, null, 'So the awe is inward.', 'My mind made room.', 'I am the vast thing.', null, null],
  },
  'ethics-ethics-6': {
    at: [null, [217, 286, 3, 259], null, [262, 286, 2, 262], [261, 286, 2, 261], [212, 287, 3, 260], [261, 303, 2, 261], null, [213, 286, 3, 261], [213, 286, 3, 261], null],
    say: [null, 'Same numbers, though.', null, 'Shove him? No.', 'I’d pull, not push.', 'The arithmetic is identical.', 'A threat, or an instrument.', null, null, null, null],
  },
  'epistemology-knowledge-6': {
    at: [null, [73, 386, 3, 73], [73, 385, 3, 73], [71, 385, 3, 71], [76, 386, 3, 70], null, [72, 386, 3, 72], [75, 386, 3, 69], [73, 386, 3, 67], [73, 387, 3, 67], null],
    say: [null, 'A reason against it too.', 'Then nothing is secure.', 'So he simply stopped.', 'Calm, not despair.', null, null, 'Is THAT known, though?', 'Doubt softly, then.', null, null],
  },
  'epistemology-knowledge-7': {
    at: [null, [76, 355, 3, 58], [75, 355, 3, 63], [77, 355, 3, 65], [72, 355, 3, 60], [75, 355, 3, 57], null, [75, 355, 3, 69], [75, 354, 3, 69], [74, 355, 3, 68], [74, 352, 3, 62], null],
    say: [null, 'What gives me the right?', 'Seen, to unseen.', 'Science does it constantly.', 'Because it always has.', 'The past vouching for it.', null, 'The chicken was sure too.', 'More is no guarantee.', null, null, null],
  },
  'metaphysics-being-5': {
    at: [null, [172, 388, 3, 64], [173, 388, 3, 65], [172, 388, 3, 64], [171, 387, 3, 63], null, [71, 326, 3, 65], [71, 328, 3, 71], [166, 388, 3, 70], [166, 389, 3, 70], null],
    say: [null, 'Not why THIS thing.', 'Why anything to ask about.', 'True for no reason?', 'So what is the reason?', null, 'I am a thing that wonders.', 'The universe turns round.', null, null, null],
  },
  'aesthetics-aesthetics-5': {
    at: [null, [75, 388, 2, 69], [75, 388, 2, 69], [76, 387, 3, 64], [75, 388, 3, 63], null, [77, 387, 3, 59], [75, 387, 3, 69], [74, 388, 3, 74], [76, 388, 3, 70], null],
    say: [null, 'A just and loving look.', 'The fat, relentless ego.', 'Then — kestrel.', 'Nothing left but kestrel.', null, null, 'Patches, before things.', 'One leaf, before a tree.', null, null],
  },
  'political-political-5': {
    at: [null, [86, 381, 3, 86], [92, 380, 3, 92], null, [83, 380, 3, 83], [82, 381, 2, 82], [81, 383, 3, 81], [82, 383, 3, 82], [82, 384, 3, 82], [81, 384, 3, 81], [76, 383, 3, 82], null],
    say: [null, 'Everyone at their own work.', 'Only they know what is good?', null, 'Not knowing who I’d be.', 'Suddenly I’d be fairer.', null, 'Why we build them.', 'What makes them legitimate.', 'And what justice demands.', null, null],
  },
  'political-political-6': {
    at: [null, [73, 372, 3, 49], [76, 372, 3, 52], null, [73, 372, 3, 55], [74, 372, 3, 56], [72, 372, 3, 54], [74, 372, 3, 50], null],
    say: [null, 'Not knowing who I’ll be.', 'Liberties come first.', null, 'Not necessarily, though.', 'Better than under equal pay.', null, null, null],
  },
  'logic-arguments-7': {
    at: [null, null, [178, 347, 3, 178], null, null, [143, 349, 3, 143], [112, 349, 3, 112], [119, 349, 3, 119], null, [173, 348, 3, 179], [141, 348, 3, 147], [144, 347, 3, 162], null, null, null],
    say: [null, null, 'Just a promise.', null, null, null, 'Rain, so wet. Easy.', 'And I never looked.', null, 'Dry. So no rain?', null, 'Backwards, and still safe.', null, null, null],
  },
  'logic-arguments-8': {
    at: [null, [234, 385, 3, 234], null, null, [148, 384, 3, 148], null, [256, 385, 3, 148], [256, 385, 3, 142], null, null, [259, 384, 3, 259], null, [196, 384, 3, 196], [148, 385, 3, 148], null, null],
    say: [null, 'Rain. Obviously.', null, null, 'Wait — backwards?', null, null, 'A sprinkler. Of course.', null, null, 'Anything else could do it.', null, null, 'Two causes, one street.', null, null],
  },
  'ethics-ethics-7': {
    at: [null, [105, 371, 3, 105], null, [187, 371, 3, 187], null, [311, 372, 3, 311], [310, 371, 3, 310], [312, 371, 3, 312], [229, 370, 1, 229], [153, 371, 1, 153], [109, 372, 3, 109], [191, 372, 3, 191], [189, 373, 3, 189], null, null, null],
    say: [null, 'Same two seconds.', null, 'Nothing happened.', null, 'Only the road differs.', 'Same shrug, same speed.', 'Nothing inside them differs.', null, 'Only luck, then.', 'One stands trial.', null, 'Moral luck, it’s called.', null, null, null],
    vis: [10, 73, 393, 3],
  },
  'ethics-ethics-9': {
    at: [null, [79, 376, 3, 79], null, [159, 377, 3, 183], [136, 376, 3, 136], null, [162, 375, 3, 162], [161, 378, 3, 185], [140, 377, 3, 140], [115, 377, 3, 115], null],
    say: [null, 'A mark either way.', null, 'Leaving would break her.', 'Neither outranks.', null, 'He was right, probably.', 'The other claim hasn’t moved.', null, null, null],
  },
  'ethics-ethics-8': {
    at: [null, [190, 378, 3, 190], [190, 377, 3, 190], [189, 378, 3, 189], [189, 378, 3, 189], [223, 378, 3, 223], [223, 376, 3, 223], [243, 377, 3, 243], [243, 377, 3, 243], [240, 378, 3, 240], [243, 377, 3, 243], null, [208, 378, 3, 208], [206, 377, 3, 206], [206, 378, 3, 206], [213, 379, 3, 213], [231, 378, 3, 231], null],
    say: [null, 'Or just go and sit.', 'Step back. Be impartial.', 'Nobody’s name in them.', 'No box fits her.', 'The one you know.', 'No theory said a word.', 'Something already knows.', null, 'Bonds, not boxes.', 'A different voice.', null, null, 'It grows out of being cared for.', 'Long before any rulebook.', 'Not endless self-sacrifice.', 'Rules, and then the person.', null],
  },
  'epistemology-knowledge-31': {
    at: [null, [233, 373, 3, 233], [234, 373, 3, 234], [233, 372, 3, 233], [232, 372, 3, 232], [232, 372, 3, 232], null, [235, 370, 3, 235], [236, 370, 3, 236], [253, 371, 3, 235], [238, 372, 3, 238], null],
    say: [null, 'That’s all I have.', 'There it is. The turn.', 'Clear as anything.', 'But is the memory good?', 'Same cabinet, same stuff.', null, 'Signed by memory.', 'The door is still over there.', null, null, null],
  },
  'logic-arguments-31': {
    at: [null, [98, 385, 3, 98], [101, 385, 3, 101], [102, 385, 3, 102], [102, 388, 3, 102], null, [96, 385, 3, 96], [101, 385, 3, 101], [102, 386, 3, 102], [95, 386, 3, 95], null],
    say: [null, 'Three. Interesting.', 'The needle hasn’t moved.', 'Tails is DUE, surely.', 'The needle again.', null, 'Twenty-six blacks.', 'The wheel didn’t know.', null, null, null],
  },
  'ethics-ethics-32': {
    at: [null, [87, 302, 3, 183], [84, 303, 3, 186], null, [188, 336, 3, 188], [188, 335, 3, 188], [189, 335, 3, 189], null],
    say: [null, 'The reasons sit behind it.', 'Only the card crossed.', null, 'Now the card is no use.', null, null, null],
  },
  'ethics-ethics-31': {
    at: [null, [134, 386, 3, 134], [130, 386, 3, 130], [136, 386, 3, 136], [130, 386, 3, 130], null, [134, 386, 3, 134], [130, 386, 3, 130], [225, 385, 1, 213], [166, 386, 3, 166], null],
    say: [null, 'Four rungs closer.', 'Nothing needed to change.', 'Genuinely out of reach.', 'The lamp went out.', null, 'Back on. I didn’t change.', 'It was tracking the reach.', null, null, null],
    vis: [8, 75, 393, 3],
  },
  'logic-arguments-32': {
    at: [null, null, null, null, null, null, null, null, null, null],
    say: [null, 'Sounds like yes or no.', 'Yes — so I was cheating.', 'Nobody even claimed it.', 'No is worse.', 'Both doors are traps.', null, null, null, null],
  },
  'epistemology-knowledge-32': {
    at: [null, [76, 355, 3, 58], [73, 354, 3, 55], [72, 355, 3, 60], [74, 355, 3, 62], null, [76, 354, 3, 58], [75, 355, 3, 57], [74, 354, 3, 62], [72, 355, 3, 60], null],
    say: [null, 'Nothing on it is false.', 'Nothing on it at all.', 'Every rock, then.', 'The tide would beat me.', null, 'One to one. Perfect.', 'And it shows one rock.', null, null, null],
  },
  'metaphysics-being-13': {
    at: [null, [124, 373, 3, 124], [139, 374, 3, 139], [112, 374, 3, 112], null, [154, 375, 3, 154], [200, 371, 3, 200], [171, 373, 3, 183], [171, 373, 3, 183], null],
    say: [null, 'A chain, not a body.', 'Now there are two of me.', 'Neither is the copy.', null, 'Nothing chooses.', 'Identity has to pick one.', null, null, null],
    vis: [6, 76, 393, 3],
  },
  'political-political-12': {
    at: [null, [74, 346, 3, 74], [126, 346, 3, 126], [140, 344, 3, 140], [111, 347, 3, 111], null, [156, 348, 3, 156], [168, 348, 3, 168], [146, 347, 3, 146], [124, 346, 3, 124], null],
    say: [null, 'Why that is dangerous.', 'How many doors are open.', 'Nothing is blocking me.', 'But can I walk through it?', null, 'My real self wants this?', 'And calls it freedom.', null, null, null],
  },
  'logic-arguments-22': {
    at: [null, [127, 367, 3, 127], [149, 368, 3, 149], null, [146, 368, 3, 158], [145, 369, 3, 145], [107, 367, 3, 107], null],
    say: [null, 'All, none, some, some not.', 'A promise about every one.', null, 'One cat finishes it.', null, null, null],
  },
  'metaphysics-being-15': {
    at: [null, [76, 375, 3, 76], [129, 374, 3, 129], [166, 375, 3, 178], [146, 376, 3, 146], null, [162, 374, 3, 162], [140, 351, 3, 140], [108, 353, 3, 108], null],
    say: [null, 'What did I actually see?', 'It moved. It touched.', 'Three plain things.', 'Slow it down and look.', null, 'No glue anywhere.', null, null, null],
  },
  'aesthetics-aesthetics-19': {
    at: [null, [127, 358, 3, 127], [182, 358, 2, 182], [144, 358, 3, 144], [112, 358, 3, 112], null, [159, 359, 3, 159], [174, 360, 2, 186], [146, 358, 3, 146], [126, 359, 3, 126], null],
    say: [null, 'Nobody signed the pipe.', 'Frame it and I look.', 'Flat, buggy, no view.', 'That glance was the whole thing.', null, 'One of the densest there is.', 'The verdict moved, not it.', null, null, null],
  },
  'ethics-ethics-18': {
    at: [null, [129, 371, 3, 129], [178, 371, 3, 178], [146, 371, 3, 146], [117, 372, 3, 117], null, [157, 372, 3, 157], [145, 373, 3, 145], [110, 372, 3, 110], null],
    say: [null, 'The reason was reason.', 'So they were outside.', 'Infants can’t reason.', 'Nobody puts them outside.', null, 'Can they suffer, then.', null, null, null],
  },
  'metaphysics-being-24': {
    at: [null, [77, 386, 3, 77], [129, 386, 3, 129], [156, 385, 3, 180], null, [157, 386, 3, 157], [174, 386, 3, 174], [146, 385, 3, 146], [121, 387, 3, 121], null],
    say: [null, 'One grain never matters.', 'Every step is safe.', 'Half gone, still a heap.', null, 'One grain. Still HEAP.', 'Something I agreed is wrong.', null, null, null],
  },
  'political-political-13': {
    at: [null, [77, 387, 3, 71], [127, 388, 3, 127], [179, 389, 3, 179], [180, 389, 3, 180], [179, 389, 3, 179], null, [112, 388, 3, 112], [112, 387, 3, 112], [145, 379, 3, 145], [141, 381, 3, 141], null],
    say: [null, 'Not for their own good.', 'Nobody is assaulted.', 'And here is the argument.', 'It feels like a proof.', 'Exactly what they wanted.', null, 'He grants one and three.', 'So it all rests on the middle.', null, null, null],
    vis: [9, 73, 393, 3],
  },
  'political-political-15': {
    at: [null, [129, 377, 3, 129], [184, 376, 3, 184], [184, 376, 3, 184], null, [204, 379, 2, 204], [185, 380, 3, 185], [185, 379, 3, 185], null],
    say: [null, 'Try the lawful routes first.', 'That is where most fall over.', 'In daylight. And then stay.', null, 'Ran when it was over.', null, null, null],
    vis: [5, 71, 393, 3],
  },
  'logic-arguments-26': {
    at: [null, [78, 378, 3, 78], [132, 374, 3, 132], [167, 376, 3, 185], [168, 376, 3, 186], [168, 376, 3, 186], null, [160, 376, 3, 160], [169, 376, 3, 181], [150, 380, 3, 150], [120, 379, 3, 120], null],
    say: [null, 'Then be reasonable.', 'Call it N.', 'I’m allowed to suppose it.', 'N plus one is bigger.', 'So N wasn’t the largest.', null, 'Every step after was valid.', 'The assumption failed.', null, null, null],
  },
  'logic-arguments-25': {
    at: [null, [74, 389, 3, 74], [127, 389, 3, 127], [178, 389, 3, 178], null, [147, 389, 3, 153], [115, 388, 3, 115], [90, 388, 3, 90], null],
    say: [null, 'Almost everyone is wrong.', 'One in ten thousand.', 'It catches that one.', null, '1% of a big number.', null, null, null],
  },
  'ethics-ethics-23': {
    at: [null, [77, 383, 3, 71], [125, 383, 3, 125], [147, 381, 3, 147], null, [152, 381, 3, 152], [176, 385, 3, 182], [146, 382, 3, 146], [122, 382, 3, 122], null],
    say: [null, 'Not a hard question.', 'Not even a decision.', 'Eight thousand miles off.', null, 'The cost is the same.', 'Only the distance differs.', null, null, null],
  },
  'aesthetics-aesthetics-11': {
    at: [null, [77, 354, 3, 77], [132, 354, 3, 132], [152, 354, 3, 182], [153, 357, 3, 153], null, [152, 352, 3, 164], [146, 355, 3, 146], [120, 354, 3, 120], null],
    say: [null, 'Nine seconds.', 'Not similar. Identical.', 'Everything you could measure.', 'Only the plaques differ.', null, 'So it isn’t in the picture.', null, null, null],
  },
  'aesthetics-aesthetics-16': {
    at: [null, [128, 379, 3, 128], [147, 380, 3, 177], [142, 379, 3, 142], null, [155, 379, 3, 161], [147, 381, 3, 147], [109, 381, 3, 109], null],
    say: [null, 'Not one mark has moved.', 'It happens to me, then.', 'He despised the man.', null, 'Longer than the painting.', null, null, null],
  },
  'epistemology-knowledge-2': {
    at: [null, [76, 354, 3, 76], [128, 354, 3, 128], null, [165, 354, 3, 183], [173, 349, 3, 185], null, [170, 345, 3, 176], [170, 344, 3, 176], [170, 345, 3, 176], null],
    say: [null, 'Now get in.', 'Precise and true.', null, 'I’ve memorised all of them.', 'Nothing has arrived.', null, 'The hands had to move.', null, null, null],
    vis: [7, 75, 393, 3],
  },
  'epistemology-knowledge-21': {
    at: [null, [76, 354, 3, 76], [129, 354, 3, 129], null, [135, 353, 3, 135], [124, 354, 3, 124], [124, 354, 3, 124], null, [156, 355, 3, 156], [146, 355, 3, 146], [106, 354, 3, 106], null],
    say: [null, 'Genuinely try.', 'It hasn’t moved.', null, 'Wanting it.', 'Deciding on it.', 'The needle still won’t move.', null, 'And I did nothing at all.', null, null, null],
  },
  'epistemology-knowledge-13': {
    at: [null, [78, 365, 3, 78], null, [150, 363, 3, 186], null, [153, 363, 3, 159], [150, 363, 3, 174], [148, 366, 3, 148], [122, 366, 3, 122], null],
    say: [null, 'No, flatly.', null, 'Better odds than most things.', null, 'So strike them all.', 'But I know it has a winner.', null, null, null],
  },
  'epistemology-knowledge-8': {
    at: [null, [189, 372, 3, 207], [189, 372, 3, 207], [151, 372, 3, 151], null, [166, 371, 3, 166], [192, 382, 3, 222], [159, 374, 3, 159], [89, 373, 3, 89], [89, 373, 3, 89], [163, 370, 3, 163], [150, 374, 3, 150], [93, 374, 3, 93], [96, 374, 3, 96], [97, 374, 3, 97], [149, 371, 3, 149], [186, 371, 3, 192], null, null],
    say: [null, 'And why again.', 'How long can he keep it up?', 'Another belief underneath.', null, 'Support goes under.', 'Now that needs propping.', 'Why trust the timetable?', 'Why trust the city?', 'Here comes the next why.', 'Still no floor.', 'On for ever, then.', 'Or a circle. Or bedrock.', null, 'A handful hold themselves up.', 'Nowhere left to go.', null, null, null],
  },
  'epistemology-knowledge-9': {
    at: [null, [215, 372, 3, 215], [234, 372, 3, 246], null, [204, 372, 3, 204], [152, 373, 1, 140], [144, 360, 3, 144], [140, 360, 3, 140], [152, 372, 3, 128], null, [188, 374, 3, 188], [169, 375, 2, 169], [153, 373, 2, 135], [153, 373, 2, 141], [220, 370, 3, 220], [234, 372, 3, 276], [217, 373, 3, 277], null],
    say: [null, 'What am I claiming?', 'Just sitting there being it.', null, 'That sketch is a belief.', 'What makes it a good one?', null, 'It matches how things are.', 'Truth is the fit.', null, 'So go and check.', 'Compare it with what?', null, 'Locks into the rest.', 'Fitting the whole web.', 'Or just: it keeps working.', 'And never strands me.', null],
  },
  'metaphysics-being-7': {
    at: [null, [209, 370, 2, 209], [207, 371, 2, 207], [207, 371, 2, 207], [128, 370, 2, 128], [77, 369, 3, 65], [211, 369, 2, 211], null, [255, 369, 2, 255], [192, 372, 2, 192], [124, 370, 2, 124], [72, 369, 2, 66], [73, 369, 2, 67], [145, 370, 3, 145], [200, 370, 2, 200], [202, 371, 2, 202], null, null],
    say: [null, 'So where is yesterday?', 'Three slices on a road.', 'Rooms I could stroll between.', 'Just an empty frame.', 'Nowhere at all.', 'Tomorrow isn’t built.', null, 'Only the middle is filled.', 'One lit slice, moving.', 'Think of a book, then.', 'Page four hundred is set.', null, 'All three at once.', 'Now is just where I stand.', null, null, null],
  },
  'aesthetics-aesthetics-7': {
    at: [null, [223, 331, 3, 223], [219, 319, 3, 219], [298, 319, 3, 298], [247, 319, 3, 247], [247, 319, 3, 247], null, [218, 319, 3, 218], [217, 319, 3, 217], [220, 314, 3, 220], [257, 314, 3, 257], [257, 314, 3, 257], [258, 314, 3, 258], [258, 315, 3, 258], [296, 315, 3, 296], null],
    say: [null, 'On what grounds, though.', 'Three seconds. Thirty years.', 'A feeling isn’t a reason.', 'Scrape it. Nothing there.', 'In the mind doing the looking.', null, 'Then his mind counts too.', 'Something in me refuses.', null, 'Practice and comparison.', 'They agree: a standard.', 'A taster really does taste it.', 'It’ll show me more then.', null, null],
  },
  'metaphysics-being-8': {
    at: [null, [304, 384, 3, 304], [255, 381, 3, 255], [214, 381, 3, 214], [216, 381, 3, 216], null, [175, 383, 3, 175], [133, 382, 3, 133], [134, 382, 3, 134], null, [176, 379, 3, 176], [207, 379, 2, 207], null, [205, 381, 3, 205], [208, 382, 3, 208], [202, 382, 3, 202], null, null],
    say: [null, 'Pushed by the one before.', 'Long before I existed.', 'Here it comes.', 'Never once, then.', null, 'Right on schedule.', 'Physics started it.', 'A choice snaps the chain?', null, 'Both picked the wrong test.', 'So what else could it be?', null, null, 'Hume, and later Frankfurt.', 'From my own wants.', null, null],
  },
  'aesthetics-aesthetics-8': {
    at: [null, [164, 371, 2, 164], [164, 371, 1, 164], [97, 372, 2, 97], [75, 373, 1, 63], [127, 370, 2, 127], [162, 371, 1, 162], null, [73, 372, 1, 55], [126, 371, 1, 126], [164, 371, 1, 164], [103, 374, 1, 103], [204, 330, 3, 126], [162, 371, 2, 162], null, [98, 372, 1, 98], [75, 372, 1, 57], [127, 371, 1, 127], null],
    say: [null, 'Same canvas.', 'Two different reasons.', 'Glasses for each.', 'They change what I notice.', 'A block, an edge.', 'What it’s OF has gone quiet.', null, 'Same canvas. New painting.', 'Blocks into strokes.', 'Catching a mood, then.', null, 'Every real work has it.', 'Significant form.', null, 'Handing a feeling over.', 'He finds it by painting it.', null, null],
  },
  'political-political-7': {
    at: [null, [186, 352, 3, 264], [186, 352, 3, 264], [183, 356, 3, 219], [177, 358, 3, 177], [187, 353, 3, 265], null, null, [183, 355, 3, 219], [187, 356, 3, 187], [163, 356, 3, 187], [174, 355, 3, 258], null, null, [178, 355, 3, 292], [174, 353, 3, 216], [179, 356, 3, 179], null],
    say: [null, 'A government? Paper?', 'Or mine before any vote.', 'Mine the moment I exist.', 'Guard them, not hand them.', 'Written down and signed.', 'No signature, no right.', null, 'And the law is enforced.', 'It really is real.', null, 'The speech is still there.', 'They can break it.', 'Not un-give it.', null, 'Then quietly stopped.', 'If rights come from reasoning —', null],
  },
  'political-political-8': {
    at: [null, null, [104, 384, 3, 104], [145, 381, 3, 145], [187, 381, 3, 187], [136, 387, 3, 136], [100, 390, 3, 100], [146, 388, 3, 146], [188, 391, 3, 194], [188, 382, 2, 194], [188, 382, 2, 188], [184, 381, 3, 184], [102, 382, 3, 102], [127, 385, 3, 127], [138, 381, 3, 138], [138, 382, 3, 138], null, null],
    say: [null, null, 'Watch it fall apart.', 'Nobody cheated anyone.', 'One sees a plank of wood.', 'Three crates, three people.', 'You can’t get fairer. Can you?', 'Nobody favoured, nobody skipped.', 'And he’s still at the wood.', null, 'Nothing added or thrown away.', 'Dead level.', null, 'Equal resources?', 'Or equal chances.', 'What each can actually do.', null, null],
  },
  'metaphysics-being-9': {
    at: [null, [105, 362, 3, 105], [106, 362, 3, 106], null, [171, 362, 3, 171], [170, 363, 3, 170], [204, 360, 3, 204], [238, 361, 3, 238], [239, 361, 3, 239], [248, 361, 3, 236], null],
    say: [null, 'He couldn’t doubt the thinking.', 'Two substances, then.', null, 'How does it push?', 'The pineal gland. Really?', 'Damage a brain, lose the memory.', 'Something the brain does.', null, null, null],
  },
  'logic-arguments-9': {
    at: [null, null, null, null, null, null, null, null, null, null],
    say: [null, null, 'Whose mouth doesn’t matter.', 'That isn’t what they said.', 'He built it to knock it.', 'The claim never moved.', null, null, null, null],
  },
  'epistemology-knowledge-10': {
    at: [null, [97, 383, 2, 97], [100, 383, 2, 100], [93, 384, 2, 93], [93, 384, 2, 93], null, [163, 384, 2, 163], [164, 384, 2, 164], [204, 370, 3, 204], [242, 386, 2, 242], null],
    say: [null, 'So do I know, or not?', 'Only if you can’t be wrong.', 'Know it, and admit I might.', 'Both in the room at once.', null, 'Science never claims it.', 'Changing its mind is the method.', null, null, null],
  },
  'ethics-ethics-10': {
    at: [null, [198, 387, 3, 198], [198, 387, 3, 198], [198, 387, 3, 198], null, [198, 388, 3, 198], [198, 388, 3, 198], [198, 383, 3, 198], [198, 383, 3, 198], null],
    say: [null, 'Nobody deliberates.', 'No comparison to make.', 'So why did that need no thought?', null, 'Nine thousand kilometres off.', 'It doesn’t stop at the bank.', null, null, null],
  },
  'logic-arguments-10': {
    at: [null, [130, 383, 2, 70], null, [107, 384, 2, 107], null, [130, 384, 2, 136], [171, 385, 2, 171], [170, 384, 2, 170], [169, 384, 2, 169], null],
    say: [null, 'Nothing joins them.', null, 'There it is.', null, 'All of them? Really?', 'Said aloud, it’s rubbish.', null, null, null],
  },
  'aesthetics-aesthetics-9': {
    at: [null, [189, 353, 2, 87], [89, 353, 1, 89], [90, 354, 1, 90], [194, 340, 3, 122], [190, 355, 2, 154], null, [191, 352, 2, 185], [191, 354, 2, 215], [192, 342, 3, 216], [192, 341, 3, 216], null],
    say: [null, 'The rest was something else.', 'A copy of a box.', 'Just a box.', 'The question that broke it.', 'Nothing I can SEE.', null, 'Not in the object, then.', 'One option among many.', null, null, null],
  },
  'political-political-9': {
    at: [null, [186, 400, 3, 186], [187, 400, 3, 187], [190, 398, 3, 190], [198, 400, 3, 198], null, [196, 400, 3, 196], [194, 400, 3, 194], [191, 384, 3, 197], null],
    say: [null, 'Seven to one. Honest.', 'Whoever flatters best.', 'The procedure held.', 'Working, not failing.', null, 'Both named the danger.', null, null, null],
  },
  'logic-arguments-11': {
    at: [null, null, [73, 373, 3, 55], null, null, [106, 375, 3, 118], [106, 374, 3, 118], [106, 374, 3, 118], [98, 373, 3, 116], null],
    say: [null, null, 'Nothing smuggled yet.', null, null, 'Every link holds.', 'That’s what makes it a trap.', null, null, null],
  },
  'ethics-ethics-11': {
    at: [null, [73, 378, 3, 61], [73, 378, 3, 61], [74, 377, 3, 62], [85, 376, 3, 85], [121, 376, 3, 121], null, [89, 378, 3, 89], [89, 376, 3, 89], [86, 374, 3, 86], null],
    say: [null, 'A bar game and a symphony.', 'The same stuff, to him.', 'Intensity, duration, reach.', 'His own student refused.', 'Not on one level.', null, null, null, 'The column can’t settle it.', null],
  },
  'ethics-ethics-12': {
    at: [null, [99, 376, 3, 99], [110, 379, 3, 134], [110, 379, 3, 134], null, [111, 380, 3, 135], [107, 381, 3, 137], [111, 380, 3, 135], [109, 380, 3, 133], null],
    say: [null, 'Knowing I can’t repay.', 'Not what it costs me.', 'Hand it to everyone.', null, 'Nobody believes one now.', 'Nothing left to break.', null, null, null],
  },
  'epistemology-knowledge-11': {
    at: [null, [93, 315, 3, 93], [200, 345, 3, 134], [199, 347, 3, 175], [169, 345, 1, 169], [200, 344, 3, 164], [164, 345, 1, 164], null, [202, 344, 3, 202], [232, 344, 3, 232], [234, 344, 3, 234], [242, 345, 3, 242], null],
    say: [null, 'For a worse reason.', 'The other has moved on.', 'Stopped twelve hours ago.', 'But I believed it.', 'And a clock is a fair reason.', 'All three, then.', null, 'One instant, never again.', 'The match was an accident.', null, null, null],
  },
  'epistemology-knowledge-12': {
    at: [null, [185, 393, 3, 65], [185, 393, 3, 65], [188, 393, 3, 92], [185, 393, 3, 131], null, [129, 374, 3, 129], [189, 393, 3, 129], [185, 392, 3, 125], [187, 392, 3, 127], null],
    say: [null, 'So how did they get in?', 'Before I’ve thought at all.', 'The toast is long gone.', 'Longer, and it bends.', null, 'In from strangers.', 'Look what it does.', null, null, null],
  },
  'metaphysics-being-10': {
    at: [null, [75, 374, 3, 75], [93, 372, 3, 93], [124, 374, 3, 124], [127, 374, 3, 127], [128, 374, 3, 128], [128, 374, 3, 128], null, [124, 371, 3, 124], [124, 371, 3, 124], [124, 371, 3, 124], [131, 374, 3, 131], null],
    say: [null, 'So where is the redness?', 'Give it a card.', 'Where does the card go?', 'Above every red thing.', 'Only in the things.', 'No red object, no redness.', null, 'Just a word we hang on.', 'It touches none of them.', null, null, null],
  },
  'metaphysics-being-11': {
    at: [null, null, null, null, null, null, null, null, null, null, null, null],
    say: [null, 'Holding on to what?', 'A prince and a cobbler.', 'Every room, every promise.', 'Neither body moved.', 'Only the memories.', null, null, null, 'The names crossed the floor.', 'It went where they went.', null],
  },
  'aesthetics-aesthetics-10': {
    at: [null, [75, 387, 3, 39], [72, 387, 3, 48], [84, 387, 3, 84], null, [116, 387, 3, 116], [115, 387, 3, 115], [180, 367, 3, 120], [182, 366, 3, 122], null],
    say: [null, 'Making cruelty look glorious.', 'The craft verdict is easy.', 'A book is well written, or not.', null, 'What it invites isn’t a side issue.', 'If it asks and I refuse —', null, null, null],
  },
  'aesthetics-aesthetics-12': {
    at: [null, [185, 375, 3, 185], [187, 375, 3, 187], [176, 376, 3, 146], null, [171, 376, 3, 141], [171, 376, 3, 141], [171, 376, 3, 141], [171, 376, 3, 141], null],
    say: [null, 'This is grief, clearly.', 'No hint of a joke.', 'Every mark says the same.', null, 'He says it was a joke.', 'The box still won’t open.', null, null, null],
  },
  'political-political-10': {
    at: [null, [76, 392, 3, 40], [73, 392, 3, 43], [71, 392, 3, 47], [83, 391, 3, 83], [119, 393, 3, 119], [119, 393, 3, 119], [114, 393, 3, 114], null, [107, 393, 3, 107], [107, 393, 3, 107], [112, 393, 3, 112], [118, 396, 3, 118], null],
    say: [null, 'The picture won’t tell me.', 'The world lies unowned.', 'He bolts on a condition.', 'Never only a pile.', 'Traded, and handed on.', 'Was every step clean?', 'Then it’s hers, however tall.', null, 'Lay a level across the tops.', 'Only if it lifts the bottom.', null, null, null],
  },
  'political-political-11': {
    at: [null, null, null, null, [248, 365, 2, 128], null, null, null, null, null, null, null, null, null],
    say: [null, 'Then I’ve decided the state.', 'An instrument, not a history.', 'Everyone can kill everyone.', 'Too strong to be argued with.', null, 'We already owe each other.', 'They keep what they came with.', 'Property taught us to compare.', 'Nobody at the top at all.', 'Freedom handed back.', null, null, null],
  },
  'logic-arguments-12': {
    at: [null, [72, 382, 2, 48], [74, 382, 3, 50], null, null, [75, 382, 2, 51], [76, 382, 2, 46], [71, 383, 2, 41], null],
    say: [null, 'Both doors are real.', 'But only two?', null, null, 'There was a whole wall.', null, null, null],
  },
  'epistemology-knowledge-14': {
    at: [null, [76, 374, 3, 52], [76, 373, 3, 52], null, [74, 374, 3, 50], [74, 374, 3, 50], [74, 374, 3, 50], [77, 373, 3, 59], null],
    say: [null, 'Every check is on this side.', 'Inferred, not observed.', null, 'Watch the screen.', 'Nothing moved. Nothing would.', null, null, null],
  },
  'ethics-ethics-13': {
    at: [null, [75, 383, 1, 39], [75, 384, 1, 39], null, [73, 383, 1, 31], [75, 383, 1, 33], [75, 383, 1, 45], null],
    say: [null, 'Run from what shouldn’t.', 'Or charge at what shouldn’t.', null, 'Somewhere along here.', null, null, null],
  },
  'political-political-14': {
    at: [null, null, null, null, null, null, null, null, null],
    say: [null, 'A dollar each, freely.', 'Every transfer is free.', 'And the pattern is gone.', null, 'Reach in and stop them.', null, null, null],
  },
  'metaphysics-being-12': {
    at: [null, [75, 384, 2, 45], [74, 384, 2, 50], [75, 384, 2, 51], [76, 384, 2, 52], [75, 384, 2, 45], null, [76, 381, 1, 46], [76, 380, 1, 46], [73, 383, 2, 43], null],
    say: [null, 'The stream is easy.', 'Somebody is having them.', 'A box for the owner.', 'He never caught it.', 'The box stays empty.', null, 'An illusion, they say.', null, null, null],
  },
  'aesthetics-aesthetics-13': {
    at: [null, [73, 378, 3, 49], [73, 378, 3, 49], [75, 378, 3, 45], [75, 378, 3, 45], null, [75, 378, 3, 45], [76, 378, 3, 46], [77, 379, 3, 47], null],
    say: [null, 'No expert could tell.', 'No brushstroke to find.', 'Where each has been, then.', 'Starts last year and stops.', null, 'Not a single canvas changed.', null, null, null],
  },
  'political-political-32': {
    at: [null, null, null, null, null, null, null, null, null],
    say: [null, 'The same either way.', 'Worse than the drive there.', 'I knew that going in.', null, 'Look at the gap, then.', null, null, null],
  },
  'metaphysics-being-32': {
    at: [null, [71, 374, 3, 59], [72, 374, 3, 60], [74, 373, 2, 62], [74, 374, 3, 62], null, [74, 374, 3, 62], [72, 374, 3, 66], [207, 373, 2, 207], [208, 374, 3, 208], null],
    say: [null, 'Just these two.', 'Alike all the way down.', 'Even the relations match.', 'Both descriptions are true.', null, 'The label came from outside.', 'Take it away. Nothing changed.', null, null, null],
  },
  'aesthetics-aesthetics-32': {
    at: [null, [71, 369, 3, 65], [73, 370, 3, 67], [76, 370, 3, 64], null, [72, 371, 3, 66], [72, 371, 3, 66], [73, 371, 3, 67], [75, 372, 3, 75], null],
    say: [null, 'Same years, reversed.', 'Nothing added or taken.', 'Never bad, never remarkable.', null, 'All three hold the same.', 'And I can still rank them.', null, null, null],
  },
  'aesthetics-aesthetics-31': {
    at: [null, null, [75, 392, 2, 69], null, null, null, [225, 384, 3, 225], [209, 384, 3, 209], null],
    say: [null, 'Nobody stands up.', 'Same nine notes.', null, 'And now they’re on their feet.', 'Only the meter moved.', null, null, null],
  },
  'metaphysics-being-31': {
    at: [null, null, null, null, null, null, null, null, null, null, null],
    say: [null, 'Nothing was added.', 'Three more things, though.', 'You can count them.', 'Same as with objects.', null, 'So what did I count?', 'Cheese, ring, or gap.', null, null, null],
  },
  'political-political-31': {
    at: [null, [71, 393, 2, 59], [71, 393, 3, 59], [71, 393, 2, 59], null, [72, 393, 1, 60], [73, 393, 1, 55], [72, 393, 1, 54], [73, 392, 1, 55], null],
    say: [null, 'The wear is shared.', 'I’d be daft not to.', 'So does everyone.', null, 'One whole unit of gain.', 'One unit of harm, quartered.', null, null, null],
  },
  'logic-arguments-34': {
    at: [null, [75, 384, 3, 51], null, [76, 384, 3, 52], [74, 385, 3, 56], [71, 385, 3, 59], null, [74, 384, 3, 56], [77, 384, 3, 53], [72, 384, 3, 54], [75, 383, 3, 57], null],
    say: [null, 'A handful. Very wrong.', null, 'This feels like progress.', 'Four times, half the bracket.', 'Square root, not in step.', null, null, 'Only people who answered.', 'Tight around the wrong one.', null, null],
  },
  'epistemology-knowledge-33': {
    at: [null, [74, 385, 3, 56], [74, 387, 3, 56], [73, 388, 3, 61], [73, 388, 3, 61], null, [76, 387, 3, 58], [74, 388, 3, 56], [77, 388, 3, 59], null],
    say: [null, 'Nobody blinks.', 'Now a cheque is riding on it.', 'And I got out to check.', 'Same evidence as before.', null, null, 'A height for this Saturday.', null, null],
  },
  'metaphysics-being-33': {
    at: [null, [77, 364, 3, 59], [73, 363, 3, 55], [73, 363, 3, 55], [75, 363, 3, 57], [75, 364, 3, 57], null, [71, 363, 3, 71], [72, 363, 3, 66], [74, 363, 3, 62], [77, 363, 3, 59], null],
    say: [null, 'That needs no explaining.', 'Now run it backwards.', 'I knew that was wrong.', 'Every collision is legal.', 'The same laws exactly.', null, null, 'Order is rare.', 'It never wanders back.', null, null],
  },
  'metaphysics-being-34': {
    at: [null, [74, 374, 3, 56], [71, 374, 3, 59], [74, 375, 3, 62], [77, 375, 3, 59], [71, 370, 3, 59], [75, 374, 3, 63], null, [76, 375, 3, 64], [76, 374, 3, 64], [71, 374, 3, 65], [74, 375, 3, 68], null],
    say: [null, 'Ask it anyway.', 'Not who owns it.', 'Not the legs, then.', 'The wood does.', 'Underneath, not earlier.', 'And under that, molecules.', null, null, 'Resting on nothing.', 'What holds what up.', null, null],
  },
  'epistemology-knowledge-34': {
    at: [null, [71, 376, 3, 65], [71, 381, 3, 53], [74, 381, 3, 56], [74, 380, 3, 56], [71, 378, 3, 59], [71, 378, 3, 59], [71, 378, 3, 59], null, [71, 376, 3, 71], [74, 377, 3, 62], [76, 379, 3, 58], null],
    say: [null, 'How often it holds.', 'They agree down here.', 'Nobody goes wrong there.', 'Now say certain.', 'The space between them.', 'Not the same as right.', 'Half, and says half. Level.', null, null, 'Fix it from either end.', null, null],
  },
  'logic-arguments-33': {
    at: [null, [76, 364, 3, 64], [75, 367, 3, 57], [76, 367, 3, 58], [71, 367, 3, 59], [71, 367, 3, 59], null, [77, 369, 3, 71], [75, 367, 3, 75], [76, 367, 3, 64], [77, 368, 3, 65], null],
    say: [null, 'Now it behaves.', 'Every dot, exactly.', 'Nothing unexplained.', 'Nowhere near the new one.', 'It learned my errors.', null, null, 'Fewer moving parts.', 'Each one can be wrong.', null, null],
  },
  'ethics-ethics-33': {
    at: [null, [74, 368, 3, 50], [74, 367, 3, 50], [73, 368, 3, 49], [76, 367, 3, 52], null, [73, 368, 3, 55], [76, 368, 3, 52], [73, 368, 3, 61], [73, 368, 3, 49], null],
    say: [null, 'That much is easy.', 'There’s still one more.', 'What says I may stop?', 'Until the columns are level.', null, null, 'Not a wider life.', 'A narrowed one.', null, null],
  },
  'aesthetics-aesthetics-33': {
    at: [null, [75, 379, 3, 57], [71, 379, 3, 59], [71, 380, 3, 59], [73, 380, 3, 61], null, [73, 380, 3, 61], [75, 379, 3, 69], [74, 379, 3, 62], null],
    say: [null, 'Paint, glaze, varnish, dirt.', 'Nobody objects to that.', 'Now the argument starts.', 'Scrubbed off for ever.', null, null, 'No layer is the original.', null, null],
  },
  'political-political-33': {
    at: [null, [77, 393, 3, 53], [71, 393, 3, 53], [71, 393, 3, 53], [72, 393, 3, 54], [76, 393, 3, 58], null, [72, 393, 3, 60], [77, 393, 3, 53], [73, 391, 3, 55], null],
    say: [null, 'Every argument, then.', 'One wants the doors shut.', 'Tolerance ending tolerance.', 'So shut them.', 'Now I’m the thing I feared.', null, null, 'Not belief. Method.', null, null],
  },
  'political-political-34': {
    at: [null, [73, 326, 3, 55], [71, 324, 3, 53], [75, 327, 3, 57], null, [75, 324, 3, 57], [75, 325, 3, 57], [73, 324, 3, 67], [77, 324, 3, 59], null],
    say: [null, 'That one’s easy.', 'The river doesn’t stop there.', 'And too far away is worse.', null, null, 'As small as possible.', 'And no smaller.', null, null],
  },
  'ethics-ethics-34': {
    at: [null, [74, 387, 3, 44], [75, 387, 3, 45], [72, 387, 3, 48], [74, 387, 3, 50], null, [75, 387, 3, 45], [72, 387, 3, 48], [75, 387, 3, 45], null],
    say: [null, 'A little less each.', 'More of it, so higher.', 'Only just worth living.', 'He couldn’t accept it.', null, null, 'Try the average, then.', null, null],
  },
  'aesthetics-aesthetics-34': {
    at: [null, [74, 393, 3, 50], [73, 392, 3, 49], [74, 393, 3, 50], null, [73, 393, 3, 55], [72, 393, 3, 54], [72, 393, 3, 54], null],
    say: [null, 'Not resemblance, then.', 'Eleven plates, fewer lines.', 'Still unmistakably a bull.', null, null, 'I was taught how one goes.', null, null],
  },
  'logic-arguments-2': {
    at: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    say: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  'logic-arguments-1': {
    at: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    say: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  'political-political-35': {
    at: [null, [73, 394, 3, 55], [74, 393, 2, 56], [76, 394, 3, 58], [74, 394, 3, 68], [74, 394, 3, 62], [75, 394, 3, 63], [75, 394, 3, 57], [72, 393, 2, 54], null, [93, 395, 3, 93], null],
    say: [null, 'Nine empty chairs.', null, 'Now the strange part.', 'Other jobs, other lives.', 'Other children.', 'Not the same three.', 'They’d never have been born.', null, null, 'Maybe there is no victim.', null],
  },
  'aesthetics-aesthetics-35': {
    at: [null, [74, 372, 3, 62], [75, 371, 3, 63], [76, 371, 3, 64], [73, 371, 3, 67], [74, 371, 3, 62], null, [72, 371, 3, 60], [72, 372, 3, 60], [76, 372, 3, 58], [84, 371, 3, 96], [139, 363, 3, 139], null],
    say: [null, 'Two places. Right.', 'A surgery, obviously.', null, 'Both readings had to fit.', 'Wrong isn’t surprising.', null, 'No jolt this time.', 'That’s what explaining does.', 'Laughing at someone?', 'Or letting out pressure.', null, null],
  },
  'logic-arguments-35': {
    at: [null, [77, 376, 3, 71], [76, 378, 3, 70], [74, 376, 3, 74], [77, 376, 3, 77], [75, 376, 3, 75], [73, 377, 3, 73], [75, 378, 3, 69], null, [75, 377, 3, 69], [81, 376, 3, 105], [82, 376, 3, 148], null],
    say: [null, 'Week for week.', 'Not a coincidence.', 'Cones cause drownings?', 'The data doesn’t care.', null, 'Take the summer out.', 'It was never there.', null, 'Feet and reading. Same trick.', 'Smokers drank coffee.', null, null],
  },
  'metaphysics-being-35': {
    at: [null, [326, 318, 3, 332], [328, 318, 3, 334], [273, 319, 3, 237], [274, 320, 3, 166], null, null, null, null, [133, 371, 1, 133], [272, 320, 3, 182], null],
    say: [null, 'Nothing broken yet.', 'A tourist, then.', 'So I’m never born.', 'Then I am. Then I’m not.', null, null, null, 'I was always there.', 'It always jammed.', null, null],
  },
  'ethics-ethics-35': {
    at: [null, [77, 373, 3, 47], [76, 373, 3, 52], [72, 374, 3, 54], [73, 374, 3, 61], [75, 374, 3, 51], null, [76, 374, 3, 58], [83, 373, 3, 83], null],
    say: [null, 'Hands in his pockets.', 'Surely the first is worse.', 'Same motive, though.', 'Same result too.', null, null, 'Real cases aren’t this tidy.', null, null],
  },
  'epistemology-knowledge-35': {
    at: [null, [72, 377, 3, 60], [72, 376, 3, 60], [72, 389, 3, 72], [72, 388, 3, 72], null, [74, 388, 3, 62], [76, 388, 3, 58], [74, 387, 3, 68], [75, 388, 3, 69], null, null],
    say: [null, null, 'Know the thing.', 'And know what it rules out.', 'Closure, then.', null, null, 'I never checked for paint.', 'And I’d still say I knew.', 'Never a live option?', null, null],
  },
  'political-political-36': {
    at: [null, [76, 373, 3, 58], [74, 372, 3, 62], [74, 372, 3, 74], [76, 372, 3, 58], null, [75, 373, 3, 57], [73, 373, 3, 61], [75, 372, 3, 69], [92, 372, 3, 92], null],
    say: [null, null, 'Nobody asked that question.', 'One guard, every cell.', 'And nobody in the tower.', null, null, 'No case was ever brought.', 'The range shrank.', 'Room to be unfinished.', null],
  },
  'aesthetics-aesthetics-36': {
    at: [null, [72, 388, 3, 48], [71, 388, 3, 53], [76, 387, 3, 58], [71, 387, 3, 65], [76, 387, 3, 64], [76, 388, 3, 64], null, [74, 387, 3, 56], [93, 387, 3, 93], [132, 388, 3, 132], null],
    say: [null, 'It’s all really there.', null, 'No pixel moved.', 'Both true, and they disagree.', 'Light came off the thing.', 'Seeing it, not a record.', null, null, 'You know a painter chose.', 'You forget a photographer did.', null],
  },
  'ethics-ethics-36': {
    at: [null, [75, 374, 3, 63], [74, 372, 3, 62], [72, 375, 3, 60], [73, 375, 3, 61], [72, 374, 3, 60], null, [75, 374, 3, 63], [95, 375, 3, 95], [132, 375, 3, 132], [132, 375, 3, 132], null],
    say: [null, 'Yesterday hasn’t changed.', 'So what did it do?', null, 'Excusing says they couldn’t.', 'Forgiving says they could.', null, 'The resentment was mine.', 'So mine to give up.', null, 'Not easy, and not owed.', null],
  },
  'logic-arguments-36': {
    at: [null, [74, 369, 3, 62], [75, 368, 3, 63], [75, 368, 3, 63], null, [76, 369, 3, 64], [77, 369, 3, 65], [84, 369, 3, 84], null],
    say: [null, null, 'As much as the search.', 'Two squares of a forest.', null, null, 'Only half true, then.', 'A way of ignoring a result.', null],
  },
  'epistemology-knowledge-36': {
    at: [null, [75, 364, 3, 57], [72, 364, 3, 60], [73, 365, 3, 61], [71, 364, 3, 65], [75, 365, 3, 69], [75, 365, 3, 69], [75, 365, 3, 69], null, [75, 365, 3, 63], [73, 365, 3, 67], [72, 365, 3, 66], [94, 362, 3, 94], null],
    say: [null, 'All four the same.', null, 'Everyone had a reason.', 'Better knit, apparently.', 'Nicer feel.', 'It was the position.', 'Invisible from inside.', null, 'They weren’t lying.', 'The reason was hidden.', 'So the gap fills itself.', null, null],
  },
  'metaphysics-being-36': {
    at: [null, [72, 388, 3, 60], [75, 388, 3, 63], [72, 388, 3, 66], [74, 389, 3, 68], null, [72, 388, 3, 54], [73, 388, 3, 61], [98, 381, 3, 98], [140, 384, 3, 140], null],
    say: [null, null, 'Everyone shifts up one.', 'Room 1 is empty.', 'No last room to fall off.', null, null, 'The part equals the whole.', 'The maths is fine.', 'Buildable is another matter.', null],
  },
  'ethics-ethics-37': {
    at: [null, [74, 391, 3, 62], [75, 393, 3, 63], [72, 393, 3, 66], [226, 390, 3, 226], [145, 393, 3, 145], [143, 393, 3, 143], [143, 392, 3, 143], null, [143, 392, 3, 143], [147, 392, 3, 147], null],
    say: [null, 'Four words.', 'There’s the cord.', 'No money, no law.', 'A duty out of a sound.', null, 'She cancelled a plan.', 'And told a friend.', null, null, 'Then who was wronged?', null],
    vis: [4, 153, 393, 3],
  },
  'political-political-37': {
    at: [null, [73, 388, 3, 61], [73, 388, 3, 61], [75, 388, 3, 63], [72, 388, 3, 60], [73, 387, 3, 67], null, [76, 388, 3, 58], [71, 387, 3, 53], [87, 387, 3, 87], [102, 388, 3, 126], null],
    say: [null, 'Across the country.', 'Across a room.', null, 'Having it is one thing.', 'Using it is another.', null, null, 'Both defend the right.', 'They differ on whose.', 'Drawn without announcing it.', null],
  },
  'logic-arguments-37': {
    at: [null, [77, 388, 3, 65], [73, 388, 3, 67], [77, 388, 3, 65], [76, 388, 3, 64], [75, 388, 3, 69], [75, 389, 3, 69], null, [101, 387, 3, 101], [139, 388, 3, 139], null],
    say: [null, 'Shave yourself, he leaves you.', 'Don’t, and he shaves you.', null, 'So who shaves the barber?', 'Collections of collections.', 'Does it contain itself?', null, null, 'Frege added an appendix.', null],
  },
  'metaphysics-being-37': {
    at: [null, [74, 389, 3, 56], [74, 389, 3, 62], [73, 390, 3, 67], [73, 389, 3, 67], [73, 388, 3, 67], [73, 388, 3, 67], [75, 389, 3, 63], null, [83, 386, 3, 101], null],
    say: [null, 'Say what it means, then.', null, 'Struck, therefore breaks.', 'Down comes the hammer.', 'The sorcerer toughens it.', 'Still just as fragile.', null, null, 'True of what never happened.', null],
  },
  'epistemology-knowledge-37': {
    at: [null, [75, 383, 3, 57], [73, 383, 3, 61], [76, 384, 3, 70], [72, 383, 3, 66], null, [75, 383, 3, 63], [75, 383, 3, 63], [75, 383, 3, 63], [83, 383, 3, 95], null],
    say: [null, null, 'He never inspected her.', 'Put the doubts down.', 'And grieved sincerely.', null, 'Same hull. Same cracks.', 'The verdict hasn’t moved.', null, 'It rides on other people.', null],
  },
  'aesthetics-aesthetics-37': {
    at: [null, [73, 376, 3, 67], [72, 376, 3, 66], [73, 377, 3, 67], null, [74, 376, 3, 68], [73, 376, 3, 67], [72, 376, 3, 66], [101, 375, 3, 101], null],
    say: [null, 'Nothing above the line.', null, 'Burn it and it survives.', null, 'Learned note for note.', null, 'Depends what stood behind.', 'Not what the sounds are.', null],
  },
  'ethics-ethics-16': {
    at: [null, [139, 375, 3, 139], [140, 375, 3, 140], null, [143, 377, 3, 143], [142, 376, 3, 142], [145, 375, 3, 145], null],
    say: [null, 'Same hand, same notes.', 'Neither one was free?', null, 'Doing what I want.', null, null, null],
  },
  'aesthetics-aesthetics-17': {
    at: [null, [121, 372, 2, 121], [168, 371, 3, 168], null, [172, 372, 3, 172], [168, 372, 3, 168], [170, 372, 3, 170], [171, 372, 3, 171], null],
    say: [null, 'And I pay for it.', 'The meter doesn’t care.', null, 'Worked through and released.', 'Or the fee for finding out.', null, null, null],
  },
  'ethics-ethics-15': {
    at: [null, [72, 377, 3, 42], [74, 374, 3, 50], [76, 377, 3, 58], [72, 374, 3, 54], [76, 375, 3, 52], null, [72, 376, 3, 42], [72, 376, 3, 42], [72, 381, 3, 48], [75, 375, 3, 51], null],
    say: [null, 'Hold it up and check.', 'Now add a moral word.', 'The beam didn’t move.', 'No extra fact, then.', 'A wince set down in ink.', null, 'Maybe the scale is wrong.', 'A poor scale, then.', null, null, null],
  },
  'aesthetics-aesthetics-14': {
    at: [null, [74, 378, 3, 44], [71, 373, 3, 53], [75, 373, 3, 63], [71, 373, 3, 59], [75, 374, 3, 57], null, [74, 363, 3, 50], [75, 373, 3, 57], [76, 374, 3, 52], null],
    say: [null, 'Nothing wrong with it.', 'One tastes iron.', 'Not the same complaint.', 'Taste really does differ.', 'But not all equally good.', null, 'A key at the bottom.', null, null, null],
  },
  'ethics-ethics-14': {
    at: [null, null, null, null, null, null, null, null, null, null],
    say: [null, 'So is everyone else’s.', 'That’s the whole problem.', 'Everyone else has it too.', 'Part of mine into a wall.', 'There’s a door in it.', null, null, null, null],
    vis: [7, 287, 393, 3],
  },
  'aesthetics-aesthetics-15': {
    at: [null, [75, 383, 3, 45], [77, 383, 3, 47], [72, 384, 3, 48], [76, 384, 3, 52], [73, 384, 3, 55], [72, 384, 3, 54], null, [72, 384, 3, 48], [74, 384, 3, 44], [74, 383, 3, 44], [73, 383, 3, 43], null],
    say: [null, 'Which one is beauty.', 'Strip away every stake.', 'Then that was beauty.', 'To own it.', 'Or sell it.', 'Or be seen beside it.', null, null, 'The rose didn’t change.', 'It’s aimed at me.', null, null],
  },
  'epistemology-knowledge-17': {
    at: [null, [73, 388, 3, 49], [74, 388, 3, 50], [75, 388, 3, 57], [76, 389, 3, 58], null, [77, 388, 3, 47], [73, 390, 3, 55], [71, 388, 3, 53], null],
    say: [null, 'Nobody throws it away.', 'Patch, and patch again.', 'Not testing everything.', 'A paradigm, he called it.', null, 'Then it all goes at once.', null, null, null],
  },
  'logic-arguments-13': {
    at: [null, [324, 376, 3, 348], [324, 378, 3, 342], [326, 376, 3, 344], null, [326, 376, 3, 356], [326, 375, 3, 356], [325, 375, 3, 349], null],
    say: [null, 'Nobody argued for that.', 'Every gap is a jump.', 'The steps looked fine.', null, 'Some slopes are real, then.', null, null, null],
  },
  'logic-arguments-14': {
    at: [null, [73, 382, 2, 43], [71, 382, 1, 47], [74, 383, 1, 50], null, [72, 383, 1, 42], null, null, null, null],
    say: [null, 'Both sound right.', 'That can’t be right.', 'The form isn’t the fault.', null, null, 'Two meanings, one word.', 'It never joined.', null, null],
  },
  'epistemology-knowledge-15': {
    at: [null, [73, 383, 3, 43], [72, 382, 1, 54], [77, 382, 1, 59], [73, 382, 1, 55], [73, 382, 1, 55], null, [75, 382, 2, 51], [75, 382, 1, 51], [71, 382, 1, 53], [75, 382, 1, 51], null],
    say: [null, 'Or only unpack a word.', 'Bachelors are unmarried.', 'The fourth should be empty.', 'Look, and learn nothing new.', 'Learn something, and look.', null, 'Seven plus five.', 'I ran no experiment.', null, null, null],
  },
  'logic-arguments-15': {
    at: [null, [73, 387, 3, 43], [71, 387, 3, 47], [73, 384, 3, 49], null, [72, 387, 3, 48], [75, 383, 3, 51], [76, 384, 3, 52], null],
    say: [null, 'Both true, though.', 'Two people. A nation.', 'I was there, so I know.', null, 'Big enough, and fair.', null, null, null],
  },
  'epistemology-knowledge-16': {
    at: [null, null, [75, 383, 3, 57], [76, 384, 3, 58], null, [76, 384, 3, 58], [77, 382, 3, 53], [74, 383, 3, 50], null],
    say: [null, 'Two of them are narrow.', 'The third allows everything.', 'Usually said as a boast.', null, 'One narrow bar survived.', null, null, null],
  },
  'political-political-18': {
    at: [null, [71, 370, 3, 53], [76, 370, 3, 58], [73, 370, 3, 55], null, [74, 370, 3, 62], [71, 383, 3, 59], [74, 369, 3, 56], null],
    say: [null, 'One crosses the city.', 'The other gets nowhere.', 'The resource was equal.', null, 'Measure what they can do.', null, null, null],
  },
  'metaphysics-being-16': {
    at: [null, [73, 394, 1, 49], [75, 365, 3, 51], [75, 365, 3, 57], [76, 366, 3, 58], null, [71, 365, 3, 53], [76, 365, 3, 52], [76, 365, 3, 52], null],
    say: [null, 'One is behind it.', 'The other is dragged.', 'A desire about a desire.', 'Views about what I want.', null, 'Whether the man is behind it.', null, null, null],
  },
  'metaphysics-being-14': {
    at: [null, [76, 373, 3, 52], [73, 372, 3, 55], [75, 372, 3, 57], [75, 372, 3, 57], null, [71, 372, 3, 47], [72, 373, 3, 48], [71, 371, 3, 53], [72, 372, 3, 54], null],
    say: [null, 'Two rows fill completely.', 'Two come out patchy.', 'It couldn’t be otherwise.', 'It just happens here.', null, 'One I could work out.', 'The other took a lab.', null, null, null],
  },
  'metaphysics-being-17': {
    at: [null, [74, 374, 3, 44], [77, 375, 3, 47], [74, 375, 3, 50], null, [72, 375, 3, 48], [193, 375, 3, 193], [200, 375, 3, 200], null],
    say: [null, 'The wall is complete.', 'Never seen any.', 'Something arrives.', null, 'Why is there anything it’s like?', null, null, null],
  },
  'political-political-16': {
    at: [null, [72, 381, 3, 54], [74, 381, 3, 62], [74, 380, 3, 62], [76, 381, 3, 58], null, [74, 381, 3, 56], [74, 381, 3, 56], [76, 380, 3, 58], null],
    say: [null, 'Four cords.', 'The line sets the pace.', 'Two cords gone.', 'And the other two follow.', null, 'Not about the wage.', null, null, null],
  },
  'political-political-17': {
    at: [null, [76, 363, 3, 58], [72, 362, 3, 60], null, [73, 362, 3, 61], [75, 375, 3, 63], [74, 377, 3, 62], null],
    say: [null, 'His row is empty.', 'He’s right about that.', null, 'Stop asking about signatures.', null, null, null],
  },
  'logic-arguments-16': {
    at: [null, [75, 314, 3, 69], [147, 313, 3, 111], [150, 313, 3, 150], [152, 313, 3, 152], null, [152, 314, 3, 152], [149, 314, 3, 149], null, [218, 314, 3, 218], null],
    say: [null, 'Five out of five.', 'Nobody believes that.', 'But we all do it.', 'Before isn’t because.', null, null, 'Sun’s up anyway.', null, null, null],
    vis: [8, 146, 313, 3],
  },
  'logic-arguments-17': {
    at: [null, [210, 362, 3, 210], [209, 363, 3, 209], [190, 363, 3, 160], [191, 364, 3, 119], [187, 364, 3, 121], null, [188, 363, 3, 122], [237, 363, 3, 237], [236, 363, 3, 236], null],
    say: [null, 'One prints its reasons.', 'The other just asserts.', 'He is dishonest, though.', 'That felt like winning.', 'It touched no reason.', null, null, 'One had parts. One didn’t.', null, null],
    vis: [8, 328, 361, 3],
  },
  'logic-arguments-18': {
    at: [null, [204, 365, 3, 204], null, [113, 367, 3, 113], [78, 380, 3, 114], [76, 380, 3, 118], [124, 367, 3, 124], null, [296, 378, 1, 272], null],
    say: [null, 'Everyone says so.', null, 'Is the water safe?', 'The shaft has a hole.', null, 'Somebody tested it.', null, null, null],
  },
  'ethics-ethics-19': {
    at: [null, [209, 320, 3, 209], [201, 318, 3, 159], [202, 318, 3, 118], null, [200, 309, 2, 122], [197, 309, 2, 125], null, null, null],
    say: [null, 'Somebody else signed.', 'Not how risky.', 'Who else is in it.', null, 'Only one was free.', null, 'Expensive at the end.', null, null],
  },
  'ethics-ethics-17': {
    at: [null, [204, 393, 1, 204], [206, 393, 3, 206], [207, 395, 1, 207], [162, 394, 1, 162], [122, 394, 1, 122], null, [121, 394, 1, 121], [175, 392, 1, 175], [199, 393, 2, 199], null],
    say: [null, 'Even then?', 'He knew how it looks.', 'Not a rule for all.', 'Hand a copy to everybody.', 'Then nobody expects truth.', null, null, 'Surely the friend matters.', null, null],
    vis: [8, 325, 393, 2],
  },
  'epistemology-knowledge-18': {
    at: [null, [213, 341, 3, 213], [283, 376, 2, 217], [160, 341, 3, 160], [115, 341, 3, 115], [118, 341, 3, 118], [112, 343, 3, 112], null, [286, 377, 2, 286], null],
    say: [null, 'Tied to everything.', 'Tied to one memory.', 'Same report, both markers.', 'It shouldn’t move both.', null, 'Proportion to what holds it.', null, null, null],
  },
  'ethics-ethics-20': {
    at: [null, [218, 367, 3, 218], [149, 367, 3, 149], [116, 367, 3, 116], [119, 368, 3, 119], [121, 368, 3, 121], null, [279, 368, 3, 279], null],
    say: [null, 'Two hundred years out.', 'Some of that is fair.', 'A rate on the date itself.', null, 'Nobody chose their year.', null, null, null],
  },
  'epistemology-knowledge-19': {
    at: [null, [212, 371, 2, 212], [153, 371, 2, 153], [122, 371, 2, 122], [122, 371, 2, 122], null, [121, 371, 2, 121], [210, 368, 2, 210], [277, 371, 2, 277], null],
    say: [null, 'Cut to fit one door.', 'A heart doctor on diet.', 'The credentials are real.', 'Just the wrong door.', null, null, 'Both qualified. Opposite.', null, null],
  },
  'metaphysics-being-18': {
    at: [null, [169, 385, 2, 211], [166, 386, 3, 166], [124, 385, 2, 124], [123, 385, 2, 123], [122, 385, 2, 122], [123, 385, 2, 123], null, [168, 386, 2, 276], null],
    say: [null, 'Point at the apple. Easy.', 'Not three apples.', 'Not the chalk mark.', 'Prime before anyone counted.', null, 'So where does it live?', null, null, null],
  },
  'epistemology-knowledge-20': {
    at: [null, [252, 392, 2, 210], [212, 394, 1, 212], [168, 392, 1, 168], [119, 339, 3, 119], [118, 395, 1, 118], [119, 339, 3, 119], null, [249, 394, 2, 243], [252, 393, 1, 186], null],
    say: [null, 'Three more. Better.', 'Right to climb.', 'All the same post.', 'Nobody retracted.', 'It was never four.', null, null, 'Built to show me my own.', null, null],
    vis: [8, 327, 393, 3],
  },
  'metaphysics-being-19': {
    at: [null, [210, 347, 3, 210], [210, 371, 3, 210], [165, 371, 1, 165], [124, 371, 3, 124], null, [124, 367, 3, 124], [124, 366, 3, 124], null, null],
    say: [null, 'Still an apple.', 'And still.', 'That was the last plank.', 'Something underneath?', null, null, 'Then which is which?', null, null],
  },
  'metaphysics-being-20': {
    at: [null, [209, 384, 3, 209], [211, 384, 3, 211], [165, 383, 3, 165], [118, 383, 3, 118], [118, 384, 3, 118], [119, 384, 3, 119], null, [278, 384, 3, 278], [278, 383, 3, 278], [279, 383, 3, 279], null],
    say: [null, 'Thousands of them.', 'Count the minds.', 'Most are in a machine.', 'Nobody aimed it.', 'Where the minds are.', null, null, 'Two say it never gets built.', 'Watch it shrink.', null, null],
  },
  'aesthetics-aesthetics-18': {
    at: [null, [209, 395, 3, 209], [165, 393, 3, 165], [125, 393, 3, 125], [123, 393, 3, 123], null, [243, 393, 3, 243], [177, 384, 3, 177], null],
    say: [null, 'Same slope. Same numbers.', 'It moves the way sadness does.', 'Nobody is inside the notes.', null, null, 'So why pay to sit in it?', null, null],
    vis: [6, 329, 393, 3],
  },
  'aesthetics-aesthetics-20': {
    at: [null, null, null, null, null, null, null, null, null, null],
    say: [null, 'A textbook is faster.', 'A camera does that.', 'Wallpaper is cheaper.', 'Nothing came for the fourth.', null, null, 'Replaceable, and still worth it.', null, null],
  },
  'aesthetics-aesthetics-21': {
    at: [null, [215, 382, 3, 215], [167, 383, 3, 167], [121, 382, 3, 121], [118, 382, 3, 118], [117, 382, 3, 117], null, [249, 382, 3, 249], [201, 376, 3, 183], null],
    say: [null, 'All of it burning.', 'Two of them came back.', 'No text to print it from.', 'The object was the work.', null, null, 'Photography ruins the line.', null, null],
    vis: [7, 327, 385, 3],
  },
  'political-political-19': {
    at: [null, [205, 379, 3, 205], [164, 380, 3, 164], [122, 380, 3, 122], [122, 380, 3, 122], null, [204, 379, 3, 204], [277, 378, 3, 277], null],
    say: [null, 'Same price throughout.', 'But the feeling drops.', 'Only the distance changed.', null, null, 'Always one more.', null, null],
  },
  'political-political-20': {
    at: [null, null, null, null, null, null, null, [211, 309, 3, 283], [212, 311, 3, 278], null],
    say: [null, 'Neither will budge.', 'The normal result?', 'The law lands on both.', 'A reason they could weigh.', null, null, 'The shelf is very small.', null, null],
  },
  'political-political-21': {
    at: [null, null, null, [124, 380, 1, 124], null, null, null, [280, 379, 1, 280], null, null, null],
    say: [null, 'Agreed by staying?', 'Somebody governs that too.', 'And the next.', 'Nowhere left to stand.', null, null, 'Not a call to riot.', 'Just never earned.', null, null],
  },
  'aesthetics-aesthetics-22': {
    at: [null, [211, 386, 3, 211], [211, 385, 2, 211], [152, 384, 3, 152], [124, 385, 3, 124], [123, 385, 3, 123], [127, 386, 3, 127], null, [155, 385, 3, 155], [169, 385, 3, 169], null],
    say: [null, 'The heart goes up.', 'I believe none of it.', 'All three seem true.', 'One of them has to go.', null, 'Playing a game, then.', null, 'Imagining is enough.', null, null],
    vis: [8, 156, 393, 3],
  },
  'aesthetics-aesthetics-24': {
    at: [null, [209, 377, 3, 209], [163, 375, 3, 163], [122, 377, 3, 122], [122, 377, 3, 122], null, [205, 375, 3, 205], [276, 377, 3, 276], null],
    say: [null, 'Everywhere at once.', 'The aura, he called it.', null, 'A film has no original.', null, 'It reaches everybody now.', null, null],
  },
  'aesthetics-aesthetics-23': {
    at: [null, [207, 351, 3, 207], [212, 379, 1, 212], [164, 378, 1, 164], [123, 351, 3, 123], [123, 351, 3, 123], [124, 350, 3, 124], null, [202, 353, 3, 202], [278, 350, 3, 278], null],
    say: [null, 'Say what it was about.', 'A mood, easily.', 'The title did that.', null, 'Not about anything.', 'A shape made of tones.', null, 'It copies the wanting.', null, null],
  },
  'epistemology-knowledge-23': {
    at: [null, [206, 376, 3, 206], [164, 376, 3, 164], [150, 376, 3, 120], [150, 378, 3, 120], null, [245, 369, 3, 245], [203, 366, 3, 203], null],
    say: [null, 'Wider isn’t looser.', 'The mouth hasn’t moved.', null, 'Then the mesh does nothing.', null, 'Two settings at once.', null, null],
    vis: [6, 324, 393, 3],
  },
  'epistemology-knowledge-24': {
    at: [null, [217, 368, 2, 211], null, [219, 367, 2, 159], [218, 368, 2, 116], null, [220, 371, 3, 118], [219, 366, 2, 201], [278, 373, 2, 278], null],
    say: [null, 'Not how clever. How sure.', null, 'That bar is longer.', null, null, 'It runs both ways.', 'Confidence isn’t knowledge.', null, null],
  },
  'epistemology-knowledge-22': {
    at: [null, [209, 385, 2, 209], [211, 385, 3, 211], [163, 384, 2, 163], [123, 385, 2, 123], [123, 385, 2, 123], [124, 385, 2, 124], null, [208, 383, 3, 208], [279, 385, 3, 279], null],
    say: [null, 'One just guesses.', 'Nothing to choose today.', 'One is a road.', 'The other is stepping stones.', null, 'Tie them down, then.', null, 'It’s in every other day.', null, null],
  },
  'ethics-ethics-21': {
    at: [null, [206, 363, 3, 206], [165, 361, 3, 165], [124, 362, 3, 124], [125, 362, 3, 125], null, [208, 364, 3, 208], null, [180, 362, 3, 180], null],
    say: [null, 'Two arrows. One aimed.', 'So the aim is the thing.', null, 'Ah. Now it is the means.', null, 'Through it, or past it.', null, null, null],
    vis: [7, 187, 361, 3],
  },
  'ethics-ethics-22': {
    at: [null, [210, 377, 3, 210], [165, 377, 3, 165], [119, 377, 3, 119], [118, 376, 3, 118], [113, 376, 3, 113], null, [205, 375, 3, 205], [280, 377, 3, 280], null],
    say: [null, 'Indistinguishable, though.', 'I’d say no as well.', null, 'The other four aren’t off.', 'Never plugged in.', null, 'So pleasure isn’t all of it.', null, null],
  },
  'ethics-ethics-24': {
    at: [null, [215, 379, 3, 215], [216, 378, 3, 216], [163, 378, 3, 163], [118, 378, 3, 118], [125, 379, 3, 125], null, [215, 381, 3, 215], [284, 379, 3, 284], null],
    say: [null, 'Stop him. Stop others.', 'Mend him. Or repay him.', 'Ninety, and harmless.', 'Three have nothing to hold.', null, null, 'The same trick backwards.', null, null],
  },
  'logic-arguments-19': {
    at: [null, [211, 385, 3, 211], [151, 385, 3, 151], [122, 386, 3, 122], [123, 385, 3, 123], [211, 383, 3, 211], null, [169, 385, 3, 169], null],
    say: [null, 'The vowel and the even.', 'A consonant is allowed.', null, 'A vowel behind the seven.', 'Only a no can test it.', null, null, null],
    vis: [6, 157, 393, 3],
  },
  'logic-arguments-20': {
    at: [null, [257, 300, 3, 209], [209, 368, 1, 209], [258, 300, 3, 162], null, null, null, null, [278, 300, 3, 278], null],
    say: [null, 'Same claim, less support.', 'One leg left.', 'Not a lie. Just the weakest.', null, 'The real one never moved.', 'Take on the strongest.', null, null, null],
  },
  'logic-arguments-21': {
    at: [null, [206, 395, 3, 206], [206, 395, 3, 206], [164, 394, 3, 164], [122, 394, 3, 122], [123, 394, 3, 123], [114, 394, 3, 114], null, [186, 393, 3, 186], null],
    say: [null, 'Take it away and see.', 'Now switch it on alone.', 'A spark would do as well.', null, 'Tuesday fails both.', 'Four boxes, not two.', null, null, null],
    vis: [7, 327, 393, 3],
  },
  'metaphysics-being-21': {
    at: [null, [213, 376, 2, 213], [214, 376, 3, 214], [215, 377, 2, 215], [164, 376, 2, 164], [118, 377, 2, 118], [118, 377, 2, 118], null, [165, 375, 2, 165], [207, 376, 2, 207], null],
    say: [null, 'What is there, then.', 'Only this instant.', 'Yesterday is nowhere.', 'The future isn’t written.', null, 'Now is just where I am.', null, 'Relativity leans this way.', null, null],
    vis: [8, 71, 393, 3],
  },
  'metaphysics-being-22': {
    at: [null, [209, 356, 3, 209], [212, 356, 3, 212], [166, 337, 3, 166], [124, 335, 3, 124], [124, 336, 3, 124], null, [213, 355, 3, 207], [282, 358, 3, 282], null],
    say: [null, 'Same world, same laws.', 'Same way each time.', 'Never a live option.', null, 'Not about the replay.', null, 'Then nothing decided it.', null, null],
  },
  'metaphysics-being-23': {
    at: [null, [215, 372, 3, 215], [152, 372, 3, 152], [117, 372, 3, 117], [118, 372, 3, 118], [119, 372, 3, 119], null, [283, 372, 3, 283], [283, 372, 3, 283], [281, 372, 3, 281], null],
    say: [null, 'No original plank left.', 'He built a second one.', null, 'Use points left.', 'Wood points right.', null, 'When do parts make a thing?', 'A pile isn’t a ship.', null, null],
  },
  'political-political-22': {
    at: [null, [209, 394, 1, 209], [212, 394, 1, 212], [165, 394, 3, 165], [124, 394, 3, 124], [126, 394, 3, 126], null, [165, 393, 3, 243], [165, 393, 3, 189], null],
    say: [null, 'Her day is her own.', 'But he holds the switch.', 'Nothing she could do.', null, 'Interfering, or able to.', null, 'Not manners. Courts.', null, null],
  },
  'political-political-24': {
    at: [null, [211, 375, 1, 211], [165, 376, 2, 165], [122, 375, 1, 122], [122, 375, 1, 122], null, [202, 373, 1, 202], [293, 375, 3, 275], null],
    say: [null, 'Not a courtesy on top.', 'Five generations later.', null, 'Trapped inside a picture.', null, 'Identical, or recognised.', null, null],
  },
  'political-political-23': {
    at: [null, [209, 372, 3, 209], [211, 372, 3, 211], [175, 373, 3, 163], [172, 373, 3, 118], [170, 373, 3, 116], null, [242, 372, 3, 242], [208, 372, 3, 190], null],
    say: [null, 'That one I never chose.', 'Forget all of it, then.', 'A chooser is still in there.', null, 'Nothing neutral underneath.', null, 'Chosen from nowhere.', null, null],
    vis: [7, 326, 393, 3],
  },
  'logic-arguments-39': {
    at: [[74, 388, 3, 62], [73, 388, 3, 61], [71, 387, 3, 59], [76, 367, 3, 64], [74, 388, 3, 68], [88, 388, 3, 88], [81, 384, 2, 81], [71, 383, 3, 77], null],
    say: ['Some sentences bite themselves.', 'Three claims, one test.', null, 'It is asking for it.', 'There goes the plank.', 'No evidence needed at all.', 'Harsh. Also correct.', null, null],
    vis: [6, 73, 393, 3],
  },
  'epistemology-knowledge-39': {
    at: [[73, 347, 3, 55], [73, 348, 3, 61], [75, 345, 3, 63], [72, 348, 3, 60], [74, 348, 3, 62], [76, 345, 3, 88], [76, 348, 3, 112], [74, 348, 3, 98], null],
    say: ['Two findings, one verdict.', 'Every row holds together.', 'Now count downward.', null, 'Nobody made a mistake.', 'Reasons, or the verdict?', 'The many, together.', null, null],
  },
  'logic-arguments-38': {
    at: [[71, 370, 3, 65], [72, 374, 3, 66], [74, 373, 3, 68], [74, 373, 3, 68], [71, 373, 3, 65], [72, 365, 3, 72], [72, 373, 3, 84], [75, 377, 3, 111], null],
    say: ['Three steps. Watch them.', 'Greater than anything else.', 'He changed one word.', null, 'Identical. I checked twice.', 'Broken before the island.', 'Rude, and fair.', null, null],
  },
  'ethics-ethics-38': {
    at: [[74, 347, 3, 50], [74, 347, 3, 56], [76, 348, 3, 58], [76, 349, 3, 58], [75, 349, 3, 57], [73, 351, 3, 55], [76, 349, 3, 76], [91, 344, 3, 103], null],
    say: ['Both children. Only one me.', 'The scale never asks whose.', 'Three reasons to lean.', null, 'Even your own mother?', 'The tie was the reason.', 'One thought too many.', null, null],
  },
  'epistemology-knowledge-38': {
    at: [[76, 391, 3, 58], [77, 392, 3, 59], [73, 394, 3, 55], [73, 393, 3, 55], [72, 394, 3, 60], [74, 394, 3, 56], [83, 394, 3, 83], [111, 394, 3, 111], null],
    say: ['Two of three were right.', 'The hollow ones nearly happened.', 'A hit and an aim look alike.', null, 'Nearest cases, not all cases.', 'A stopped clock is right once.', 'Tie it down, said Plato.', null, null],
  },
  'ethics-ethics-39': {
    at: [[73, 348, 3, 55], [75, 348, 3, 57], [77, 348, 3, 59], [76, 348, 3, 58], [75, 348, 3, 57], [73, 345, 3, 61], [79, 348, 3, 79], [109, 348, 3, 109], null],
    say: ['One more. Every time.', 'Judge, intend, act.', null, 'Stuck on the last step.', 'So nobody ever slips?', 'Knowledge, but asleep.', 'Ovid knew the feeling.', null, null],
  },
  'metaphysics-being-39': {
    at: [[75, 388, 1, 57], [72, 389, 1, 60], [77, 390, 1, 65], [76, 389, 3, 64], [75, 369, 3, 62], [87, 386, 3, 87], [96, 384, 2, 192], [95, 385, 2, 185], null],
    say: ['Nobody is a lot of people.', 'Not one of them watered it.', 'Every answer is the same.', null, 'The king did not water it.', 'Hume in a single line.', 'If the first had not been.', null, null],
    vis: [6, 296, 353, 3],
  },
  'metaphysics-being-38': {
    at: [[73, 347, 3, 55], [76, 348, 3, 58], [73, 348, 3, 55], [73, 349, 3, 55], [73, 349, 3, 61], [75, 356, 3, 57], [81, 357, 3, 81], [83, 348, 3, 107], null],
    say: ['Same clay all week.', 'A vase on Tuesday only.', 'Two bars, two lengths.', null, 'A fact about dates.', 'Two names, or two things.', 'Kripke settles the form.', null, null],
  },
  'aesthetics-aesthetics-38': {
    at: [[74, 385, 3, 56], [72, 385, 2, 60], [75, 388, 3, 57], [76, 388, 3, 52], [72, 388, 3, 54], [73, 387, 2, 55], [80, 388, 3, 80], [106, 388, 3, 106], null],
    say: ['Seen it. Still gripped.', 'Knowing is flat. Feeling is not.', 'Three claims, one too many.', null, 'Athens knew the endings.', 'Not forgetting, then.', 'Poetic faith. Good phrase.', null, null],
  },
  'political-political-38': {
    at: [[72, 387, 2, 54], [75, 387, 3, 57], [72, 388, 1, 54], [72, 388, 1, 54], [71, 388, 1, 59], [76, 388, 1, 58], [82, 389, 1, 82], [109, 389, 2, 109], null],
    say: ['A vote nobody mentioned.', 'How much slack?', 'Three things he might owe.', null, 'He told them to their faces.', 'And they threw him out.', 'He owes you his judgement.', null, null],
  },
  'aesthetics-aesthetics-39': {
    at: [[74, 384, 3, 56], [75, 384, 3, 57], [73, 385, 3, 61], [75, 385, 3, 63], [73, 385, 3, 61], [75, 384, 3, 57], [82, 385, 3, 82], [108, 384, 1, 108], null],
    say: ['Same wood, same hands.', 'Look at the route instead.', 'And here is what came out.', null, 'The line is in the making.', 'Kant said it first.', 'Free, or mercenary.', null, null],
  },
  'political-political-39': {
    at: [[73, 369, 3, 55], [72, 365, 3, 60], [75, 393, 1, 63], [74, 353, 3, 62], [75, 353, 3, 57], [76, 309, 1, 52], [75, 362, 3, 81], [111, 349, 3, 111], null],
    say: ['One of the forty.', 'And now it binds me.', 'Four offers. Read them.', null, 'Comply, or agree?', 'Locke on the count.', 'The greater force carries it.', null, null],
  },
};
