// GENERATED by scripts/make-mentions.mjs — do not hand-edit.
//
// Which philosophers each lesson is about, and how strongly:
//   3 — QUOTED. The lesson carries their words (a quote card's philosopherId,
//       or a cinematic quote beat's author). It is built on them.
//   1 — NAMED. Their name appears in the lesson's text or script. Discussed,
//       which is worth less than being the subject.
//
// This replaces "every philosopher in the branch gets credit for every lesson in
// it", under which one ethics lesson moved all forty ethics thinkers up together.
//
// Regenerate after writing or editing a lesson:  npm run make:mentions

export type Mention = readonly [philosopherId: string, weight: number];

export const MENTION_QUOTED = 3;
export const MENTION_NAMED = 1;

export const LESSON_MENTIONS: Record<string, readonly Mention[]> = {
  'business-foundations-4': [['walter-benjamin', 1]],
  'economics-foundations-4': [['adam-smith', 3]],
  'personal-growth-foundations-2': [['william-james', 3]],
  'personal-growth-foundations-3': [['seneca', 3]],
  'philosophy-foundations-1': [['socrates', 3], ['plato', 1]],
  'philosophy-foundations-2': [['john-stuart-mill', 3]],
  'philosophy-foundations-3': [['jeremy-bentham', 3]],
  'philosophy-foundations-4': [['bertrand-russell', 3]],
  'philosophy-foundations-5': [['john-locke', 3]],
  'philosophy-foundations-6': [['arthur-schopenhauer', 3]],
  'psychology-foundations-1': [['william-james', 3]],
  'psychology-foundations-3': [['william-james', 3]],
  'science-foundations-5': [['karl-popper', 3]],
};

/** The philosophers a finished lesson should credit. Empty for a lesson naming none. */
export function mentionsFor(lessonId: string): readonly Mention[] {
  return LESSON_MENTIONS[lessonId] ?? [];
}
