// GENERATED by scripts/make-visitor.mjs — do not edit by hand.
//
// The second figure who walks into a lesson: which beat he arrives on, where he
// stands, which edge he comes from, and which way he turns once he is there.
//
// Only lessons whose graded beat has two sides (a `poll` of named positions, or
// a `cards` deck of two) and which have measured floor space for him on BOTH the
// entrance beat and the question beat. See scripts/make-visitor.mjs, and group AA
// of docs/LESSON_RULES.md.

export interface VisitorCue {
  /** The beat he walks on. He is off-stage before it and standing after it. */
  enter: number;
  /** Where he stands, in stage units. */
  x: number;
  /** The off-stage x he walks in from. */
  from: number;
  /** Which way he faces once he has arrived: +1 right, −1 left. */
  dir: number;
  /**
   * Present when the lead has to be turned round to face him (N21): the side the
   * lead turns to, +1 right, −1 left. Only for a lead who never walks after he
   * arrives, so the turn cannot fight a walk.
   */
  turn?: number;
}

export const VISITOR: Record<string, VisitorCue> = {
};
