// GENERATED by `npm run make:chair` — do not edit by hand.
//
// Which lessons play the lawn-chair routine or the standing mug, and on which beats
// (chairPlay.ts). A row is one QUAD per part, in playing order: `[beat, kind,
// crossedIn, mugIn, …]`. Kinds: CH_SETUP 10, CH_PUTAWAY 11, CH_MUG_STAND 12, and the
// seated parts SEAT_CROSS 1 · SEAT_MUG 2 · SEAT_DRUM 3 · SEAT_SIP 4 · SEAT_REST 5.
export const CHAIR_PLANS: Record<string, readonly number[]> = {
};
