// GENERATED by scripts/make-names.mjs — do not hand-edit.
//
// Every philosopher name that appears in a lesson's NARRATION, with the id it
// resolves to. The deck draws these in their era's colour and opens a one-line
// snapshot when one is tapped (see components/lesson/cinematic/NarrationText).
//
// Narration only — not `explain`, not a control's `reads`. This table decides
// what is DRAWN, so a name that appears somewhere else must not colour a
// paragraph that never mentions them.
//
// The rules for believing a surname live in scripts/make-mentions.mjs and are
// re-used here: unique across all 322, longer than three characters, and not an
// ordinary English word. Regenerate with:  npm run make:names

export type LessonName = readonly [surface: string, philosopherId: string];

/** Longest surface form first — the matcher takes them in order. */
export const LESSON_NAMES: Record<string, readonly LessonName[]> = {
  'aesthetics-aesthetics-1': [['Hume', 'david-hume'], ['Kant', 'immanuel-kant']],
  'aesthetics-aesthetics-14': [['Hume', 'david-hume']],
  'aesthetics-aesthetics-15': [['Kant', 'immanuel-kant']],
  'aesthetics-aesthetics-24': [['Walter Benjamin', 'walter-benjamin'], ['Benjamin', 'walter-benjamin']],
  'aesthetics-aesthetics-3': [['Schopenhauer', 'arthur-schopenhauer'], ['Aristotle', 'aristotle'], ['Plato', 'plato']],
  'aesthetics-aesthetics-35': [['Hobbes', 'thomas-hobbes']],
  'aesthetics-aesthetics-4': [['Plato', 'plato']],
  'aesthetics-aesthetics-5': [['Simone Weil', 'simone-weil'], ['Murdoch', 'iris-murdoch'], ['Weil', 'simone-weil']],
  'aesthetics-aesthetics-6': [['Burke', 'edmund-burke'], ['Kant', 'immanuel-kant']],
  'aesthetics-aesthetics-7': [['Hume', 'david-hume']],
  'epistemology-knowledge-1': [['Socrates', 'socrates'], ['Plato', 'plato']],
  'epistemology-knowledge-15': [['Kant', 'immanuel-kant']],
  'epistemology-knowledge-17': [['Kuhn', 'thomas-kuhn']],
  'epistemology-knowledge-2': [['Ryle', 'gilbert-ryle']],
  'epistemology-knowledge-22': [['Plato', 'plato']],
  'epistemology-knowledge-24': [['Moore', 'ge-moore']],
  'epistemology-knowledge-3': [['Descartes', 'rene-descartes']],
  'epistemology-knowledge-4': [['Descartes', 'rene-descartes'], ['Socrates', 'socrates'], ['Leibniz', 'gottfried-leibniz'], ['Locke', 'john-locke'], ['Plato', 'plato'], ['Kant', 'immanuel-kant']],
  'epistemology-knowledge-5': [['Francis Bacon', 'francis-bacon'], ['Aristotle', 'aristotle'], ['Bacon', 'francis-bacon'], ['Plato', 'plato']],
  'epistemology-knowledge-6': [['Descartes', 'rene-descartes']],
  'epistemology-knowledge-7': [['Hume', 'david-hume']],
  'ethics-ethics-1': [['Aristotle', 'aristotle'], ['Kant', 'immanuel-kant']],
  'ethics-ethics-10': [['Peter Singer', 'peter-singer'], ['Singer', 'peter-singer']],
  'ethics-ethics-11': [['John Stuart Mill', 'john-stuart-mill'], ['Jeremy Bentham', 'jeremy-bentham'], ['Socrates', 'socrates'], ['Bentham', 'jeremy-bentham'], ['Mill', 'john-stuart-mill']],
  'ethics-ethics-12': [['Kant', 'immanuel-kant']],
  'ethics-ethics-13': [['Aristotle', 'aristotle']],
  'ethics-ethics-14': [['Locke', 'john-locke']],
  'ethics-ethics-16': [['Hume', 'david-hume']],
  'ethics-ethics-17': [['Kant', 'immanuel-kant']],
  'ethics-ethics-19': [['Mill', 'john-stuart-mill']],
  'ethics-ethics-2': [['Aristotle', 'aristotle'], ['Kant', 'immanuel-kant'], ['Mill', 'john-stuart-mill']],
  'ethics-ethics-21': [['Aquinas', 'thomas-aquinas']],
  'ethics-ethics-23': [['Singer', 'peter-singer']],
  'ethics-ethics-3': [['John Stuart Mill', 'john-stuart-mill'], ['Immanuel Kant', 'immanuel-kant'], ['Aristotle', 'aristotle'], ['Kant', 'immanuel-kant'], ['Mill', 'john-stuart-mill']],
  'ethics-ethics-33': [['Peter Singer', 'peter-singer'], ['Singer', 'peter-singer']],
  'ethics-ethics-34': [['Derek Parfit', 'derek-parfit'], ['Parfit', 'derek-parfit']],
  'ethics-ethics-5': [['Karl Jaspers', 'karl-jaspers'], ['Confucius', 'confucius'], ['Socrates', 'socrates'], ['Jaspers', 'karl-jaspers']],
  'ethics-ethics-6': [['Thomson', 'judith-jarvis-thomson'], ['Foot', 'philippa-foot']],
  'ethics-ethics-7': [['Bernard Williams', 'bernard-williams'], ['Thomas Nagel', 'thomas-nagel'], ['Williams', 'bernard-williams'], ['Nagel', 'thomas-nagel']],
  'ethics-ethics-8': [['Carol Gilligan', 'carol-gilligan'], ['Nel Noddings', 'nel-noddings'], ['Gilligan', 'carol-gilligan'], ['Noddings', 'nel-noddings']],
  'ethics-ethics-9': [['Sartre', 'jean-paul-sartre']],
  'logic-arguments-22': [['Aristotle', 'aristotle']],
  'logic-arguments-37': [['Russell', 'bertrand-russell'], ['Frege', 'gottlob-frege']],
  'logic-arguments-4': [['Socrates', 'socrates']],
  'metaphysics-being-1': [['Parmenides', 'parmenides'], ['Leibniz', 'gottfried-leibniz']],
  'metaphysics-being-10': [['Aristotle', 'aristotle'], ['Plato', 'plato']],
  'metaphysics-being-11': [['Locke', 'john-locke']],
  'metaphysics-being-12': [['Descartes', 'rene-descartes'], ['Hume', 'david-hume']],
  'metaphysics-being-15': [['Hume', 'david-hume']],
  'metaphysics-being-16': [['Frankfurt', 'harry-frankfurt']],
  'metaphysics-being-18': [['Plato', 'plato']],
  'metaphysics-being-19': [['Locke', 'john-locke']],
  'metaphysics-being-2': [['Parmenides', 'parmenides'], ['Leibniz', 'gottfried-leibniz']],
  'metaphysics-being-3': [['Heraclitus', 'heraclitus'], ['Plato', 'plato']],
  'metaphysics-being-4': [['Parmenides', 'parmenides'], ['Aristotle', 'aristotle'], ['Elea', 'zeno-of-elea']],
  'metaphysics-being-5': [['Heidegger', 'martin-heidegger'], ['Leibniz', 'gottfried-leibniz']],
  'metaphysics-being-8': [['Harry Frankfurt', 'harry-frankfurt'], ['David Hume', 'david-hume'], ['Frankfurt', 'harry-frankfurt'], ['Hume', 'david-hume']],
  'metaphysics-being-9': [['Descartes', 'rene-descartes']],
  'political-political-1': [['Hobbes', 'thomas-hobbes'], ['Locke', 'john-locke']],
  'political-political-10': [['Nozick', 'robert-nozick'], ['Locke', 'john-locke'], ['Rawls', 'john-rawls']],
  'political-political-11': [['Rousseau', 'jean-jacques-rousseau'], ['Hobbes', 'thomas-hobbes'], ['Locke', 'john-locke']],
  'political-political-12': [['Isaiah Berlin', 'isaiah-berlin'], ['Rousseau', 'jean-jacques-rousseau'], ['Berlin', 'isaiah-berlin']],
  'political-political-13': [['Mill', 'john-stuart-mill']],
  'political-political-14': [['Nozick', 'robert-nozick']],
  'political-political-16': [['Marx', 'karl-marx']],
  'political-political-18': [['Sen', 'amartya-sen']],
  'political-political-20': [['Rawls', 'john-rawls']],
  'political-political-23': [['Rawls', 'john-rawls']],
  'political-political-3': [['Rousseau', 'jean-jacques-rousseau'], ['Hobbes', 'thomas-hobbes'], ['Locke', 'john-locke']],
  'political-political-33': [['Karl Popper', 'karl-popper'], ['Popper', 'karl-popper']],
  'political-political-36': [['Bentham', 'jeremy-bentham']],
  'political-political-37': [['Rawls', 'john-rawls']],
  'political-political-4': [['Berlin', 'isaiah-berlin'], ['Mill', 'john-stuart-mill']],
  'political-political-5': [['Rousseau', 'jean-jacques-rousseau'], ['Hobbes', 'thomas-hobbes'], ['Locke', 'john-locke'], ['Plato', 'plato'], ['Rawls', 'john-rawls'], ['Mill', 'john-stuart-mill']],
  'political-political-6': [['Rawls', 'john-rawls']],
  'political-political-7': [['Mary Wollstonecraft', 'mary-wollstonecraft'], ['Wollstonecraft', 'mary-wollstonecraft'], ['John Locke', 'john-locke'], ['Locke', 'john-locke']],
  'political-political-8': [['Martha Nussbaum', 'martha-nussbaum'], ['Amartya Sen', 'amartya-sen'], ['Nussbaum', 'martha-nussbaum'], ['Sen', 'amartya-sen']],
  'political-political-9': [['Plato', 'plato'], ['Mill', 'john-stuart-mill']],
};
