// GENERATED by scripts/make-names.mjs — do not hand-edit.
//
// Every philosopher name that appears in a lesson's NARRATION, with the id it
// resolves to. The deck draws these in their era's colour and opens a one-line
// snapshot when one is tapped (see components/lesson/cinematic/NarrationText).
//
// Narration only — not `explain`, not a control's `reads`. This table decides
// what is DRAWN, so a name that appears somewhere else must not colour a
// paragraph that never mentions them.
//
// The rules for believing a surname live in scripts/make-mentions.mjs and are
// re-used here: unique across all 322, longer than three characters, and not an
// ordinary English word. Regenerate with:  npm run make:names

export type LessonName = readonly [surface: string, philosopherId: string];

/** Longest surface form first — the matcher takes them in order. */
export const LESSON_NAMES: Record<string, readonly LessonName[]> = {
  'history-caesar-1': [['Miletus', 'thales']],
};
