// GENERATED by scripts/make-wardrobe.mjs — do not edit by hand.
//
// What each lesson's figure is wearing. See components/lesson/cinematic/wardrobe.ts
// for the pieces themselves and for the one rule that governs them (a piece must
// change the SILHOUETTE, because the figure is solid ink with no face).
//
// Each entry is [LEAD, SECOND]. The second is only used by a scene that mounts a
// figure with role="second" (AA4), and it is chosen HERE rather than derived in
// the component because only this script can see the lesson's band.
//
// Neighbours never match, and a lesson carrying a grave word wears nothing louder
// than a mortarboard — N11, one medium over.

export const WARDROBE: Record<string, [string, string]> = {
};
