// GENERATED by scripts/make-thoughts.mjs — the placement. The WORDS are authored.
//
// What the stickman is working out, beat by beat, in a bubble over his head.
//
// ── WHY THIS IS A TABLE AND NOT A FIELD ON THE BEAT ─────────────────────────
//
// The same reason `data/lessonFocus.ts` is one, and it is nothing to do with
// design: `muststamp` hashes every lesson's SCRIPT, so writing a thought into 186
// scripts marks all 186 must-box measurements stale and demands a browser sweep
// of hours to record something the stage never draws from the script. §17 records
// the maxim making exactly that trade and being moved out for it.
//
// The cost is that a rewritten beat can orphan its own thought — J9's stale "the
// trap is B" — so `check:thoughts` re-derives every entry against the beat it
// claims to sit on, and says so when the beat has moved out from under it.
//
// ── `top` IS PER LESSON, `say` IS PER BEAT ──────────────────────────────────
//
// `top` is the stage y of the bubble's TAIL, chosen against the lesson's own BAND
// and the art the beats actually draw. It is per lesson because the band is, and
// because a bubble that moved between beats would read as a second object rather
// than as something coming out of his head.

export interface LessonThoughts {
  /**
   * Per beat: `[x, tailY, discs, headX]`, or null for the beats with nowhere to
   * put a bubble.
   *
   * `x` is the box's centre and `headX` is HIS centre — both absolute stage
   * coordinates, both measured out of `mustBoxes`. They differ when the space
   * directly overhead was taken and the box had to slide; the trail leans back
   * toward `headX` so it still says whose thought it is.
   *
   * ABSOLUTE, not an offset from his live position. The player derives that from
   * the script's `walk` track, a scene need not pass one, and where it was missing
   * the bubble fell back to the middle of the stage and landed across a plate this
   * generator had carefully avoided. `headX` is the union of his boxes across the
   * whole beat, so it already covers wherever he walks during it.
   *
   * `tailY` is the stage y of the smallest disc: the bubble hangs from its tail so
   * a one-line and a two-line thought keep the same distance from his head.
   *
   * GENERATED by `make:thoughts` against the measured art. A bubble never covers
   * a WORD (D31); it is allowed over art, and only when nothing fully clear was
   * within reach.
   */
  at: ([number, number, number, number] | null)[];
  /** One entry per beat: what he is thinking, or null for the beats he is just listening. */
  say: (string | null)[];
  /**
   * The SECOND figure's line as he walks in: `[beat, x, tailY, discs, headX]`.
   *
   * `headX` is where HE stands, so the trail leans to him. Without it the player was
   * handed the box's own x as the head, and a box slid clear of the stage edge hung
   * its discs straight down beside him rather than toward him.
   *
   * Only the 24 lessons where a visitor arrives (AA8), and only on his entrance
   * beat — never on the question itself, because a second figure staking a claim
   * while the reader is still choosing is a hint wearing a hat (group O). What he
   * says is pooled rather than authored, and that is structural: a `poll` lists
   * named positions and a `split` divides one thing in two, so his meaning is
   * fixed by the CONTROL — he disagrees — whatever the lesson is about.
   */
  vis?: [number, number, number, number, number?];
}

export const THOUGHTS: Record<string, LessonThoughts> = {
};
