// GENERATED by scripts/make-wander.mjs. Do not edit by hand.
//
// WHERE THE FIGURE MOVES HIMSELF, BEAT BY BEAT (group AF).
//
// A reader asked for the mascot to stop being *"too stationary"* — to look up and
// down, walk back and forth, and sit on the ground for a while, instead of only
// moving his arms. `components/lesson/cinematic/wander.ts` is the maths and this
// is the choreography: one plan per beat, or null where he may not move.
//
// A plan is flat numbers, because it crosses into a worklet:
//
//   [ lo, hi, kind, at, dur, target, … ]
//
//   lo, hi   how far either side of where the scene stands him he may go, in
//            stage units — measured against the art the beat draws, the second
//            figure, the pen mark and the frames the camera shows.
//   kind     1 step · 2 look · 3 sit · 4 crouch · 5 turn · 6 lean
//   at, dur  seconds from the start of the beat, placed in the line's own pauses
//   target   the value that move arrives at (an offset, ±1, or 0/1)
//
// `npm run check:wander` re-derives every one of them.

export const WANDER_PLANS: Record<string, readonly (readonly number[] | null)[]> = {
};
