// GENERATED by scripts/make-visitor.mjs — do not edit by hand.
//
// The second figure who walks into a lesson: which beat he arrives on, where he
// stands, which edge he comes from, and which way he turns once he is there.
//
// Only lessons whose graded beat has two sides (a `poll` of named positions, or
// a `split` between two) and which have measured floor space for him on BOTH the
// entrance beat and the question beat. See scripts/make-visitor.mjs, and group AA
// of docs/LESSON_RULES.md.

export interface VisitorCue {
  /** The beat he walks on. He is off-stage before it and standing after it. */
  enter: number;
  /** Where he stands, in stage units. */
  x: number;
  /** The off-stage x he walks in from. */
  from: number;
  /** Which way he faces once he has arrived: +1 right, −1 left. */
  dir: number;
}

export const VISITOR: Record<string, VisitorCue> = {
  'political-political-4': { enter: 8, x: 85, from: -60, dir: 1 },
  'ethics-ethics-7': { enter: 10, x: 299, from: 460, dir: -1 },
  'ethics-ethics-31': { enter: 8, x: 49, from: -60, dir: 1 },
  'metaphysics-being-32': { enter: 8, x: 366, from: 460, dir: -1 },
  'metaphysics-being-39': { enter: 6, x: 311, from: 460, dir: -1 },
  'logic-arguments-16': { enter: 8, x: 56, from: -60, dir: 1 },
  'logic-arguments-17': { enter: 8, x: 54, from: -60, dir: 1 },
  'ethics-ethics-17': { enter: 8, x: 49, from: -60, dir: 1 },
  'epistemology-knowledge-20': { enter: 8, x: 56, from: -60, dir: 1 },
  'aesthetics-aesthetics-18': { enter: 6, x: 353, from: 460, dir: -1 },
  'aesthetics-aesthetics-21': { enter: 7, x: 350, from: 460, dir: -1 },
  'logic-arguments-19': { enter: 6, x: 52, from: -60, dir: 1 },
  'logic-arguments-21': { enter: 7, x: 49, from: -60, dir: 1 },
  'ethics-ethics-21': { enter: 7, x: 123, from: -60, dir: 1 },
  'epistemology-knowledge-23': { enter: 6, x: 52, from: -60, dir: 1 },
  'metaphysics-being-21': { enter: 8, x: 350, from: 460, dir: -1 },
  'aesthetics-aesthetics-22': { enter: 8, x: 54, from: -60, dir: 1 },
  'political-political-22': { enter: 7, x: 123, from: -60, dir: 1 },
  'political-political-23': { enter: 7, x: 53, from: -60, dir: 1 },
  'ethics-ethics-37': { enter: 4, x: 166, from: -60, dir: -1 },
  'aesthetics-aesthetics-31': { enter: 6, x: 358, from: 460, dir: -1 },
  'logic-arguments-23': { enter: 8, x: 39, from: -60, dir: 1 },
  'metaphysics-being-13': { enter: 6, x: 304, from: 460, dir: -1 },
  'political-political-13': { enter: 9, x: 46, from: -60, dir: 1 },
  'political-political-15': { enter: 5, x: 343, from: 460, dir: -1 },
  'logic-arguments-25': { enter: 6, x: 47, from: -60, dir: 1 },
  'epistemology-knowledge-2': { enter: 7, x: 46, from: -60, dir: 1 },
  'metaphysics-being-8': { enter: 12, x: 301, from: 460, dir: -1 },
  'political-political-8': { enter: 11, x: 71, from: -60, dir: 1 },
  'ethics-ethics-11': { enter: 6, x: 49, from: -60, dir: 1 },
  'ethics-ethics-14': { enter: 7, x: 155, from: -60, dir: -1 },
  'metaphysics-being-17': { enter: 6, x: 354, from: 460, dir: -1 },
  'logic-arguments-27': { enter: 7, x: 31, from: -60, dir: 1 },
  'ethics-ethics-27': { enter: 7, x: 30, from: -60, dir: 1 },
  'epistemology-knowledge-29': { enter: 7, x: 28, from: -60, dir: 1 },
  'aesthetics-aesthetics-30': { enter: 7, x: 29, from: -60, dir: 1 },
};
