// GENERATED by scripts/make-visitor.mjs — do not edit by hand.
//
// The second figure who walks into a lesson: which beat he arrives on, where he
// stands, which edge he comes from, and which way he turns once he is there.
//
// Only lessons whose graded beat has two sides (a `poll` of named positions, or
// a `split` between two) and which have measured floor space for him on BOTH the
// entrance beat and the question beat. See scripts/make-visitor.mjs, and group AA
// of docs/LESSON_RULES.md.

export interface VisitorCue {
  /** The beat he walks on. He is off-stage before it and standing after it. */
  enter: number;
  /** Where he stands, in stage units. */
  x: number;
  /** The off-stage x he walks in from. */
  from: number;
  /** Which way he faces once he has arrived: +1 right, −1 left. */
  dir: number;
}

export const VISITOR: Record<string, VisitorCue> = {
  'ethics-ethics-31': { enter: 8, x: 45, from: -60, dir: 1 },
  'metaphysics-being-39': { enter: 6, x: 287, from: 460, dir: -1 },
  'logic-arguments-39': { enter: 6, x: 47, from: -60, dir: 1 },
  'logic-arguments-16': { enter: 8, x: 56, from: -60, dir: 1 },
  'ethics-ethics-17': { enter: 8, x: 349, from: 460, dir: -1 },
  'epistemology-knowledge-20': { enter: 8, x: 351, from: 460, dir: -1 },
  'aesthetics-aesthetics-18': { enter: 6, x: 353, from: 460, dir: -1 },
  'aesthetics-aesthetics-21': { enter: 7, x: 357, from: 460, dir: -1 },
  'logic-arguments-19': { enter: 6, x: 157, from: -60, dir: 1 },
  'logic-arguments-21': { enter: 7, x: 351, from: 460, dir: -1 },
  'epistemology-knowledge-23': { enter: 6, x: 357, from: 460, dir: -1 },
  'metaphysics-being-21': { enter: 8, x: 47, from: -60, dir: 1 },
  'aesthetics-aesthetics-22': { enter: 8, x: 156, from: -60, dir: 1 },
  'political-political-22': { enter: 7, x: 356, from: 460, dir: -1 },
  'political-political-23': { enter: 7, x: 356, from: 460, dir: -1 },
  'ethics-ethics-37': { enter: 4, x: 153, from: -60, dir: -1 },
  'logic-arguments-23': { enter: 8, x: 40, from: -60, dir: 1 },
  'metaphysics-being-13': { enter: 6, x: 46, from: -60, dir: 1 },
  'political-political-15': { enter: 5, x: 44, from: -60, dir: 1 },
  'metaphysics-being-8': { enter: 12, x: 97, from: -60, dir: 1 },
  'ethics-ethics-14': { enter: 7, x: 257, from: 460, dir: -1 },
  'logic-arguments-40': { enter: 7, x: 32, from: -60, dir: 1 },
  'ethics-ethics-40': { enter: 7, x: 34, from: -60, dir: 1 },
};
