// GENERATED by scripts/make-marks.mjs — do not edit by hand.
//
// A hand-drawn mark on the label the narration is naming, drawn as the voice reaches
// the word, on the taps where the scene's art does not change (StageMark.tsx). See the
// generator's header for where a mark may and may not go; `check:marks` holds it.

export type MarkStyle = 'ring' | 'underline' | 'bracket' | 'box' | 'arrowL' | 'arrowR';

export interface StageMarkSpot {
  /** Index of the narration word, split on whitespace, the voice says as the mark draws. */
  w: number;
  style: MarkStyle;
  /** Where the mark is drawn, in stage units: [x, y, width, height]. */
  box: readonly [number, number, number, number];
  /** The stage label it marks, as measured. */
  label: string;
  /** The plate the label is printed on, when the mark is drawn round that instead. */
  on?: readonly [number, number, number, number];
}

export const MARKS: Record<string, Record<number, StageMarkSpot>> = {
  'aesthetics-aesthetics-10': {
    1: { w: 8, style: 'underline', box: [185.2, 448, 155.7, 8], label: "GLORY IN CRUELTY" },
  },
  'aesthetics-aesthetics-14': {
    1: { w: 5, style: 'underline', box: [249.5, 262, 134.2, 8], label: "NOTHING WRONG WITH IT" },
  },
  'aesthetics-aesthetics-15': {
    5: { w: 0, style: 'arrowL', box: [223.1, 297, 29, 16], label: "I COULD SELL IT" },
  },
  'aesthetics-aesthetics-17': {
    2: { w: 8, style: 'underline', box: [38, 320.5, 33.4, 8], label: "FEAR" },
  },
  'aesthetics-aesthetics-19': {
    4: { w: 5, style: 'underline', box: [342.9, 288, 42.1, 8], label: "MARSH" },
  },
  'aesthetics-aesthetics-21': {
    3: { w: 1, style: 'arrowL', box: [253.6, 231, 29, 16], label: "A PAINTING" },
  },
  'aesthetics-aesthetics-33': {
    4: { w: 10, style: 'underline', box: [331, 309, 39.7, 8], label: "GLAZE" },
  },
  'aesthetics-aesthetics-36': {
    1: { w: 3, style: 'underline', box: [101, 251, 179.2, 8], label: "ONE SQUARE, ONE AFTERNOON" },
  },
  'aesthetics-aesthetics-5': {
    8: { w: 8, style: 'underline', box: [257.7, 408, 92.5, 8], label: "LEAF" },
  },
  'aesthetics-aesthetics-8': {
    4: { w: 6, style: 'arrowR', box: [342.6, 304, 29, 16], label: "A PAINTING" },
  },
  'aesthetics-aesthetics-9': {
    5: { w: 5, style: 'underline', box: [51, 225, 90, 8], label: "SUPERMARKET" },
  },
  'epistemology-knowledge-15': {
    3: { w: 13, style: 'arrowL', box: [194.5, 248.4, 29, 16], label: "ADDS\nSOMETHING" },
  },
  'epistemology-knowledge-16': {
    2: { w: 5, style: 'arrowR', box: [286.6, 318, 29, 16], label: "FITS ANY RESULT" },
  },
  'epistemology-knowledge-2': {
    3: { w: 12, style: 'arrowL', box: [238.8, 313, 29, 16], label: "THE DOING" },
  },
  'epistemology-knowledge-21': {
    3: { w: 12, style: 'underline', box: [320.4, 359, 59.2, 8], label: "EVIDENCE" },
  },
  'epistemology-knowledge-24': {
    2: { w: 16, style: 'arrowR', box: [211, 229, 29, 16], label: "THE SCEPTIC'S CONCLUSION", on: [30, 222, 176, 30] },
    7: { w: 17, style: 'underline', box: [245.4, 300, 111.1, 8], label: "HERE IS ONE HAND" },
  },
  'epistemology-knowledge-35': {
    8: { w: 16, style: 'underline', box: [101, 270, 69.9, 8], label: "IT IS A ZEBRA" },
  },
  'epistemology-knowledge-39': {
    5: { w: 11, style: 'arrowL', box: [107.9, 391, 29, 16], label: "MAJORITY" },
  },
  'epistemology-knowledge-5': {
    6: { w: 2, style: 'underline', box: [15, 324, 123.5, 8], label: "ARISTOTLE’S LADDER · METAPHYSICS I" },
  },
  'epistemology-knowledge-8': {
    1: { w: 4, style: 'arrowR', box: [67.5, 431.5, 29, 16], label: "REASONS" },
    6: { w: 5, style: 'arrowL', box: [214, 276, 29, 16], label: "the timetable says so", on: [248, 255, 130, 58] },
  },
  'ethics-ethics-1': {
    14: { w: 0, style: 'arrowL', box: [252.8, 239.1, 29, 16], label: "FLOURISHING" },
  },
  'ethics-ethics-12': {
    1: { w: 5, style: 'underline', box: [174, 245.5, 47.7, 8], label: "PROMISE" },
  },
  'ethics-ethics-13': {
    1: { w: 2, style: 'underline', box: [210, 431, 60, 8], label: "COURAGE", on: [213, 398, 54, 32] },
  },
  'ethics-ethics-19': {
    5: { w: 3, style: 'arrowR', box: [342.6, 231, 29, 16], label: "SIGNED BY" },
  },
  'ethics-ethics-26': {
    2: { w: 13, style: 'underline', box: [187, 373, 48, 8], label: "PLANT", on: [190, 346, 42, 26] },
  },
  'ethics-ethics-29': {
    2: { w: 11, style: 'underline', box: [107, 255, 35.4, 8], label: "DUTY" },
    7: { w: 13, style: 'arrowL', box: [95.1, 363, 29, 16], label: "WALKS PAST" },
  },
  'ethics-ethics-31': {
    2: { w: 16, style: 'arrowR', box: [211, 219, 29, 16], label: "THE SHELF", on: [112, 216, 94, 22] },
    4: { w: 6, style: 'arrowL', box: [242.5, 273, 29, 16], label: "DUTY" },
    7: { w: 2, style: 'arrowR', box: [336.4, 273, 29, 16], label: "DUTY" },
  },
  'ethics-ethics-41': {
    7: { w: 0, style: 'underline', box: [171.5, 397, 47.1, 8], label: "DECLINE" },
  },
  'ethics-ethics-7': {
    7: { w: 0, style: 'underline', box: [13, 134, 226.2, 8], label: "ROAD A  ·  NOTHING COMING" },
  },
  'logic-arguments-12': {
    1: { w: 13, style: 'underline', box: [179.5, 392.5, 47, 8], label: "AGAINST\nUS" },
    3: { w: 7, style: 'arrowL', box: [123.3, 311, 29, 16], label: "THE ROOM YOU WERE OFFERED" },
  },
  'logic-arguments-27': {
    2: { w: 4, style: 'underline', box: [180.2, 325, 139.7, 8], label: "THIS SENTENCE IS FALSE" },
  },
  'logic-arguments-28': {
    7: { w: 11, style: 'arrowL', box: [85.1, 351, 29, 16], label: "SHOUTING FIRE" },
  },
  'logic-arguments-31': {
    2: { w: 1, style: 'arrowL', box: [182.4, 279, 29, 16], label: "CHANCE OF HEADS, NEXT FLIP" },
  },
  'logic-arguments-38': {
    5: { w: 4, style: 'arrowL', box: [236, 254, 29, 16], label: "AN ISLAND", on: [270, 250, 116, 24] },
  },
  'logic-arguments-39': {
    1: { w: 2, style: 'underline', box: [135, 247, 238.9, 8], label: "HOLD EACH CLAIM TO ITS OWN STANDARD" },
  },
  'logic-arguments-4': {
    3: { w: 20, style: 'arrowR', box: [321.3, 472, 29, 16], label: "+ true premises → COGENT" },
    7: { w: 2, style: 'arrowL', box: [6, 208, 29, 16], label: "HOW SURE IS THE CONCLUSION?" },
  },
  'logic-arguments-41': {
    3: { w: 3, style: 'underline', box: [167, 423, 74.9, 8], label: "BANK TELLERS" },
  },
  'logic-arguments-6': {
    2: { w: 11, style: 'arrowL', box: [188.1, 326, 29, 16], label: "CONSEQUENT" },
  },
  'logic-arguments-7': {
    12: { w: 8, style: 'arrowL', box: [237.9, 201.5, 29, 16], label: "THE RULE" },
  },
  'logic-arguments-8': {
    3: { w: 6, style: 'underline', box: [49.8, 112.9, 120.4, 8], label: "THEN streets wet" },
    8: { w: 7, style: 'arrowR', box: [195.9, 159.5, 29, 16], label: "WET STREETS → SO IT RAINED" },
  },
  'metaphysics-being-10': {
    9: { w: 8, style: 'underline', box: [224, 483, 126, 8], label: "REDNESS", on: [227, 448, 120, 34] },
  },
  'metaphysics-being-12': {
    1: { w: 10, style: 'arrowR', box: [299.9, 367, 29, 16], label: "THE STREAM ITSELF" },
  },
  'metaphysics-being-16': {
    2: { w: 1, style: 'underline', box: [280.9, 272, 70.2, 8], label: "UNWILLING" },
  },
  'metaphysics-being-18': {
    3: { w: 16, style: 'underline', box: [291, 333, 82, 8], label: "THE NUMBER 3", on: [294, 288, 76, 44] },
  },
  'metaphysics-being-20': {
    9: { w: 6, style: 'arrowL', box: [216, 357.5, 29, 16], label: "SIMULATED  24" },
  },
  'metaphysics-being-35': {
    2: { w: 3, style: 'arrowL', box: [74.3, 309.5, 29, 16], label: "1925" },
  },
  'metaphysics-being-40': {
    3: { w: 9, style: 'arrowR', box: [229.2, 404, 29, 16], label: "TOMORROW" },
  },
  'metaphysics-being-5': {
    4: { w: 2, style: 'underline', box: [149.1, 445, 207.8, 8], label: "EVERY FACT NEEDS A REASON" },
  },
  'metaphysics-being-6': {
    5: { w: 12, style: 'arrowL', box: [121.4, 480, 29, 16], label: "REPAIRED" },
  },
  'metaphysics-being-7': {
    6: { w: 7, style: 'underline', box: [302, 257, 56, 8], label: "tomorrow" },
  },
  'metaphysics-being-8': {
    3: { w: 10, style: 'arrowR', box: [182, 275, 29, 16], label: "YOUR CHOICE" },
  },
  'metaphysics-being-9': {
    5: { w: 20, style: 'arrowL', box: [52.3, 220, 29, 16], label: "MIND" },
    7: { w: 5, style: 'arrowR', box: [178.8, 220, 29, 16], label: "MIND" },
  },
  'political-political-11': {
    4: { w: 2, style: 'underline', box: [192.1, 484, 55.9, 8], label: "ONE SOVEREIGN" },
  },
  'political-political-20': {
    1: { w: 5, style: 'arrowL', box: [240, 247, 29, 16], label: "nothing is sacred", on: [274, 244, 108, 22] },
  },
  'political-political-23': {
    1: { w: 4, style: 'arrowR', box: [125, 265.5, 29, 16], label: "A DAUGHTER" },
  },
  'political-political-30': {
    1: { w: 4, style: 'arrowL', box: [262.3, 253, 29, 16], label: "PERFECT JUSTICE" },
  },
  'political-political-36': {
    4: { w: 5, style: 'arrowL', box: [157.8, 267, 29, 16], label: "EMPTY" },
  },
  'political-political-5': {
    8: { w: 9, style: 'arrowL', box: [98, 274, 29, 16], label: "legitimate?" },
  },
  'political-political-8': {
    1: { w: 1, style: 'arrowL', box: [209, 69, 29, 16], label: "THE MATCH  ·  FAR SIDE" },
  },
  'political-political-9': {
    6: { w: 12, style: 'arrowL', box: [263.4, 216, 29, 16], label: "THE VOTE" },
  },
};
