// GENERATED by scripts/make-marks.mjs — do not edit by hand.
//
// A hand-drawn mark on the label the narration is naming, drawn as the voice reaches
// the word, on the taps where the scene's art does not change (StageMark.tsx). See the
// generator's header for where a mark may and may not go; `check:marks` holds it.

export type MarkStyle = 'ring' | 'underline' | 'bracket' | 'box' | 'arrowL' | 'arrowR';

export interface StageMarkSpot {
  /** Index of the narration word, split on whitespace, the voice says as the mark draws. */
  w: number;
  style: MarkStyle;
  /** Where the mark is drawn, in stage units: [x, y, width, height]. */
  box: readonly [number, number, number, number];
  /** The stage label it marks, as measured. */
  label: string;
  /** The plate the label is printed on, when the mark is drawn round that instead. */
  on?: readonly [number, number, number, number];
}

export const MARKS: Record<string, Record<number, StageMarkSpot>> = {
};
