// GENERATED by `npm run make:posters` from components/subjects/posters.ts.
// Do not edit: change the poster and run it again. check:subjects fails a stale stamp.
import type { ImageSourcePropType } from 'react-native';

/** The box every picture here was drawn for: a 390dp phone's Home card, less its border. */
export const CARD_POSTER_BOX = { w: 300, h: 195 } as const;

/** Each subject's Home-shelf poster, pre-drawn (see scripts/make-poster-art.mjs). */
export const CARD_POSTER: Record<string, { source: ImageSourcePropType; stamp: string }> = {
  'philosophy': { source: require('@/assets/images/posters/card-philosophy.png'), stamp: '773b32b7015a' },
  'psychology': { source: require('@/assets/images/posters/card-psychology.png'), stamp: 'f91ba417ddf3' },
  'personal-growth': { source: require('@/assets/images/posters/card-personal-growth.png'), stamp: '807d952b2b5c' },
  'business': { source: require('@/assets/images/posters/card-business.png'), stamp: 'd44e2def6db6' },
  'economics': { source: require('@/assets/images/posters/card-economics.png'), stamp: '59b749de9112' },
  'science': { source: require('@/assets/images/posters/card-science.png'), stamp: '2da7d79f56cb' },
  'history': { source: require('@/assets/images/posters/card-history.png'), stamp: '2eebb212ad1a' },
};
