// WHERE THE FIGURE SHOULD BE LOOKING, BEAT BY BEAT.
//
//   node scripts/make-gaze.mjs            # report what it would write
//   node scripts/make-gaze.mjs --write
//
// ── WHY THIS EXISTS ─────────────────────────────────────────────────────────
//
// `moves.ts` has had `gazeAt` and `pointAt` since the rig was written, and across
// 184 cinematic scenes they are called ZERO times. `interact.ts` is a thousand
// lines of the figure's relationship to the world — `handAt`, `gripAt`,
// `carryHands`, `reachHandTo`, `propAct`, `handshake`, `passObject` — and 14 of
// its 17 exports are also called zero times. The figure narrates a diagram he
// never once looks at.
//
// A reader put it plainly, comparing the lessons with the app's own ad reels:
// "the objects interact with the stickman in a very clean and actual good looking
// way … I want the stickman more interactive with objects and lessons."
//
// ── WHY A TABLE AND NOT A CHANNEL ───────────────────────────────────────────
//
// The target is a fact about what the beat DRAWS, and the thing that already
// knows what every beat draws is `measure-must`'s recording. Asking each of 186
// scripts to declare a look-at point by hand would be 1,300 authored coordinates
// that go stale the moment a prop moves; derived from the recording, they move
// with it and `make:gaze` is re-run beside `make:tours`.
//
// ── THE TARGET IS THE PICTURE, NOT A GUESS AT THE SUBJECT ───────────────────
//
// Two rules were tried. Aiming at the thing that CHANGED since the previous beat
// is the more interesting behaviour and it is not reliable: on a beat where six
// things move it picks one arbitrarily, and on a beat where nothing moves it has
// no answer at all. Aiming at the PICTURE — the area-weighted centre of
// everything drawn that is not the figure — is never wrong in an embarrassing
// way. A presenter looks at his diagram; when a prop enters on one side the
// centre shifts and he follows it, which is the reaction without the guesswork.
//
// Weighted by the square root of area, so one large panel does not drag the look
// onto itself and away from the six small things sitting on it.
import fs from 'node:fs';
import path from 'node:path';

const DIR = 'components/lesson/cinematic';
const SIDE = path.join(DIR, 'mustBoxes.ts.json');
const OUT = path.join(DIR, 'gazeTargets.ts');
const WRITE = process.argv.includes('--write');
const ONLY = process.argv.find((a) => a.startsWith('--only='))?.slice(7);

/** Smaller than this is a tick or a hairline, and not something to look AT. */
const MIN_W = 10;
const MIN_H = 6;
/**
 * How far the target may sit from the figure before it is dropped.
 *
 * Not a reach limit — a look is not a touch. This only refuses a target that is
 * so far off that turning the head toward it would read as looking away from the
 * scene rather than into it.
 */
const MAX_LOOK = 420;

const { words } = JSON.parse(fs.readFileSync(SIDE, 'utf8'));

const table = {};
let beatsWith = 0;
let beatsWithout = 0;

for (const [id, beats] of Object.entries(words)) {
  if (!Array.isArray(beats)) continue;
  const per = [];
  for (const items of beats) {
    if (!Array.isArray(items)) { per.push(null); beatsWithout += 1; continue; }
    const fig = items.find((i) => i.k === 'fig');
    let wx = 0, wy = 0, wsum = 0;
    for (const it of items) {
      if (it.k === 'fig' || it.bleed) continue;
      const [x, y, w, h] = it.b;
      if (w < MIN_W || h < MIN_H) continue;
      const weight = Math.sqrt(w * h);
      wx += (x + w / 2) * weight;
      wy += (y + h / 2) * weight;
      wsum += weight;
    }
    if (!wsum) { per.push(null); beatsWithout += 1; continue; }
    const tx = wx / wsum;
    const ty = wy / wsum;
    if (fig) {
      const [fx, fy, fw, fh] = fig.b;
      const d = Math.hypot(tx - (fx + fw / 2), ty - (fy + fh / 2));
      if (d > MAX_LOOK) { per.push(null); beatsWithout += 1; continue; }
    }
    per.push([Math.round(tx), Math.round(ty)]);
    beatsWith += 1;
  }
  // A lesson whose every beat is null carries nothing rather than a row of nulls.
  if (per.some(Boolean)) table[id] = per;
}

if (ONLY) {
  for (const id of Object.keys(table).filter((k) => k.includes(ONLY))) {
    console.log(`${id}\n    ${JSON.stringify(table[id])}`);
  }
  process.exit(0);
}

const lines = [
  '// GENERATED by scripts/make-gaze.mjs — do not edit by hand.',
  '//',
  '// Where the figure looks on each beat, in stage units: the area-weighted centre',
  '// of everything the beat draws that is not the figure. See make-gaze.mjs for why',
  '// this is the picture rather than a guess at the beat\'s subject.',
  '//',
  '// Re-run it beside `make:tours` whenever the must-boxes are re-measured.',
  '',
  'export const GAZE: Record<string, ([number, number] | null)[]> = {',
];
for (const id of Object.keys(table).sort()) {
  const row = table[id].map((p) => (p ? `[${p[0]}, ${p[1]}]` : 'null')).join(', ');
  lines.push(`  '${id}': [${row}],`);
}
lines.push('};', '');

const text = lines.join('\n');
if (WRITE) {
  fs.writeFileSync(OUT, text, { encoding: 'utf8' });
  console.log(`generated ${OUT}`);
} else {
  console.log(`would generate ${OUT}`);
}
console.log(`  ${Object.keys(table).length} lessons · ${beatsWith} beats with a target · ${beatsWithout} without`);
